function success = createSinglePassiveLengthRampImpedanceTrial610A(...                    
                    lengthRampConfig,...
                    lengthSineOptions,...
                    stochasticWaveSet,...
                    trialFileNameNoExt,...
                    expFolders,...
                    auroraConfig)


fid = fopen(fullfile(expFolders.rootFolderPath,...
                     expFolders.protocolFolderName,...
                     [trialFileNameNoExt,'.dpf']),'w');

trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                  expFolders.blockLabelsFolderName,...
                                  [trialFileNameNoExt,'.csv']);

programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFilePath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

jsonMetaData = struct('data',[],'protocol',[],...
                      'segments',[],'experiment',[]);


jsonMetaData.data.file = {expFolders.dataFolderName, ...
                          [trialFileNameNoExt,'.ddf']};
jsonMetaData.data.sha256 = "";

jsonMetaData.protocol.file = {expFolders.protocolFolderName, ...
                          [trialFileNameNoExt,'.dpf']};
jsonMetaData.protocol.sha256 = "";


%%
%Move the specimen from a length of 0 to its starting length
%%


waitTime                    = 1;
flag_printMetaDataToFile    = 1;



numberOfSegments = length(lengthRampConfig.lengths) ...
                  + 1 ...
                  +length(stochasticWaveSet);

assert(strcmp(lengthRampConfig.options(1).unit,auroraConfig.defaultLengthUnit),...
       ['Error: the default length units and the',...
        ' length ramp units should match']);


timeFieldName = ['time_',auroraConfig.defaultTimeUnit];
cyclesFieldName ='cycles';
frequencyFieldName = ['frequency_',auroraConfig.defaultFrequencyUnit];
bandwidthFieldName = ['bandwidth_',auroraConfig.defaultFrequencyUnit];
amplitudeFieldName = ['amplitude_',auroraConfig.defaultLengthUnit]; 
lengthFieldName    = ['length_',auroraConfig.defaultLengthUnit];
isActive = 0;

segmentMetaDataArray(numberOfSegments) = ...
    struct('type','',timeFieldName,[0,0],'meta_data',[]);

for idxSeg=1:1:length(lengthRampConfig.lengths)
    segmentMetaDataArray(idxSeg).(timeFieldName) = [0,0];
    segmentMetaDataArray(idxSeg).meta_data.is_active = isActive;
    segmentMetaDataArray(idxSeg).meta_data.channel='';
    segmentMetaDataArray(idxSeg).meta_data.(lengthFieldName)=[];
    segmentMetaDataArray(idxSeg).meta_data.(timeFieldName)=[];
end

idxSeg = length(lengthRampConfig.lengths)+1;
segmentMetaDataArray(idxSeg).(timeFieldName) = [0,0];
segmentMetaDataArray(idxSeg).meta_data.is_active = isActive;
segmentMetaDataArray(idxSeg).meta_data.channel='';
segmentMetaDataArray(idxSeg).meta_data.(frequencyFieldName)=[];
segmentMetaDataArray(idxSeg).meta_data.(amplitudeFieldName)=[];
segmentMetaDataArray(idxSeg).meta_data.(cyclesFieldName)=[];

idxSegNext=idxSeg+1;

for idxSeg=idxSegNext:1:(numberOfSegments)
    segmentMetaDataArray(idxSeg).(timeFieldName) = [0,0];
    segmentMetaDataArray(idxSeg).meta_data.is_active = isActive;
    segmentMetaDataArray(idxSeg).meta_data.(bandwidthFieldName) = [0,0];
    segmentMetaDataArray(idxSeg).meta_data.(amplitudeFieldName) = 0;
end

idxSeg = 0;

for i=1:1:length(lengthRampConfig.lengths)

  lengthChangeOptions             = lengthRampConfig.options;
  lengthChangeOptions(1).value    = lengthRampConfig.lengths(i);
  lengthChangeOptions(2).value    = auroraConfig.prePostPositioningDuration;

  programMetaData ...
      = writeControlFunction610A(...
              fid,...
              waitTime,...
              'Ramp',...
              lengthChangeOptions,...
              auroraConfig,...
              programMetaData,...
              flag_printMetaDataToFile);

  idxSeg=idxSeg+1;

  segmentMetaDataArray(idxSeg).type = ...
      'Ramp';                
  segmentMetaDataArray(idxSeg).(timeFieldName) = ...
      [programMetaData.controlFunction.startTime,...
       programMetaData.controlFunction.endTime];  
  segmentMetaDataArray(idxSeg).meta_data.is_active          ...
    = isActive;
  segmentMetaDataArray(idxSeg).meta_data.channel            ...
    = lengthChangeOptions(1).port;
  segmentMetaDataArray(idxSeg).meta_data.(lengthFieldName)  ...
    =lengthRampConfig.lengths(i);
  segmentMetaDataArray(idxSeg).meta_data.(timeFieldName)    ...
    =lengthChangeOptions(2).value;
  
end

%%
% Apply a sine wave to (more quickly) bring the passive forces 
% to equilibrium
%%


sineCycles = lengthSineOptions(3).value;
sineTime   = sineCycles/lengthSineOptions(1).value;

sineTimeRounded   = ...
  round(sineTime*auroraConfig.analogToDigitalSampleRateHz)...
  /auroraConfig.analogToDigitalSampleRateHz;

assert(abs(sineTime-sineTimeRounded) < eps*10,...
       ['Error: choose another sine wave frequency or sampling frequency',...
         ' this combination will not yield the correct number of cycles']);


%
% Write the meta data
%
idxSeg=idxSeg+1;

waitTimeForBlock = auroraConfig.passive.recoveryTime;

segmentMetaDataArray(idxSeg).(timeFieldName) =  ...
  [programMetaData.nextStartTime+waitTimeForBlock,...
   programMetaData.nextStartTime+waitTimeForBlock+sineTime]; 

segmentMetaDataArray(idxSeg).type = ['Sine Wave'];
segmentMetaDataArray(idxSeg).meta_data.is_active = isActive;

segmentMetaDataArray(idxSeg).meta_data.channel            ...
    = lengthSineOptions(1).port;
segmentMetaDataArray(idxSeg).meta_data.(frequencyFieldName) = ...
  lengthSineOptions(1).value;
segmentMetaDataArray(idxSeg).meta_data.(amplitudeFieldName) = ...
  lengthSineOptions(2).value;    
segmentMetaDataArray(idxSeg).meta_data.(cyclesFieldName) = ...
  lengthSineOptions(3).value;    

programMetaData ...
        = writeControlFunction610A(...
                fid,...
                auroraConfig.passive.recoveryTime,...
                'Sine Wave',...
                lengthSineOptions,...
                auroraConfig,...                
                programMetaData,...
                flag_printMetaDataToFile);  


%%
% Perturb Passive Muscle
%%

startTimeBlock              = programMetaData.nextStartTime;
waitTimeForBlock            = auroraConfig.passive.recoveryTime;
flag_printMetaDataToFile    = 1;

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
    
end



for i=1:1:length(stochasticWaveSet)

    assert(strcmp(stochasticWaveSet(i).config.lengthUnits,...
                  auroraConfig.defaultLengthUnit),...
           ['Error: the default length units and the',...
            ' stochastic wave length units should match']);

    assert(strcmp(stochasticWaveSet(i).config.frequencyUnits,...
                  auroraConfig.defaultFrequencyUnit),...
           ['Error: the default frequency units and the',...
            ' stochastic wave frequency units should match']);

    assert(strcmp(stochasticWaveSet(i).config.timeUnits,...
                  auroraConfig.defaultTimeUnit),...
           ['Error: the default time units and the',...
            ' stochastic wave time units should match']);

    %
    % Write the meta data
    %
    idxSeg=idxSeg+1;
    
    singleWaveDuration = (stochasticWaveSet(i).config.points...
                         /stochasticWaveSet(i).config.frequencyHz);

    segmentMetaDataArray(idxSeg).(timeFieldName) =  ...
      [programMetaData.nextStartTime+waitTimeForBlock,...
       programMetaData.nextStartTime+waitTimeForBlock+singleWaveDuration]; 

    segmentMetaDataArray(idxSeg).type = [stochasticWaveSet(i).controlFunction,'-Stochastic'];
    segmentMetaDataArray(idxSeg).meta_data.is_active = isActive;
    segmentMetaDataArray(idxSeg).meta_data.(bandwidthFieldName) = ...
      stochasticWaveSet(i).config.frequencyRange;
    segmentMetaDataArray(idxSeg).meta_data.(amplitudeFieldName) = ...
      max(stochasticWaveSet(i).config.magnitudeRange);    

    %
    % Write the wave
    %
    
    switch stochasticWaveSet(i).controlFunction
        case 'Step'

            stepLengths = stochasticWaveSet(i).optionValues(:,1) ...
                         +lengthRampConfig.lengths(end);

            programMetaData = ...
                writeLengthStepBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stepLengths,...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);      
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end




end

jsonMetaData.segments = segmentMetaDataArray;
jsonMetaData.experiment.title = ...
  sprintf('Passive Impedance %1.1f %s',...
          lengthRampConfig.lengths(end), ...
          auroraConfig.defaultLengthUnit);


endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs(endTimeBlock-startTimeBlock...
          -(waitTimeForBlock*length(stochasticWaveSet)+waveDurationInS )) < 1e-2,...
       'Error: timing meta data is incorrect');

waitTime            = auroraConfig.passive.recoveryTime;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


jsonMetaDataEncoded = jsonencode(jsonMetaData);
fidJson = fopen(fullfile(expFolders.rootFolderPath,...
                         [trialFileNameNoExt,'.json']),'w');
fprintf(fidJson,jsonMetaDataEncoded);
fclose(fidJson);

fclose(fid);
fclose(programMetaData.labelFileHandle);
