function programMetaData = ...
    writeTwitchProbeBlock610A(...
            fid, ...
            waitTime, ...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile)

assert(strcmp(auroraConfig.defaultTimeUnit,'s'),...
    'Error: auroraConfig.defaultTimeUnit must be s');

stimOptions = getCommandFunctionOptions610A(...
                'Stimulus-Twitch','Stimulator',auroraConfig);

stimOptions(1).value = 0;
stimOptions(2).value = auroraConfig.twitch.pulseWidthMs;


programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Stimulus-Twitch',...
            stimOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);