function spectrumError = calcWavePowerSpectrumError(...
                          arg, fcnWave,...
                          configVibration,...
                          objScale)


[timeVec,...
signalVec,...
stochasticFunctions,...
numberOfStochasticWaveCommands] = fcnWave(arg);

spectrum = analyzeSignalSpectrum(timeVec, signalVec,configVibration);

npts=length(arg);
freqSampleHz = [0:(1/(npts-1)):1]' ...
                .* diff(configVibration.frequencyRange) ...
                   +  min(configVibration.frequencyRange);

pwrSampleHz = interp1(spectrum.fwHz,spectrum.pw,freqSampleHz);
pwrSampleHz = pwrSampleHz./max(pwrSampleHz);

spectrumError = (pwrSampleHz-1)./objScale;
