function success = constructInjuryExperiments610A(  ...
                        stochasticWaveSet,...
                        perturbationConfig,...    
                        auroraConfig,...
                        expConfig,...
                        projectFolders)


seriesName = 'injury';
disp('constructInjuryExperiments610A running');

%%
% Check (some) of the inputs
%%
success=0;
assert(strcmp(auroraConfig.defaultTimeUnit,'s'),...
       'Error: printed time values configured for s only.');
assert(strcmp(auroraConfig.defaultLengthUnit,'mm'),...
      'Error: Assumed length unit is mm');
%%
%Experiment configuration
%%
lengthRampOptions=getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

passiveLengthRampConfig(2) =      ...
    struct( 'wait',0,'waitPostRamp',0,...
            'normLengths',[0,0],'normLengthChange',0, 'endNormLength', 0, ...    
            'lengths',[0,0],'lengthChange',0, 'endLength',0,...
            'velocity',0,'duration',0,'options',[],...
            'type','');%,'port','');

isometricConfig(3) =  ...            
    struct( 'normLengths',[0],...        
            'endNormLength',0,...
            'lengths',[0],...
            'endLength',0,...
            'options',[],...
            'type','');%,'port','');

activeLengthRampConfig(4) =  ...
    struct( 'wait',0,'waitPostRamp',0,...
            'normLengths',[0,0],'normLengthChange',0, 'endNormLength', 0, ...    
            'lengths',[0,0],'lengthChange',0, 'endLength',0,...
            'velocity',0,'duration',0,'options',[],...
            'type','');%,'port','');


activeLengtheningInjury(1) = ...
    struct( 'wait',0,'waitPostRamp',0,...
            'normLengths',[0,0],'normLengthChange',0, 'endNormLength', 0, ...    
            'lengths',[0,0],'lengthChange',0, 'endLength',0,...
            'velocity',0,'duration',0,'options',[],...
            'type','');%,'port','');

% If the amount of activation time needs to be reduced then adjust
% 1. Remove the square wave perturbations
% 2. Reduce the active post-ramp wait time
% 

%
% Passive-lengthening injury
%


assert(length(passiveLengthRampConfig) ...
        == length(expConfig.passive.normVelocityRange),...
        ['Error: Length of passiveLengthRampConfig and ',...
         'expConfig.passive.normVelocityRange do not match']);

for i=1:1:length(passiveLengthRampConfig)

    passiveLengthRampConfig(i).wait         = 1;
    passiveLengthRampConfig(i).waitPostRamp = 5; 
    passiveLengthRampConfig(i).normLengths  = expConfig.passive.normLengths;
    passiveLengthRampConfig(i).normLengthChange = ...
        diff(passiveLengthRampConfig(i).normLengths);


    passiveLengthRampConfig(i).lengths      = ...
        passiveLengthRampConfig(i).normLengths...
        .*auroraConfig.approximateSampleLengthInDefaultUnits;

    passiveLengthRampConfig(i).lengthChange = ...
        diff(passiveLengthRampConfig(i).lengths);


    passiveLengthRampConfig(i).velocity     = ...
                expConfig.passive.normVelocityRange(1,i)...
                *auroraConfig.maximumRampSpeedInDefaultUnits;        

    passiveLengthRampConfig(i).duration     = ...
        passiveLengthRampConfig(i).lengthChange ...
        ./ passiveLengthRampConfig(i).velocity;


    passiveLengthRampConfig(i).endNormLength = expConfig.endNormLength;
    passiveLengthRampConfig(i).endLength     = ...
        passiveLengthRampConfig(i).endNormLength ...
        .*auroraConfig.approximateSampleLengthInDefaultUnits;

    passiveLengthRampConfig(i).options      = lengthRampOptions;  
    passiveLengthRampConfig(i).type         = 'Passive-Length-Ramp';

end

%%
% Isometric
%%


n=length(isometricConfig);
n01 = [0:(1/(n-1)):1]';

flag_optimalLengthTested=0;


normLengths = zeros(length(isometricConfig),1);
for i=1:1:length(isometricConfig)
    normLength(i,1) = expConfig.isometric.normLengthRange(1,1).*(1-n01(i,1)) ...
                    + expConfig.isometric.normLengthRange(1,2).*(n01(i,1)); 
end

normLength = [normLength;0];
normLength = unique(sort(normLength));

if(length(normLength) > length(isometricConfig))
    n = length(normLength);
    isometricConfig(n) =  ...            
        struct( 'normLengths',[0],...        
                'endNormLength',0,...
                'lengths',[0],...
                'endLength',0,...
                'options',[],...
                'type','');%,'port','');    
end

flag_normLengthTested = 0;

for i=1:1:length(isometricConfig)

    isometricConfig(i).normLengths = normLength(i,1);
    isometricConfig(i).lengths = ...
        isometricConfig(i).normLengths...
            *auroraConfig.approximateSampleLengthInDefaultUnits;

    isometricConfig(i).endLength = 0;
    isometricConfig(i).endNormLength = ...
        isometricConfig(i).endLength...
        .*auroraConfig.approximateSampleLengthInDefaultUnits;

    isometricConfig(i).options = lengthRampOptions;
    isometricConfig(i).type = 'Isometric';

    if(abs(normLength(i,1))<1e-6)
        flag_normLengthTested=1;
    end
end

assert(flag_normLengthTested==1,'Error: the optimal length is not tested');

%
% Active-lengthening ramp
%

%activeLengthRampConfig(4) = struct('wait',0,'waitPostRamp',0,...
%                    'lengths',[0,0],'lengthChange',0,...
%                    'velocity',0,'duration',0,'options',[],'type','');

assert(length(activeLengthRampConfig) == ...
        length(expConfig.activeRamp.normVelocityRange),...
        ['Error: Number of trials in expConfig.activeRamp.normVelocityRange ',...
         'does not match the size of activeLengthRampConfig']);

assert(length(activeLengthRampConfig) == ...
        size(expConfig.activeRamp.normLengthRange,1),...
        ['Error: Number of trials in expConfig.activeRamp.normLengthRange ',...
         'does not match the size of activeLengthRampConfig']);


k=1;

for j=1:1:4

    normLengths = expConfig.activeRamp.normLengthRange(j,:);
    velocity    = expConfig.activeRamp.normVelocityRange(j,1) ...
                 *auroraConfig.maximumSpeedInDefaultUnits;

    activeLengthRampConfig(k).wait              = ...
        auroraConfig.timeToReachMaxActivation;


    activeLengthRampConfig(k).normLengths       = normLengths;
    activeLengthRampConfig(k).normLengthChange  = ...
        diff(activeLengthRampConfig(k).normLengths);

    activeLengthRampConfig(k).lengths      = ...
        activeLengthRampConfig(k).normLengths ...
        .*auroraConfig.approximateSampleLengthInDefaultUnits;

    activeLengthRampConfig(k).lengthChange = ...
        diff(activeLengthRampConfig(k).lengths);
    activeLengthRampConfig(k).velocity     = velocity;
    activeLengthRampConfig(k).duration     = ...
        activeLengthRampConfig(k).lengthChange ...
        ./ activeLengthRampConfig(k).velocity;

    activeLengthRampConfig(k).endLength         = expConfig.endNormLength;
    activeLengthRampConfig(k).endNormLength     = ...
            activeLengthRampConfig(k).endLength ...
            .*auroraConfig.approximateSampleLengthInDefaultUnits;

    activeLengthRampConfig(k).options           = lengthRampOptions;  
    if(velocity > 0)
        activeLengthRampConfig(k).type = 'Active-Lengthening';
    else
        activeLengthRampConfig(k).type = 'Active-Shortening';
    end
    k=k+1;
end

%
% Active-lengthening injury
%

assert( size(expConfig.activeInjury.normLengthRange,1) ...
         == length(activeLengtheningInjury), ...
       ['Error: rows in expConfig.activeInjury.normLengthRange ',...
        'should match length of activeLengtheningInjury']);

assert( size(expConfig.activeInjury.normVelocityRange,1) ...
         == length(activeLengtheningInjury), ...
       ['Error: rows in expConfig.activeInjury.normLengthRange ',...
        'should match length of activeLengtheningInjury']);


for i=1:1:length(activeLengtheningInjury)
    activeLengtheningInjury(i).wait         = ...
        zeros(size(expConfig.activeInjury.normLengthRange));

    activeLengtheningInjury(i).normLengths  = ...
        expConfig.activeInjury.normLengthRange(i,:);

    activeLengtheningInjury(i).normLengthChange = ...
        diff(activeLengtheningInjury(i).normLengths);

    activeLengtheningInjury(i).lengths      = ...
        activeLengtheningInjury(i).normLengths ...
        .*auroraConfig.approximateSampleLengthInDefaultUnits;

    activeLengtheningInjury(i).lengthChange = ...
        diff(activeLengtheningInjury(i).lengths);

    activeLengtheningInjury(i).velocity     = ...
        expConfig.activeInjury.normVelocityRange(i,:) ...
            .*auroraConfig.maximumRampSpeedInDefaultUnits;

    activeLengtheningInjury(i).duration     = ...
        activeLengtheningInjury(i).lengthChange ...
        ./ activeLengtheningInjury(i).velocity;

    activeLengtheningInjury(i).endLength = 0;
    activeLengtheningInjury(i).endNormLength = ...
            activeLengtheningInjury(i).endLength ...
            .*auroraConfig.approximateSampleLengthInDefaultUnits;

    activeLengtheningInjury(i).options      = lengthRampOptions;  
    activeLengtheningInjury(i).type         = 'Active-Lengthening-Injury';
end


%%
%Make the output folders, if necessary
%%
[dateId, dateDir, codeDir, codeLabelDir] = ...
    makeExperimentSeriesFolders(seriesName, projectFolders);

%%
% 
%%

fidProtocol = fopen(fullfile(codeDir,['protocol_',dateId,'.csv']),'w');

fprintf(fidProtocol,'%s,%s,%s,%s,%s,%s\n',...
    'Number','Type','Starting_Length_Lo',...
    'Block','FileName','Comment');

%%
%
% Characterization Block Round 1
%
%%
characterizationMetaData.codeDir        = codeDir;
characterizationMetaData.codeLabelDir   = codeLabelDir;
characterizationMetaData.fidProtocol    = fidProtocol;
characterizationMetaData.seriesName     = seriesName;
characterizationMetaData.dateId         = dateId;

startingIndex=1;
idx = createCharacterizationTrialSet610A( ...
        startingIndex,...
        isometricConfig,...
        passiveLengthRampConfig,...
        activeLengthRampConfig,...
        stochasticWaveSet,...
        perturbationConfig,...        
        auroraConfig,...
        projectFolders,...
        characterizationMetaData);


%%
%
% Injury Trial
%
%%

idxStr = getTrialIndexString(idx);

startLength = activeLengtheningInjury(1).normLengths(1,1)+1;
typeOfTrial = 'injury';
blockName   = 'Injury';
fname       = getTrialName(seriesName,idx,typeOfTrial,startLength,dateId,'.dpf');
fnameLabels = getTrialName(seriesName,idx,typeOfTrial,startLength,[dateId,'_labels'],'.csv');

fprintf(fidProtocol,'%s,%s,%1.1f,%s,%s,%s\n',...
    idxStr,typeOfTrial,startLength, blockName,fname,'');

success = createActiveLengthRampSeriesTrial610A(...
                    activeLengtheningInjury,...
                    fullfile(codeDir,fname),...
                    fullfile(codeLabelDir,fnameLabels),...
                    auroraConfig);

%%
%
% Characterization Block Round 2
%
%%
idx=idx+1;

idx = createCharacterizationTrialSet610A( ...
        idx,...
        isometricConfig,...
        passiveLengthRampConfig,...
        activeLengthRampConfig,...
        stochasticWaveSet,...
        perturbationConfig,...        
        auroraConfig,...
        projectFolders,...
        characterizationMetaData);


fclose(fidProtocol);
success=1;