function trialId = constructDegradationExperiment610A(...
                        dateId,...
                        trialId,...
                        degradationConfig,...
                        expFolders,...
                        projectFolders)

if(isempty(expFolders))
  degradationFolderName     = 'degradation';
  dataFolderName        = 'data';
  protocolFolderName    = 'protocols';
  blockLabelsFolderName = 'segmentLabels';

  codeDir         = ...
    fullfile(projectFolders.output_code,[dateId,'_610A']); 

  if(~exist(codeDir,'dir'))
    mkdir(codeDir);
  end

  degradationDir         = ...
    fullfile(codeDir,degradationFolderName); 

  if(~exist(degradationDir,'dir'))
    mkdir(degradationDir);
  end
  
  degradationDataDir         = ...
    fullfile(degradationDir,dataFolderName); 

  if(~exist(degradationDataDir,'dir'))
    mkdir(degradationDataDir);
  end
  
  degradationProtocolDir         = ...
    fullfile(degradationDir,protocolFolderName); 

  if(~exist(degradationProtocolDir,'dir'))
    mkdir(degradationProtocolDir);
  end
  
  degradationLabelDir         = ...
    fullfile(degradationDir,blockLabelsFolderName);

  if(~exist(degradationLabelDir,'dir'))
    mkdir(degradationLabelDir);
  end
  
  expFolders.rootFolderPath         = degradationDir;
  expFolders.dataFolderName         = dataFolderName;
  expFolders.protocolFolderName     = 'protocols';
  expFolders.blockLabelsFolderName  = 'segmentLabels';
end

%%
% Create the files
%%

flag_printMetaDataToFile = 1;


for idxFile=1:1:2


  switch idxFile
    case 1
      sampleFrequency = degradationConfig.tetanus.sampleFrequency;

      auroraConfig = getDefaultAuroraConfiguration610A(...
                          degradationConfig.muscleName,...
                          degradationConfig.unitSystem,...
                          sampleFrequency,...    
                          degradationConfig.lceOptMM,...
                          degradationConfig.vceMaxLPS);

      seriesName = '';
      idxP = trialId;
      type = 'tetanus';
      
      trialFileNameNoExt  = getTrialName(seriesName,idxP,type,[],...
                      auroraConfig.defaultLengthUnit, dateId,'');
    case 2

      sampleFrequency = degradationConfig.sineWave.sampleFrequency;

      auroraConfig = getDefaultAuroraConfiguration610A(...
                          degradationConfig.muscleName,...
                          degradationConfig.unitSystem,...
                          sampleFrequency,...    
                          degradationConfig.lceOptMM,...
                          degradationConfig.vceMaxLPS);      
      seriesName = '';
      idxP = trialId;
      type = 'sine_wave';
      
      trialFileNameNoExt  = getTrialName(seriesName,idxP,type,[],...
                      auroraConfig.defaultLengthUnit, dateId,'');      
    otherwise
      assert(0,'Error: this loop is only configured for 2 files')
  end

  fid = fopen(fullfile(expFolders.rootFolderPath,...
                       expFolders.protocolFolderName,...
                       [trialFileNameNoExt,'.dpf']),'w');
 
  
  trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                    expFolders.blockLabelsFolderName,...
                                    [trialFileNameNoExt,'.csv']);
  
  programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFilePath);
  programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);
  
  jsonMetaData = struct('data',[],'protocol',[],...
                        'segments',[],'experiment',[]);
  
  jsonMetaData.data.file = {expFolders.dataFolderName, ...
                            [trialFileNameNoExt,'.ddf']};
  jsonMetaData.data.sha256 = "";
  
  jsonMetaData.protocol.file = {expFolders.protocolFolderName, ...
                            [trialFileNameNoExt,'.dpf']};
  jsonMetaData.protocol.sha256 = "";
  
  %
  % Meta data 
  %
  
  mdfn = getMetaDataFieldNames610A(auroraConfig);
  numberOfSegments=1;
  
  segmentMetaDataArray(numberOfSegments) = ...
      struct('type','',mdfn.time,[0,0],'meta_data',[]);
  
  switch idxFile
    case 1

      %
      % Meta data
      %
      stimulusTetanusOptions = getCommandFunctionOptions610A(...
                                'Stimulus-Tetanus','Stimulator',auroraConfig);
      
      stimulusTetanusOptions(1).value=degradationConfig.tetanus.initialDelay;
      stimulusTetanusOptions(2).value=degradationConfig.tetanus.pulseFrequency;
      stimulusTetanusOptions(3).value=degradationConfig.tetanus.pulseWidth;
      stimulusTetanusOptions(4).value=degradationConfig.tetanus.duration;

      startTime = degradationConfig.waitTime;
      endTime   = startTime ...
                  +degradationConfig.tetanus.initialDelay ...
                  +degradationConfig.tetanus.duration;
      
      idxSeg=1;
      segmentMetaDataArray(idxSeg).type = 'Stimulus-Tetanus';
      segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime];
      segmentMetaDataArray(idxSeg).meta_data.is_active = 1;
      segmentMetaDataArray(idxSeg).meta_data.channel= ...
        stimulusTetanusOptions(1).port;
      
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.initialDelay)  = ...
        degradationConfig.tetanus.initialDelay;
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.pulseFrequency)= ...
        degradationConfig.tetanus.pulseFrequency;  
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.pulseWidth)    = ...
        degradationConfig.tetanus.pulseWidth;
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.duration)      = ...
        degradationConfig.tetanus.duration;

      %
      % Command
      %
         
      
      programMetaData = writeControlFunction610A(...
                          fid,...
                          degradationConfig.waitTime,...
                          'Stimulus-Tetanus',...
                          stimulusTetanusOptions,...
                          auroraConfig,...                
                          programMetaData,...
                          flag_printMetaDataToFile); 
      
      endTimeError = endTime - programMetaData.controlFunction.endTime;
      assert(abs(endTimeError)<1e-3,...
          'Error: end time differs from the meta data');  

      waitTime = degradationConfig.waitTime ...
                + degradationConfig.tetanus.duration;

      programMetaData = ...
          writeClosingBlock610A(...
              fid,...
              waitTime,...
              auroraConfig,...
              programMetaData,...
              flag_printMetaDataToFile);
      
      success = 1;
      assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
          'Error: maximumNumberOfCommandsExceeded');      

    case 2

      %
      % Meta data
      %
      sineTime =  degradationConfig.sineWave.cycles ...
                 /degradationConfig.sineWave.frequency;
      sineTimeRounded = ...
        round(sineTime*auroraConfig.analogToDigitalSampleRateHz) ...
        /auroraConfig.analogToDigitalSampleRateHz;
      
      assert(abs(sineTime-sineTimeRounded) < 10*eps,...
             ['Error: the combination of the a/d sample rate and the ' ...
              'sine frequency will not yield the desired number of cycles']);

      lengthSineOptions = getCommandFunctionOptions610A(...
                            'Sine Wave','Length Out',auroraConfig);
      lengthSineOptions(1).value = degradationConfig.sineWave.frequency;
      lengthSineOptions(2).value = degradationConfig.sineWave.amplitude;
      lengthSineOptions(3).value = degradationConfig.sineWave.cycles;
      

      startTime = degradationConfig.waitTime;
      endTime   = startTime ...
                  +degradationConfig.sineWave.waitTime ...
                  +sineTime;
      
      
      segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime]; 
      
      segmentMetaDataArray(idxSeg).type = ['Sine Wave'];
      segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
      
      segmentMetaDataArray(idxSeg).meta_data.channel            ...
          = lengthSineOptions(1).port;
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.frequency) = ...
        lengthSineOptions(1).value;
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.amplitude) = ...
        lengthSineOptions(2).value;    
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.cycles) = ...
        lengthSineOptions(3).value;    
      
      %
      % Write the protocol
      %
      programMetaData ...
              = writeControlFunction610A(...
                      fid,...
                      degradationConfig.waitTime,...
                      'Sine Wave',...
                      lengthSineOptions,...
                      auroraConfig,...                
                      programMetaData,...
                      flag_printMetaDataToFile);  

      endTimeError = endTime - programMetaData.controlFunction.endTime;
      assert(abs(endTimeError)<1e-3,...
          'Error: end time differs from the meta data');  

  
      programMetaData = ...
          writeClosingBlock610A(...
              fid,...
              degradationConfig.waitTime,...
              auroraConfig,...
              programMetaData,...
              flag_printMetaDataToFile);
      
      success = 1;
      assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
          'Error: maximumNumberOfCommandsExceeded');      

    otherwise
      assert(0,'Error: this file is only configured for 2 files');
  end


  %
  % Write the json files
  %
  jsonMetaData.segments = segmentMetaDataArray;

  switch idxFile
    case 1
      jsonMetaData.experiment.title = ...
        sprintf('Tetanus: %1.1f%s %1.1f%s %1.1f%s',...
                degradationConfig.tetanus.pulseFrequency, ...
                auroraConfig.defaultFrequencyUnit,...
                degradationConfig.tetanus.pulseWidth,...
                auroraConfig.defaultPulseWidthTimeUnit,...
                degradationConfig.tetanus.duration,...
                auroraConfig.defaultTimeUnit);
        jsonMetaData.experiment.tags = {'degradation'};
    case 2
      jsonMetaData.experiment.title = ...
        sprintf('Passive Sine Wave: %1.1f%s %1.1f%s %1.1f %s',...
                degradationConfig.sineWave.frequency, ...
                auroraConfig.defaultFrequencyUnit,...
                degradationConfig.sineWave.amplitude,...
                auroraConfig.defaultLengthUnit,...
                degradationConfig.sineWave.cycles,...
                'cycles');
        jsonMetaData.experiment.tags = {'recovery'};
    otherwise
      assert(0,'Error: this file is only configured for 2 files');      
  end

  
  jsonMetaDataEncoded = jsonencode(jsonMetaData);
  fidJson = fopen(fullfile(expFolders.rootFolderPath,...
                           [trialFileNameNoExt,'.json']),'w');
  fprintf(fidJson,jsonMetaDataEncoded);
  fclose(fidJson);
  
  fclose(fid);
  fclose(programMetaData.labelFileHandle);


  trialId=trialId+1;
end
