function success = constructNormalizationExperiments610A(...
                        stochasticWaveScalesToTest,...
                        stochasticWaveSet,...
                        perturbationConfig,...
                        auroraConfig,...
                        expConfig,...
                        projectFolders)

success=0;
seriesName='normalization';

%Instructions
%1. Stretch specimen until it develops some passive force
%2. 3 second isometric stimulation
%3. Put the motor at the +10mm position
%4. Manually stretch to develop half of this force passively
%5. Run the stimulate and shorten protocol. Identify
%   a. lref: Specimen length at lopt. Manually set 0 here
%   b. lzero: Specimen length at which the force-length relation goes to 0.
%             Identify by linear extrapolation
%   c. lceOpt, 0.6*lceOpt = (lzero - lref)
%6. Identify fiso using a 5 second stimulation at lref
%7. Identify lpeHalf, the length at which a passive force of fmax*0.5 is reached
%8. Use force-ramp from lopt to identify the maximum shortening velocity
%9. Use active lengthening from lopt to 1.2 lopt, with pause to identify titin
%   properties


%%
%Make the output folders, if necessary
%%
[dateId,dateDir, codeDir, codeLabelDir] = makeExperimentSeriesFolders(...
                                                seriesName,...
                                                projectFolders);

%%
% Generate the instructions file
%%

fidInstructions = fopen(fullfile(codeDir,['instructions_',dateId,'.txt']),'w');

fprintf(fidInstructions,'%s\n',...
    '1. Using the dial, manually stretch specimen until it develops some passive force. Write down dial position X-10');

fprintf(fidInstructions,'%s\n',...
    '2. Run normalization_01_isometric.dpf and write down the maximum force (f0)');

fprintf(fidInstructions,'%s\n',...
    ['3. Using the dial, manually make the specimen slack by at least 10mm. Write down dial position X-10 ',...
        'Run normalization_02_motorTo10mm.dpf']);

fprintf(fidInstructions,'%s\n',...
    '4. Using the dial, manually stretch specimen (using the dial) until it passively develops 0.5 f0. Write down dial position.');

fprintf(fidInstructions,'%s\n',...
    '5. Run normalization_03_activeForceLength.dpf, and record');
fprintf(fidInstructions,'%s\n',...
    '  a. lref: specimen length at at fmax.');
fprintf(fidInstructions,'%s\n',...
    '  b. lzero: extrapolated length at which the active force is zero.');
fprintf(fidInstructions,'%s\n',...
    '  c. lceOpt, where 0.6*lceOpt = lzero-lref');

fprintf(fidInstructions,'%s\n',...
    '6. Adjust:');
fprintf(fidInstructions,'%s\n',...
    ['  a. Machine: Using the dial, manually adjust end so that the specimen has a length ',...
        'of lref at a motor position of 0. ']);

fprintf(fidInstructions,'%s\n',...
    '7. Run normalization_04_isometricForce.dpf, and record');
fprintf(fidInstructions,'%s\n',...
    '  a. Record fmax');

fprintf(fidInstructions,'%s\n',...
    '8. Measure lpeHalf, the distance from lref at which fpe = 1/2 fmax');
fprintf(fidInstructions,'%s\n',...
    '  a. Note current manual length setting.');
fprintf(fidInstructions,'%s\n',...
    '  b. Using the dial, manually stretch specimen until it passively develops 0.5 fmax');
fprintf(fidInstructions,'%s\n',...
    ['  c. Record lpeHalf']);
fprintf(fidInstructions,'%s\n',...
    ['  d. Using the dial, manually return the length to lref using the dial']);


fprintf(fidInstructions,'%s\n',...
    '9. Run normalization_05_forceVelocity_EDL.dpf or normalization_05_forceVelocity_SOL.dpf, and record');
fprintf(fidInstructions,'%s\n',...
    '  a. vmax in mm/s');


fprintf(fidInstructions,'%s\n',...
    '10. Update:');
fprintf(fidInstructions,'%s\n',...
    ['  a. normalization/metaData_',dateId,'.csv']);
fprintf(fidInstructions,'%s\n',...
    ['  b. main_generateProjectMimeProtocols610A.m']);
fprintf(fidInstructions,'%s\n',...
    ['  c. Using main_generateProjectMimeProtocols610A.m generate new protocol']);

fprintf(fidInstructions,'%s\n',...
    '11. Run updated normalization_07_impedance.dpf');

fprintf(fidInstructions,'%s\n',...
    ['Note: Save all generated data files using the same name as the dpf file'...
    ' but with the extension of ddf (the usual data file extension)']);

fclose(fidInstructions);

%%
% Generate the corresponding protocol files
%%


fidProtocol = fopen(fullfile(codeDir,['protocol_',dateId,'.csv']),'w');

fprintf(fidProtocol,'%s,%s,%s,%s,%s,%s\n',...
    'unit_system',auroraConfig.unitSystem,'',...
    '','','');

fprintf(fidProtocol,'%s,%s,%s,%s,%s,%s\n',...
    'Number','Type','Starting_Length_Lo',...
    'Block','FileName','Comment');

fprintf(fidProtocol,'%s,%s,%1.1f,%s,%s,%s\n',...
    '-','-',0, '-','instructions.txt','Read instructions');

%%
% Write the empty metadata file
%%

fidMetaData = fopen(fullfile(codeDir,['metaData_',dateId,'.csv']),'w');

fprintf(fidMetaData,'\"animal_name\",rat\n');
fprintf(fidMetaData,'\"time_of_death\",n');
fprintf(fidMetaData,'\"time_of_experiment\",\n');
fprintf(fidMetaData,'\"muscle_name\",\n');
fprintf(fidMetaData,'\"sex\",\n');
fprintf(fidMetaData,'\"daily_muscle_count\",\n');
fprintf(fidMetaData,'\"lceOpt_mm\",\n');
fprintf(fidMetaData,'\"fmax_mN\",\n');
fprintf(fidMetaData,'\"vmax_mmps\",\n');
fprintf(fidMetaData,'\"temperature_C\",\n');
fprintf(fidMetaData,'\"musculotendon_length_mm\",\n');
fprintf(fidMetaData,'\"proximal_tendon_length_mm\",\n');
fprintf(fidMetaData,'\"distal_tendon_length_mm\",\n');
fprintf(fidMetaData,'\"muscle_length_mm\",\n');
fprintf(fidMetaData,'\"muscle_width_mm\",\n');
fprintf(fidMetaData,'\"muscle_mass_g\",\n');
fprintf(fidMetaData,'\"photo_with_ruler_taken\",\n');

fclose(fidMetaData);

%%
% Common variables
%%
lengthRampOptions=getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);


%%
%
% normalization_01_isometric.dpf
%
%%

idx=1;
idxStr = getTrialIndexString(idx);

typeOfTrial = 'isometric';
blockName   = 'normalization';
fname       = getTrialName(seriesName,idx,typeOfTrial,[],dateId,'.dpf');
fnameLabels = getTrialName(seriesName,idx,typeOfTrial,[],[dateId,'_labels'],'.csv');


fprintf(fidProtocol,'%s,%s,%s,%s,%s,%s\n',...
    idxStr,typeOfTrial,'-', blockName,fname,'See instructions 1 and 2');

fid                 = fopen(fullfile(     codeDir,fname      ),'w');
fullFilePathLabels  = fullfile(codeLabelDir,fnameLabels);

programMetaData = getEmptyProgramMetaDataStruct(fullFilePathLabels);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

%%
%Move the specimen to a length of 0
%%

waitTime                        = 0;
flag_printMetaDataToFile        = 1;

lengthRampOptions(1).value      = 0;
lengthRampOptions(2).value      = auroraConfig.prePostPositioningDuration;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

stimulationDurationInS = auroraConfig.stimulation.maxDuration;

waitTime=auroraConfig.passive.recoveryTime;

programMetaData = ...
    writeStimulusTetanusBlock610A(...
        fid,...
        waitTime, ...
        stimulationDurationInS,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


waitTime =   stimulationDurationInS ...
           + auroraConfig.restTimeBetweenActivations;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


%%
%
% normalization_02_motorTo10mm.dpf
%
%%

idx=idx+1;
idxStr = getTrialIndexString(idx);

typeOfTrial = 'repositionMotor';
blockName   = 'normalization';
fname       = getTrialName(seriesName,idx,typeOfTrial,[],dateId,'.dpf');
fnameLabels = getTrialName(seriesName,idx,typeOfTrial,[],[dateId,'_labels'],'.csv');


fprintf(fidProtocol,'%s,%s,%s,%s,%s,%s\n',...
    idxStr,typeOfTrial,'-', blockName,fname,'See instruction 3 and 4');

fid                 = fopen(fullfile(     codeDir,fname      ),'w');
fullFilePathLabels  = fullfile(codeLabelDir,fnameLabels);

programMetaData = getEmptyProgramMetaDataStruct(fullFilePathLabels);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

%%
%Move the specimen to a length of 0
%%

waitTime                        = 0;
flag_printMetaDataToFile        = 1;

lengthRampOptions(1).value      = 7; %mm
lengthRampOptions(2).value      = 10; %s

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

waitTime = auroraConfig.stop.waitTime;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


%%
%
% normalization_03_activeForceLength.dpf
%
%%
idx=idx+1;
idxStr = getTrialIndexString(idx);

typeOfTrial = 'twitchForceLength';
blockName   = 'normalization';
fname       = getTrialName(seriesName,idx,typeOfTrial,[],dateId,'.dpf');
fnameLabels = getTrialName(seriesName,idx,typeOfTrial,[],[dateId,'_labels'],'.csv');


fprintf(fidProtocol,'%s,%s,%s,%s,%s,%s\n',...
    idxStr,typeOfTrial,'-', blockName,fname,'See instruction 5');

fid                 = fopen(fullfile(     codeDir,fname      ),'w');
fullFilePathLabels  = fullfile(codeLabelDir,fnameLabels);

programMetaData = getEmptyProgramMetaDataStruct(fullFilePathLabels);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

%%
%Move the specimen to a length of 0
%%

waitTime                        = 0;
flag_printMetaDataToFile        = 1;

lengthDelta = -1; %1mm;
lengthStart = 7;
lengthEnd   = -10;
n = (lengthEnd-lengthStart)/lengthDelta;


for i=1:1:(n+1)

    motorPosition = lengthStart+lengthDelta*(i-1);
    assert(motorPosition <= 10 && motorPosition >= -10,...
           'Error: motor is out of the bound [-10,10]');

    lengthRampOptions(1).value      = motorPosition; %mm
    lengthRampOptions(2).value      = auroraConfig.prePostPositioningDuration; %second

    programMetaData ...
        = writeControlFunction610A(...
                fid,...
                waitTime,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);

    waitTime = auroraConfig.passive.recoveryTime;

    programMetaData = ...
        writeTwitchProbeBlock610A(...
            fid,...
            waitTime,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

    waitTime=programMetaData.controlFunction.duration;
end


lengthRampOptions(1).value      = 0; %mm
lengthRampOptions(2).value      = auroraConfig.prePostPositioningDuration; %second

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);


waitTime = auroraConfig.stop.waitTime;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


%%
%
% normalization_04_isometricForce.dpf
%
%%

idx=idx+1;
idxStr = getTrialIndexString(idx);

typeOfTrial = 'isometric';
blockName   = 'normalization';
fname       = getTrialName(seriesName,idx,typeOfTrial,[],dateId,'.dpf');
fnameLabels = getTrialName(seriesName,idx,typeOfTrial,[],[dateId,'_labels'],'.csv');


fprintf(fidProtocol,'%s,%s,%s,%s,%s,%s\n',...
    idxStr,typeOfTrial,'0mm', blockName,fname,'See instruction 6 and 7');

fid                 = fopen(fullfile(     codeDir,fname      ),'w');
fullFilePathLabels  = fullfile(codeLabelDir,fnameLabels);

programMetaData = getEmptyProgramMetaDataStruct(fullFilePathLabels);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

%%
%Move the specimen to a length of 0
%%

waitTime                        = 0;
flag_printMetaDataToFile        = 1;

lengthRampOptions(1).value      = 0;
lengthRampOptions(2).value      = auroraConfig.prePostPositioningDuration;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

stimulationDurationInS = auroraConfig.stimulation.maxDuration;

waitTime=auroraConfig.passive.recoveryTime;

programMetaData = ...
    writeStimulusTetanusBlock610A(...
        fid,...
        waitTime, ...
        stimulationDurationInS,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


waitTime =   stimulationDurationInS ...
           + auroraConfig.restTimeBetweenActivations;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


%%
%
% normalization_05_forceVelocity.dpf
%
%%

fvSeries(2) = struct('velocity',[],'name','');
fvSeries(1).name = 'EDL';
fvSeries(1).velocity = [0.125,0.25,0.5,0.75,1.0,1.25,1.5]...
    .*(expConfig.normalization.forceVelocity.vmax.edl);
fvSeries(2).name = 'SOL';
fvSeries(2).velocity = [0.5,0.75,0.875,1.0,1.125,1.25,1.5]...
    .*(expConfig.normalization.forceVelocity.vmax.sol);

for idxFvSeries = 1:1:length(fvSeries)

    idx=idx+1;

    idxStr          = getTrialIndexString(idx);
    startingLength  = expConfig.normalization.forceVelocity.lengthsMM(1,1);
    typeOfTrial     = 'forceVelocity';
    blockName       = 'normalization';
    
    fname       = getTrialName(seriesName,idx,typeOfTrial,startingLength,...
                        [dateId,'_',fvSeries(idxFvSeries).name],'.dpf');
    fnameLabels = getTrialName(seriesName,idx,typeOfTrial,startingLength,...
                        [dateId,'_',fvSeries(idxFvSeries).name,'_labels'],'.csv');
    
    fprintf(fidProtocol,'%s,%s,%1.1fmm,%s,%s,%s\n',...
        idxStr,typeOfTrial,startingLength, blockName,fname,'See instruction 9');
    
    fid                 = fopen(fullfile(     codeDir,fname      ),'w');
    fullFilePathLabels  = fullfile(codeLabelDir,fnameLabels);
    
    programMetaData = getEmptyProgramMetaDataStruct(fullFilePathLabels);
    programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

    waitTime                        = 0; 
    flag_printMetaDataToFile        = 1;
    
    for idxVelocity = 1:1:length(fvSeries(idxFvSeries).velocity)
        
        lengthRampOptions(1).value      = ...
            expConfig.normalization.forceVelocity.lengthsMM(1,1);
        lengthRampOptions(2).value      = ...
            auroraConfig.prePostPositioningDuration;
        
        programMetaData ...
            = writeControlFunction610A(...
                    fid,...
                    waitTime,...
                    'Ramp',...
                    lengthRampOptions,...
                    auroraConfig,...
                    programMetaData,...
                    flag_printMetaDataToFile);
        
        waitTime   = auroraConfig.passive.recoveryTime;

        rampLength = expConfig.normalization.forceVelocity.lengthsMM(1,2) ...
                   - expConfig.normalization.forceVelocity.lengthsMM(1,1);
        velocity = fvSeries(idxFvSeries).velocity(idxVelocity);
        duration = rampLength/velocity;
    
        stimulationDurationInS  = ...
             auroraConfig.timeToReachMaxActivation ...
           + duration ...
           + auroraConfig.activationPaddingTime;
        
        programMetaData = ...
            writeStimulusTetanusBlock610A(...
                fid,...
                waitTime, ...
                stimulationDurationInS,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
        
        stimulationEndTime = programMetaData.controlFunction.endTime;    
        
        %Apply a descending force ramp
        lengthRampOptions(1).value      = ...
            expConfig.normalization.forceVelocity.lengthsMM(1,2);
        lengthRampOptions(2).value      = duration;

        waitTime = auroraConfig.timeToReachMaxActivation;
        
        programMetaData ...
            = writeControlFunction610A(...
                    fid,...
                    waitTime,...
                    'Ramp',...
                    lengthRampOptions,...
                    auroraConfig,...
                    programMetaData,...
                    flag_printMetaDataToFile);
               
        rampEndTime  = programMetaData.controlFunction.endTime;
        waitTime = (stimulationEndTime-rampEndTime) ...
                  + auroraConfig.activationPaddingTime;    
    end
    
    programMetaData = ...
        writeClosingBlock610A(...
            fid,...
            waitTime,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);    

end


%%
%
% impedance trials about 0.
%
%%


for idxImpedance = 1:1:length(stochasticWaveScalesToTest)
    for i=1:1:length(stochasticWaveSet)

      idx=idx+1;
      
      idxStr          = getTrialIndexString(idx);
      startingLength  = expConfig.normalization.forceVelocity.lengthsMM(1,1);
      typeOfTrial     = ['impedance_',...
                          replace(stochasticWaveSet(i).controlFunction,' ','_')];
      blockName       = 'normalization';
      
      fname       = getTrialName(seriesName,idx,typeOfTrial,startingLength,...
                                  dateId,'.dpf');
      fnameLabels = getTrialName(seriesName,idx,typeOfTrial,startingLength,...
                                  dateId,'.csv');
      
      fprintf(fidProtocol,'%s,%s,%1.1fmm,%s,%s,%s\n',...
          idxStr,typeOfTrial,startingLength, blockName,fname,...
          'Re-generate after setting lceOptMM. See instruction 10 and 11');
      
      fid                 = fopen(fullfile(     codeDir,fname      ),'w');
      fullFilePathLabels  = fullfile(codeLabelDir,fnameLabels);
      
      programMetaData = getEmptyProgramMetaDataStruct(fullFilePathLabels);
      programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);
      
      
      waitTime                    = 0;
      flag_printMetaDataToFile    = 1;
  
      lengthRampOptions(1).value    = 0;
      lengthRampOptions(2).value    = auroraConfig.prePostPositioningDuration;
  
      programMetaData ...
          = writeControlFunction610A(...
                  fid,...
                  waitTime,...
                  'Ramp',...
                  lengthRampOptions,...
                  auroraConfig,...
                  programMetaData,...
                  flag_printMetaDataToFile);    
  
      waveDurationInS = (stochasticWaveSet(i).config.points...
                        /stochasticWaveSet(i).config.frequencyHz);
   
  
      stimulationDurationInS = waveDurationInS ...
                              + auroraConfig.timeToReachMaxActivation ...
                              + auroraConfig.activationPaddingTime;
      
      waitTime=1;
      
      programMetaData = ...
          writeStimulusTetanusBlock610A(...
              fid,...
              waitTime, ...
              stimulationDurationInS,...
              auroraConfig,...
              programMetaData,...
              flag_printMetaDataToFile);
      
      
      waitTimeForBlock  = auroraConfig.timeToReachMaxActivation;  
  
      startTimeBlock    = programMetaData.nextStartTime;
      
      scaleMagnitude = stochasticWaveScalesToTest(idxImpedance);


        switch stochasticWaveSet(i).controlFunction
            case 'Ramp'            
                programMetaData = ...
                    writeLengthRampBlock610A(...
                        fid, ...
                        waitTimeForBlock,...
                        stochasticWaveSet(i).waitDuration,...
                        stochasticWaveSet(i).optionValues(:,1).*scaleMagnitude,...
                        stochasticWaveSet(i).optionValues(:,2),...
                        stochasticWaveSet(i).options,...
                        auroraConfig,...
                        programMetaData,...
                        stochasticWaveSet(i).type,...
                        flag_printMetaDataToFile);
    
            case 'Sine Wave'
                programMetaData = ...
                    writeLengthSineBlock610A(...
                        fid,...
                        waitTimeForBlock,...
                        stochasticWaveSet(i).waitDuration,...
                        stochasticWaveSet(i).optionValues(:,1),...
                        stochasticWaveSet(i).optionValues(:,2).*scaleMagnitude,...
                        stochasticWaveSet(i).optionValues(:,3),...
                        stochasticWaveSet(i).options,...
                        auroraConfig,...
                        programMetaData,...
                        stochasticWaveSet(i).type,...
                        flag_printMetaDataToFile);
            otherwise
                assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
        end

        endTimeBlock = programMetaData.controlFunction.endTime;
        assert(abs((endTimeBlock-startTimeBlock)...
                  -(waitTimeForBlock+waveDurationInS)) < 1e-6,...
               'Error: timing meta data is incorrect');    
    
        waitTime =   auroraConfig.activationPaddingTime ...
                   + auroraConfig.restTimeBetweenActivations;

        waitTime =  auroraConfig.stop.waitTime;
        
        programMetaData = ...
            writeClosingBlock610A(...
                fid,...
                waitTime,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
        
        fclose(fid);        

    end
    


end



%%
%Move the specimen to a the starting length
%%
% 
% 
% waitTime                        = 0; 
% flag_printMetaDataToFile        = 1;
% 
% lengthRampOptions(1).value      = ...
%     expConfig.normalization.forceVelocity.lengthsMM(1,1);
% lengthRampOptions(2).value      = ...
%     auroraConfig.prePostPositioningDuration;
% 
% programMetaData ...
%     = writeControlFunction610A(...
%             fid,...
%             waitTime,...
%             'Ramp',...
%             lengthRampOptions,...
%             auroraConfig,...
%             programMetaData,...
%             flag_printMetaDataToFile);
% 
% 
% waitTime                = auroraConfig.passive.recoveryTime;
% 
% stimulationDurationInS  = ...
%      auroraConfig.timeToReachMaxActivation ...
%    + expConfig.normalization.forceVelocity.forceRampDurationS(1,1) ...
%    + auroraConfig.activationPaddingTime;
% 
% programMetaData = ...
%     writeStimulusTetanusBlock610A(...
%         fid,...
%         waitTime, ...
%         stimulationDurationInS,...
%         auroraConfig,...
%         programMetaData,...
%         flag_printMetaDataToFile);
% 
% stimulationEndTime = programMetaData.controlFunction.endTime;    
% 
% %Apply a descending force ramp
% forceRampOptions = getCommandFunctionOptions610A(...
%                     'Ramp','Force Out',auroraConfig);
% 
% forceRampOptions(1).value = ...
%     expConfig.normalization.forceVelocity.forceRampForceMN(1,1); %Force to ramp to 1mN
% forceRampOptions(2).value = ...
%     expConfig.normalization.forceVelocity.forceRampDurationS(1,1);
% 
% waitTime = auroraConfig.timeToReachMaxActivation;
% 
% programMetaData ...
%     = writeControlFunction610A(...
%             fid,...
%             waitTime,...
%             'Ramp',...
%             forceRampOptions,...
%             auroraConfig,...
%             programMetaData,...
%             flag_printMetaDataToFile);
% 
% rampEndTime         = programMetaData.controlFunction.endTime;
% 
% 
% waitTime = (stimulationEndTime-rampEndTime) ...
%           + auroraConfig.activationPaddingTime;
% 
% %Move the motor to the lengthening start position
% 
% lengthRampOptions(1).value      = ...
%     expConfig.normalization.forceVelocity.lengthsMM(2,1);
% lengthRampOptions(2).value      = ...
%     auroraConfig.prePostPositioningDuration;
% 
% programMetaData ...
%     = writeControlFunction610A(...
%             fid,...
%             waitTime,...
%             'Ramp',...
%             lengthRampOptions,...
%             auroraConfig,...
%             programMetaData,...
%             flag_printMetaDataToFile);
% 
% %
% % Wait for the muscle to recover,
% %   then actively lengthen. Why am I not using a force-ramp? Because for this
% %   I need to know the current force and/or have the machine set to use
% %   the Ref length and Ref force units.
% %
% 
% waitTime  = auroraConfig.passive.recoveryTime;
% 
% lengthChangeMM = expConfig.normalization.forceVelocity.lengthsMM(2,2) ...
%                   -expConfig.normalization.forceVelocity.lengthsMM(2,1);
% 
% 
% 
% velocityMMPS = expConfig.normalization.forceVelocity.velocityRangeMMPS(2,1);
% 
% rampDuration = lengthChangeMM / velocityMMPS;
% 
% 
% lengthRampOptions(1).value      = ...
%     expConfig.normalization.forceVelocity.lengthsMM(2,2);
% lengthRampOptions(2).value      = ...
%     rampDuration;
% 
% 
% stimulationDurationInS  = ...
%      auroraConfig.timeToReachMaxActivation ...
%    + rampDuration ...
%    + auroraConfig.activationPaddingTime;
% 
% programMetaData = ...
%     writeStimulusTetanusBlock610A(...
%         fid,...
%         waitTime, ...
%         stimulationDurationInS,...
%         auroraConfig,...
%         programMetaData,...
%         flag_printMetaDataToFile);
% 
% stimulationEndTime = programMetaData.controlFunction.endTime;    
% 
% waitTime = 0;
% 
% programMetaData ...
%     = writeControlFunction610A(...
%             fid,...
%             waitTime,...
%             'Ramp',...
%             lengthRampOptions,...
%             auroraConfig,...
%             programMetaData,...
%             flag_printMetaDataToFile);
% 
% endTime = programMetaData.controlFunction.endTime;
% 
% waitTime = (stimulationEndTime-endTime)+auroraConfig.restTimeBetweenActivations;
% 
% 
% programMetaData = ...
%     writeClosingBlock610A(...
%         fid,...
%         waitTime,...
%         auroraConfig,...
%         programMetaData,...
%         flag_printMetaDataToFile);
% 


fclose(fidProtocol);
success=1;