function success = createRampTrial610A_01(...
                    startEndLength,...
                    rampStartLength,...
                    trialFileNameNoExt,...                                     
                    auroraConfig,...
                    expConfig,...
                    expFolders,...
                    flag_isASequence)


    flag_printMetaDataToFile=1;

    fid = fopen(fullfile(expFolders.rootFolderPath,...
                         expFolders.protocolFolderName,...
                         [trialFileNameNoExt,'.dpf']),'w');
   
    
    trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                      expFolders.blockLabelsFolderName,...
                                      [trialFileNameNoExt,'.csv']);
    
    programMetaData = getEmptyProgramMetaDataStruct610A_01(...
                        startEndLength,...
                        trialBlockLabelFilePath);

    programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);
    

    if(flag_isASequence==0)
      jsonMetaData = struct('data',[],'protocol',[],...
                            'segments',[],'experiment',[]);
        
      jsonMetaData.data.file = {expFolders.dataFolderName, ...
                                [trialFileNameNoExt,'.ddf']};
      jsonMetaData.data.sha256 = "";
      
      jsonMetaData.protocol.file = {expFolders.protocolFolderName, ...
                                [trialFileNameNoExt,'.dpf']};
      jsonMetaData.protocol.sha256 = "";
    else
      jsonMetaData = struct('segments',[],'experiment',[]); 
    end    

    segmentMetaDataArray= [];
    
    %
    % Go to the start/end length
    %

    lengthRampOptions = ...
      getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);
    
    waitTime                    = 1;
    flag_printMetaDataToFile    = 1;
    
    positioningDuration = abs(startEndLength)...
                          /expConfig.positioning.rampSpeedInMMPS;
    positioningDuration = max(positioningDuration,...
                              expConfig.positioning.minimumRampTime);
    
    lengthRampOptions(1).value = startEndLength; 
    lengthRampOptions(2).value = positioningDuration;
    
    startTime = programMetaData.nextStartTime+waitTime;
    endTime = startTime+positioningDuration;
    
    [programMetaData,fcnMetaData] ...
        = writeControlFunction610A_01(...
                fid,...
                waitTime,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
    
    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];
    
    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data');         

    %
    % Ramp to the initial ramp length
    %
    lengthRampOptions = ...
      getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

    positioningDuration = abs(rampStartLength-startEndLength)...
                          /expConfig.positioning.rampSpeedInMMPS;
    positioningDuration = max(positioningDuration,...
                              expConfig.positioning.minimumRampTime);


    lengthRampOptions(1).value = rampStartLength; 
    lengthRampOptions(2).value = positioningDuration;
    
    startTime = programMetaData.nextStartTime+expConfig.timing.waitTime;
    endTime = startTime+positioningDuration;

    

    [programMetaData,fcnMetaData] ...
        = writeControlFunction610A_01(...
                fid,...
                expConfig.timing.waitTime,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
  
    segmentMetaDataArray = [segmentMetaDataArray,fcnMetaData];

    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data');        

    %
    % Meta data
    %
    waitTime      = expConfig.positioning.recoveryWaitTime;
    rampDuration  = expConfig.ramp.duration;
    tetanusDuration=0;
    if(expConfig.ramp.isActive==1)

      tetanusDuration  =rampDuration ...
                       +expConfig.tetanus.timeToReachMaxActivation ...
                       +expConfig.tetanus.durationExtension;

      stimulusTetanusOptions = getCommandFunctionOptions610A(...
                                'Stimulus-Tetanus','Stimulator',auroraConfig);
      
      stimulusTetanusOptions(1).value=expConfig.tetanus.initialDelay;
      stimulusTetanusOptions(2).value=expConfig.tetanus.pulseFrequency;
      stimulusTetanusOptions(3).value=expConfig.tetanus.pulseWidth;
      stimulusTetanusOptions(4).value=tetanusDuration;

      startTime = programMetaData.nextStartTime+waitTime;
      endTime   = startTime ...
                  +expConfig.tetanus.initialDelay ...
                  +tetanusDuration;

         
      [programMetaData, fcnMetaData] = ...
        writeControlFunction610A_01(...
              fid,...
              waitTime,...
              'Stimulus-Tetanus',...
              stimulusTetanusOptions,...
              auroraConfig,...                
              programMetaData,...
              flag_printMetaDataToFile); 
      
      segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

      endTimeError = endTime - programMetaData.controlFunction.endTime;
      assert(abs(endTimeError)<1e-3,...
          'Error: end time differs from the meta data'); 

      waitTime = expConfig.tetanus.timeToReachMaxActivation;
    end


    %
    % Ramp to some length
    %
    lengthRampOptions = ...
      getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

    lengthRampOptions(1).value = expConfig.ramp.length; 
    lengthRampOptions(2).value = expConfig.ramp.duration;
    
    startTime = programMetaData.nextStartTime ...
              + waitTime;
    endTime = startTime+expConfig.ramp.duration;

    [programMetaData, fcnMetaData] ...
        = writeControlFunction610A_01(...
                fid,...
                waitTime,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
  
    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];
    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data');

    %
    % Ramp to 0
    %
    lengthRampOptions = ...
      getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

    positioningDuration = abs(startEndLength-expConfig.ramp.length)...
                          /expConfig.positioning.rampSpeedInMMPS;
    positioningDuration = max(positioningDuration,...
                              expConfig.positioning.minimumRampTime);

    waitTime = max(expConfig.tetanus.recoveryTime+tetanusDuration,...
                   expConfig.ramp.holdDuration);

    lengthRampOptions(1).value = startEndLength; 
    lengthRampOptions(2).value = positioningDuration;
    
    startTime = programMetaData.nextStartTime + waitTime;
    endTime = startTime+lengthRampOptions(2).value;

    [programMetaData,fcnMetaData] ...
        = writeControlFunction610A_01(...
                fid,...
                waitTime,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);

    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];
    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data');         

    %
    % Close the trial
    %
    disableOptions = getCommandFunctionOptions610A('Stop','',auroraConfig);
    
    stopWaitTime=expConfig.timing.stopWaitTime;
    if(abs(expConfig.ramp.length)>1e-6)
      stopWaitTime = max(stopWaitTime,expConfig.positioning.recoveryWaitTime);
    end

    [programMetaData, fcnMetaData] ...
        = writeControlFunction610A_01(...
                fid,...
                stopWaitTime,...
                'Stop',...
                disableOptions,...              
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
    
    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];
    
    success = 1;
    assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
        'Error: maximumNumberOfCommandsExceeded');      


    fclose(fid);
    fclose(programMetaData.labelFileHandle);    
    %
    % Write the json files
    %

    if(expConfig.ramp.isActive==1)
      experimentTitle = ...
        sprintf('Active Ramp: %1.1f-%1.1f mm',...
                startEndLength,...
                expConfig.ramp.length);
      experimentTags = {'active-ramp'};
    else
      experimentTitle = ...
        sprintf('Passive Ramp: %1.1f-%1.1f mm',...
                startEndLength,...
                expConfig.ramp.length);
      experimentTags = {'passive-ramp'};
    end      

    success = writeMetaDataStructure610A(...
                segmentMetaDataArray,...
                expConfig,...
                experimentTitle,...
                experimentTags,...
                trialFileNameNoExt,...
                expFolders,...                          
                flag_isASequence);
    
    success = writeTimeSeriesDataAndImages610A(...
                programMetaData,...
                auroraConfig,...
                trialFileNameNoExt,...
                expFolders);
    
