function success = createPassiveImpedanceTrial610A(...
                    nominalLength,...
                    trialFileNameNoExt,...
                    stochasticWaveSet,...                                        
                    auroraConfig,...
                    expConfig,...
                    expFolders,...
                    flag_isASequence)



fid = fopen(fullfile(expFolders.rootFolderPath,...
                     expFolders.protocolFolderName,...
                     [trialFileNameNoExt,'.dpf']),'w');

trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                  expFolders.blockLabelsFolderName,...
                                  [trialFileNameNoExt,'.csv']);

programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFilePath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

if(flag_isASequence==0)
  jsonMetaData = struct('data',[],'protocol',[],...
                        'segments',[],'experiment',[]);
  
  
  jsonMetaData.data.file = {expFolders.dataFolderName, ...
                            [trialFileNameNoExt,'.ddf']};
  jsonMetaData.data.sha256 = "";
  
  jsonMetaData.protocol.file = {expFolders.protocolFolderName, ...
                            [trialFileNameNoExt,'.dpf']};
  jsonMetaData.protocol.sha256 = "";
else
  jsonMetaData = struct('segments',[],'experiment',[]); 
end

%%
%Create the meta data structure
%%


flag_printMetaDataToFile    = 1;

numberOfSegments = 1 ...
                 + length(stochasticWaveSet) ...
                 + length(expConfig.impedance.sine.frequencyHz) ...
                 + 1;

mdfn = getMetaDataFieldNames610A(auroraConfig);


segmentMetaDataArray(numberOfSegments) = ...
    struct('type','',mdfn.time,[0,0],'meta_data',[]);



idxSeg=1;
% Initial ramp
segmentMetaDataArray(idxSeg).type = 'Ramp';
segmentMetaDataArray(idxSeg).(mdfn.time) = [0,0];
segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
segmentMetaDataArray(idxSeg).meta_data.channel=[];
segmentMetaDataArray(idxSeg).meta_data.(mdfn.length)=[];
segmentMetaDataArray(idxSeg).meta_data.(mdfn.time)=[];

% Sine wave
for idxSine=1:1:length(expConfig.impedance.sine.frequencyHz)
idxSeg = idxSeg+1;
  segmentMetaDataArray(idxSeg).(mdfn.time) = [0,0];
  segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
  segmentMetaDataArray(idxSeg).meta_data.channel='';
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.frequency)=[];
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.amplitude)=[];
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.cycles)=[];
end

%Stochastic perturbation
for idxWave=1:1:length(stochasticWaveSet)
  idxSeg=idxSeg+1;
  segmentMetaDataArray(idxSeg).(mdfn.time) = [0,0];
  segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.bandwidth) = [0,0];
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.amplitude) = 0;
end

%Final ramp
idxSeg=idxSeg+1;
% Initial ramp
segmentMetaDataArray(idxSeg).type = 'Ramp';
segmentMetaDataArray(idxSeg).(mdfn.time) = [0,0];
segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
segmentMetaDataArray(idxSeg).meta_data.channel=[];
segmentMetaDataArray(idxSeg).meta_data.(mdfn.length)=[];
segmentMetaDataArray(idxSeg).meta_data.(mdfn.time)=[];


idxSeg = 0;

%%
% Initial ramp
%%
lengthRampOptions = getCommandFunctionOptions610A(...
                      'Ramp','Length Out',auroraConfig);
lengthRampOptions(1).value = nominalLength;
lengthRampOptions(2).value = expConfig.impedance.waitTime;

startTime = programMetaData.nextStartTime ...
            + expConfig.impedance.waitTime;
endTime   = startTime + expConfig.impedance.waitTime;

idxSeg=idxSeg+1;
segmentMetaDataArray(idxSeg).type = 'Ramp';
segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime];
segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
segmentMetaDataArray(idxSeg).meta_data.channel=lengthRampOptions(1).port;
segmentMetaDataArray(idxSeg).meta_data.(mdfn.length)=lengthRampOptions(1).value;
segmentMetaDataArray(idxSeg).meta_data.(mdfn.time)=lengthRampOptions(2).value;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            expConfig.impedance.waitTime,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');      


%%
% Apply a series of sine waves to make high resolution measurements of 
% gain and phase
%%
for idxSine=1:1:length(expConfig.impedance.sine.frequencyHz)

  lengthSineOptions = getCommandFunctionOptions610A(...
                        'Sine Wave','Length Out',auroraConfig);
  
  frequencyHz = expConfig.impedance.sine.frequencyHz(idxSine);
  period = 1/frequencyHz;
  period = round(period*auroraConfig.analogToDigitalSampleRateHz) ...
           /auroraConfig.analogToDigitalSampleRateHz;
  frequencyHz = 1/period;

  lengthSineOptions(1).value = frequencyHz;
  lengthSineOptions(2).value = expConfig.impedance.sine.amplitude;
  lengthSineOptions(3).value = expConfig.impedance.sine.cycles;
  
  sineTime   = lengthSineOptions(3).value/lengthSineOptions(1).value;
  
  sineTimeRounded   = ...
    round(sineTime*auroraConfig.analogToDigitalSampleRateHz)...
    /auroraConfig.analogToDigitalSampleRateHz;
  
  assert(abs(sineTime-sineTimeRounded) < eps*10,...
         ['Error: choose another sine wave frequency or sampling frequency',...
           ' this combination will not yield the correct number of cycles']);
  
  startTime = programMetaData.nextStartTime ...
              + expConfig.impedance.waitTime;
  endTime   = startTime + sineTime;
  
  %
  % Write the meta data
  %
  idxSeg=idxSeg+1;
  
  segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime]; 
  
  segmentMetaDataArray(idxSeg).type = ['Sine Wave'];
  segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
  
  segmentMetaDataArray(idxSeg).meta_data.channel            ...
      = lengthSineOptions(1).port;
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.frequency) = ...
    lengthSineOptions(1).value;
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.amplitude) = ...
    lengthSineOptions(2).value;    
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.cycles) = ...
    lengthSineOptions(3).value;    
  
  programMetaData ...
          = writeControlFunction610A(...
                  fid,...
                  expConfig.impedance.waitTime,...
                  'Sine Wave',...
                  lengthSineOptions,...
                  auroraConfig,...                
                  programMetaData,...
                  flag_printMetaDataToFile);  
  
  endTimeError = endTime - programMetaData.controlFunction.endTime;
  assert(abs(endTimeError)<1e-3,...
      'Error: end time differs from the meta data');
end

%%
% Apply stochastic perturbations
%%

flag_printMetaDataToFile    = 1;

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
    
end



for i=1:1:length(stochasticWaveSet)

    assert(strcmp(stochasticWaveSet(i).config.lengthUnits,...
                  auroraConfig.defaultLengthUnit),...
           ['Error: the default length units and the',...
            ' stochastic wave length units should match']);

    assert(strcmp(stochasticWaveSet(i).config.frequencyUnits,...
                  auroraConfig.defaultFrequencyUnit),...
           ['Error: the default frequency units and the',...
            ' stochastic wave frequency units should match']);

    assert(strcmp(stochasticWaveSet(i).config.timeUnits,...
                  auroraConfig.defaultTimeUnit),...
           ['Error: the default time units and the',...
            ' stochastic wave time units should match']);

  

    %
    % Write the wave meta data
    %
    idxSeg=idxSeg+1;
    
    singleWaveDuration = (stochasticWaveSet(i).config.points...
                         /stochasticWaveSet(i).config.frequencyHz);

    waveWaitTime  = expConfig.impedance.waitTime;      


    startTime = programMetaData.nextStartTime + waveWaitTime;
    endTime   = startTime+singleWaveDuration;

    scaleAmp = 1;
    targetAmplitude = expConfig.impedance.amplitude;
    defaultAmplitude = max(stochasticWaveSet(i).config.magnitudeRange);

    scaleAmp = targetAmplitude/defaultAmplitude;


    segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime]; 

    segmentMetaDataArray(idxSeg).type = ...
        [stochasticWaveSet(i).controlFunction,'-Stochastic'];
    segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.bandwidth) = ...
      stochasticWaveSet(i).config.frequencyRange;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.amplitude) = ...
      max(stochasticWaveSet(i).config.magnitudeRange).*scaleAmp;    

    %
    % Write the wave
    %
    
    switch stochasticWaveSet(i).controlFunction
        case 'Step'

            stepLengths = stochasticWaveSet(i).optionValues(:,1).*scaleAmp ...
                         +nominalLength;

            programMetaData = ...
                writeLengthStepBlock610A(...
                    fid, ...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stepLengths,...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);      
        case 'Ramp'            

            rampLengths= stochasticWaveSet(i).optionValues(:,1).*scaleAmp ...
                         + nominalLength;

            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    rampLengths,...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2).*scaleAmp,...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end

    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-2,...
        'Error: end time differs from the meta data');

end

%%
% Final ramp
%%
lengthRampOptions = getCommandFunctionOptions610A(...
                      'Ramp','Length Out',auroraConfig);
lengthRampOptions(1).value = nominalLength;
lengthRampOptions(2).value = expConfig.impedance.waitTime;

startTime = programMetaData.nextStartTime ...
            + expConfig.impedance.waitTime;
endTime   = startTime + expConfig.impedance.waitTime;

idxSeg=idxSeg+1;
segmentMetaDataArray(idxSeg).type = 'Ramp';
segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime];
segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
segmentMetaDataArray(idxSeg).meta_data.channel=lengthRampOptions(1).port;
segmentMetaDataArray(idxSeg).meta_data.(mdfn.length)=lengthRampOptions(1).value;
segmentMetaDataArray(idxSeg).meta_data.(mdfn.time)=lengthRampOptions(2).value;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            expConfig.impedance.waitTime,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');   

%%
% Finish up
%%

jsonMetaData.segments = segmentMetaDataArray;
jsonMetaData.experiment.title = ...
  sprintf('Passive Impedance %1.1f %s',...
          nominalLength, ...
          auroraConfig.defaultLengthUnit);
jsonMetaData.experiment.tags = {'passive-impedance'};

waitTime            = expConfig.stopWaitTime;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


jsonMetaDataEncoded = jsonencode(jsonMetaData);

if(flag_isASequence==1)
  fidJson = fopen(fullfile(expFolders.rootFolderPath,...
                           expFolders.sequenceMetaData,...
                           [trialFileNameNoExt,'.json']),'w');
else
  fidJson = fopen(fullfile(expFolders.rootFolderPath,...
                             [trialFileNameNoExt,'.json']),'w');
end
fprintf(fidJson,jsonMetaDataEncoded);
fclose(fidJson);

fclose(fid);
fclose(programMetaData.labelFileHandle);
