function [timeVec,...
        signalVec,...
        stochasticFunctions,...
        numberOfStochasticWaveCommands] =...
        createSquareWavePattern610A_FcnWrapper(...
                         arg,...
                         indexArg,...
                         configVibration,...
                         duration,...
                         velocity,...
                         signOfFirstChange,...
                         functionOptions,...
                         auroraConfig,...
                         argScale)

i0=1;
i1=max(indexArg);
j0 = i1+1;
j1 = length(arg);

argDur = duration;
argDur(indexArg)= arg(i0:i1,1)./argScale(1,1);


argVel = velocity;
argVel(indexArg)= arg(j0:j1,1)./argScale(2,1);

  [timeVec,...
  signalVec,...
  stochasticFunctions,...
  numberOfStochasticWaveCommands] =...
  createSquareWavePattern610A(...
                   configVibration,...
                   argDur,...
                   argVel,...
                   signOfFirstChange,...
                   functionOptions,...
                   auroraConfig);
