function success = createLengthRampImpedanceTrial610A(...
                    isRampActive,...
                    lengthRamp,...
                    stochasticWaveSet,...                    
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...
                    auroraConfig)



fid = fopen(trialFileFullPath,'w');
fidLabel = fopen(trialBlockLabelFullPath,'w');

lineCount=0;
[startTime,lineCount] = writePreamble610A(fid,lineCount,auroraConfig);

%Perturb
for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'
            [endTime, lineCount] = ...
                writeLengthRampBlock610A(fid, startTime,...
                            stochasticWaveSet(i).waitDuration,...
                            stochasticWaveSet(i).optionValues(:,1),...
                            stochasticWaveSet(i).optionValues(:,2),...
                            stochasticWaveSet(i).options,...
                            lineCount,...
                            auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);
            startTime = endTime + auroraConfig.postCommandPauseTime;

        case 'Sine Wave'
            [endTime,lineCount] = ...
                writeLengthSineBlock610A(fid, startTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);            
            startTime = endTime + auroraConfig.postCommandPauseTime;
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

if(isRampActive==1)


    %Perturb
    for i=1:1:length(stochasticWaveSet)

        %Activate
        stimulationDurationInS=5;
        [endTime, lineCount] = ...
            writeStimulationBlock610A(fid, startTime, stimulationDurationInS,...
                                     lineCount, auroraConfig);
        
        endActivation = endTime;
        
        fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Pre-Activation',startTime,endTime);
        fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Activation',endTime,endActivation);
        
        startTime = startTime + 0.3;

        switch stochasticWaveSet(i).controlFunction
            case 'Ramp'
                [endTime, lineCount] = ...
                    writeLengthRampBlock610A(fid, startTime,...
                                stochasticWaveSet(i).waitDuration,...
                                stochasticWaveSet(i).optionValues(:,1),...
                                stochasticWaveSet(i).optionValues(:,2),...
                                stochasticWaveSet(i).options,...
                                lineCount,...
                                auroraConfig);
                fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                    stochasticWaveSet(i).type,startTime,endTime);
                startTime = endTime + auroraConfig.postCommandPauseTime;
    
            case 'Sine Wave'
                [endTime,lineCount] = ...
                    writeLengthSineBlock610A(fid, startTime,...
                        stochasticWaveSet(i).waitDuration,...
                        stochasticWaveSet(i).optionValues(:,1),...
                        stochasticWaveSet(i).optionValues(:,2),...
                        stochasticWaveSet(i).optionValues(:,3),...
                        stochasticWaveSet(i).options,...
                        lineCount,...
                        auroraConfig);
                fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                    stochasticWaveSet(i).type,startTime,endTime);            
                startTime = endTime + auroraConfig.postCommandPauseTime;
            otherwise
                assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
        end
    end    

end

if(isRampActive==1)

    %Activate
    stimulationDurationInS=lengthRamp.duration + 0.3 + 5;
    [endTime, lineCount] = ...
        writeStimulationBlock610A(fid, startTime, stimulationDurationInS,...
                                 lineCount, auroraConfig);
    
    endActivation = endTime;
    
    fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Pre-Activation',startTime,endTime);
    fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Activation',endTime,endActivation);
    
    startTime = startTime + 0.3;

end

[endTime, lineCount] = ...
        writeLengthRampBlock610A(fid, startTime,...
                    lengthRamp.wait,...
                    lengthRamp.lengthChange,...
                    lengthRamp.duration,...
                    lengthRamp.options,...
                    lineCount,...
                    auroraConfig);
endTime = endTime + lengthRamp.waitPostRamp;

    fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
        lengthRamp.type,startTime,endTime);
    
startTime = endTime + auroraConfig.postCommandPauseTime;


%Perturb
for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'
            [endTime, lineCount] = ...
                writeLengthRampBlock610A(fid, startTime,...
                            stochasticWaveSet(i).waitDuration,...
                            stochasticWaveSet(i).optionValues(:,1),...
                            stochasticWaveSet(i).optionValues(:,2),...
                            stochasticWaveSet(i).options,...
                            lineCount,...
                            auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);
            startTime = endTime + auroraConfig.postCommandPauseTime;

        case 'Sine Wave'
            [endTime,lineCount] = ...
                writeLengthSineBlock610A(fid, startTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);            
            startTime = endTime + auroraConfig.postCommandPauseTime;
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end


[endTime, lineCount] = ...
    writeClosingBlock610A(fid, startTime, lineCount, auroraConfig);

success = 1;
assert(lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


fclose(fid);
fclose(fidLabel);
