function success = createLengthRampImpedanceTrial610A(...
                    isRampActive,...
                    lengthRamp,...
                    stochasticWaveSet,...                    
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...
                    pertubationConfig,...
                    auroraConfig)



fid = fopen(trialFileFullPath,'w');
fidLabel = fopen(trialBlockLabelFullPath,'w');

lineCount=0;
[startTime,lineCount] = writePreamble610A(fid,lineCount,auroraConfig);

%Perturb
for i=1:1:length(stochasticWaveSet)
    waitTimeForBlock = 0;
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'
            [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthRampBlock610A(fid, startTime,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);
            startTime = endTime;

        case 'Sine Wave'
            [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthSineBlock610A(fid, startTime,...
                    waitTimeForBlock,...                    
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);            
            startTime = endTime;
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end



if(isRampActive==1)

    %
    %Activate and measure the impedance at the starting length
    %
    waveDurationInS = 0;

    for i=1:1:length(stochasticWaveSet)
        waveDurationInS = waveDurationInS + ...
            ( stochasticWaveSet(i).config.points...
             /stochasticWaveSet(i).config.frequencyHz);
    end

    waitTime = 0;

    stimulationDurationInS = waveDurationInS ...
                            + auroraConfig.activationTime ...
                            + auroraConfig.activationTimeAfterMovement;

    [stimulationEndTime, smallestNextWaitTime, lineCount] = ...
        writeStimulusTetanusBlock610A(fid, startTime, waitTime, stimulationDurationInS,...
                                 lineCount, auroraConfig);

    fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Activation',startTime,stimulationEndTime);

    startTime = startTime + auroraConfig.activationTime;

    for i=1:1:length(stochasticWaveSet)

        switch stochasticWaveSet(i).controlFunction
            case 'Ramp'
            [endTime, smallestNextWaitTime, lineCount] = ...
                    writeLengthRampBlock610A(fid, startTime,...
                        waitTimeForBlock,...
                        stochasticWaveSet(i).waitDuration,...
                        stochasticWaveSet(i).optionValues(:,1),...
                        stochasticWaveSet(i).optionValues(:,2),...
                        stochasticWaveSet(i).options,...
                        lineCount,...
                        auroraConfig);
                fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                    stochasticWaveSet(i).type,startTime,endTime);
                startTime = endTime;
    
            case 'Sine Wave'
            [endTime, smallestNextWaitTime, lineCount] = ...
                    writeLengthSineBlock610A(fid, startTime,...
                        waitTimeForBlock,...
                        stochasticWaveSet(i).waitDuration,...
                        stochasticWaveSet(i).optionValues(:,1),...
                        stochasticWaveSet(i).optionValues(:,2),...
                        stochasticWaveSet(i).optionValues(:,3),...
                        stochasticWaveSet(i).options,...
                        lineCount,...
                        auroraConfig);
                fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                    stochasticWaveSet(i).type,startTime,endTime);            
                startTime = endTime;
            otherwise
                assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
        end  

    end    

    assert(stimulationEndTime > startTime,...
           'Error: stimulation shut off before perturbations completed');



    %
    % Let the muscle recover
    % Then activate, perform the ramp, wait, and measure the impedance
    %

    waitTime = (stimulationEndTime+auroraConfig.restTimeBetweenActivations) ...
               - startTime;

    startTime=stimulationEndTime+auroraConfig.restTimeBetweenActivations;


    %Activate again for the ramp
    waveDurationInS = 0;

    for i=1:1:length(stochasticWaveSet)
        waveDurationInS = waveDurationInS + ...
            ( stochasticWaveSet(i).config.points...
             /stochasticWaveSet(i).config.frequencyHz);
    end

    probeTime = (1/pertubationConfig.probe.frequencyHz)...
                 *pertubationConfig.probe.cycles;

    stimulationDurationInS =  auroraConfig.activationTime ...
                            + probeTime ...
                            + lengthRamp.duration ...
                            + probeTime ...
                            + lengthRamp.waitPostRamp ...
                            + waveDurationInS ...
                            + auroraConfig.activationTimeAfterMovement;

    [stimulationEndTime, smallestNextWaitTime, lineCount] = ...
        writeStimulusTetanusBlock610A(fid, startTime, waitTime, stimulationDurationInS,...
                                 lineCount, auroraConfig);

    fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Activation',startTime,stimulationEndTime);


end

waitTime  = auroraConfig.activationTime;
startTime = startTime + waitTime;


%Gain probe sine wave
[sineWaveOptions,isValid,msg]= ...
            getCommandFunctionOptions610A('Sine Wave',...
                                          'Length Out',...
                                          auroraConfig);            
assert(isValid==1,msg);


sineWaveOptions(1).value = pertubationConfig.probe.frequencyHz;
sineWaveOptions(2).value = pertubationConfig.probe.magnitude;
sineWaveOptions(3).value = pertubationConfig.probe.cycles;


[smallestNextWaitTime, commandDuration] = ...
     writeControlFunction610A(fid, waitTime, ...
        'Sine Wave',sineWaveOptions,auroraConfig);


%Ramp
startTime = startTime + commandDuration;
waitTimeForBlock = 0;
[endTime, lineCount] = ...
        writeLengthRampBlock610A(fid, startTime,...
                    waitTimeForBlock,...            
                    lengthRamp.wait,...
                    lengthRamp.lengthChange,...
                    lengthRamp.duration,...
                    lengthRamp.options,...
                    lineCount,...
                    auroraConfig);
%Gain probe
startTime = startTime + commandDuration;
waitTime=0;

[smallestNextWaitTime, commandDuration] = ...
     writeControlFunction610A(fid, waitTime, ...
        'Sine Wave',sineWaveOptions,auroraConfig);


%Let the muscle recover
startTime = startTime + commandDuration + lengthRamp.waitPostRamp;

fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
        lengthRamp.type,startTime,endTime);
    

%Perturb
for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'
            [endTime, lineCount] = ...
                writeLengthRampBlock610A(fid, startTime,...
                    waitTimeForBlock,...                    
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);
            startTime = endTime;

        case 'Sine Wave'
            [endTime,lineCount] = ...
                writeLengthSineBlock610A(fid, startTime,...
                    waitTimeForBlock, ...                   
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);            
            startTime = endTime;
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

waitTime=auroraConfig.stop.waitTime;

[endTime, lineCount] = ...
    writeClosingBlock610A(fid, startTime, waitTime, lineCount, auroraConfig);

success = 1;
assert(lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


fclose(fid);
fclose(fidLabel);
