function trialId = createPlateauSearchTrial610A_01(...
                      startEndLength,...
                      trialFileNameNoExt,...
                      dateId,...
                      trialId,...
                      sequenceId,...
                      auroraConfig,...
                      expConfig,...   
                      expFolders,...
                      projectFolders,...
                      flag_isASequence)

success = 0;

auroraConfigLocal=[];
if(auroraConfig.default.isTwitchAvailable)
  auroraConfigLocal=auroraConfig.twitch;
else
  auroraConfigLocal=auroraConfig.default;
end

%fprintf('\ncreatePlateauSearchTrail610A');
%fprintf('\n Update writeControlFunction command to return the meta-data struct');
%fprintf('\n Append this struct into the array (perhaps write a function for this)');
%fprintf('\n Write a function to create the meta data struct');

%%
% Create the file name
%%
if(isempty(trialFileNameNoExt))
  sequenceIdStr = '';
  assert(~isempty(sequenceId),'Error: sequenceId cannot be empty');
  
  if(~isempty(sequenceId))
    sequenceIdStr = num2str(sequenceId);
    if(length(sequenceIdStr)<2)
      sequenceIdStr = ['0',sequenceIdStr];
    end
  
  
  end


  lengthRange = [expConfig.ramp.lengths(1),...
                 expConfig.ramp.lengths(end)];
  
  lengthRangeStr = {'',''};
  
  for i=1:1:length(lengthRange)
    lengthRounded  = round(100*lengthRange(i));
    lengthRangeStr{i} = sprintf('%i',lengthRounded);
    lengthRangeStr{i} = strrep(lengthRangeStr{i},'-','m');
    if(abs(lengthRange(i))<1)
      while(length(lengthRangeStr{i})<2)
        lengthRangeStr{i} = ['0',lengthRangeStr{i}];
      end
    end
  end
  
  type = ['plateau_search_',lengthRangeStr{1},'_',lengthRangeStr{2}];
  
  seriesName = sequenceIdStr;
  idxP = trialId;
  if(~isempty(sequenceIdStr))
    idxP = 0;
  end
  
  trialFileNameNoExt  = getTrialName(seriesName,idxP,type,[],...
                  auroraConfigLocal.defaultLengthUnit, dateId,'');
end

%%
% Set up the files and metadata structures
%%

fid = fopen(fullfile(expFolders.rootFolderPath,...
                     expFolders.protocolFolderName,...
                     [trialFileNameNoExt,'.dpf']),'w');

trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                  expFolders.blockLabelsFolderName,...
                                  [trialFileNameNoExt,'.csv']);

programMetaData = getEmptyProgramMetaDataStruct610A_01(...
                    startEndLength,...
                    trialBlockLabelFilePath);

programMetaData = writePreamble610A(fid,auroraConfigLocal,programMetaData);



%%
% Get the command options
%%
lengthSineOptions = getCommandFunctionOptions610A(...
                      'Sine Wave','Length Out',auroraConfigLocal);
lengthSineOptions(1).value = expConfig.relax.frequency;
lengthSineOptions(2).value = expConfig.relax.amplitude;
lengthSineOptions(3).value = expConfig.relax.cycles;

lengthRampOptions = ...
  getCommandFunctionOptions610A('Ramp','Length Out',auroraConfigLocal);

stimulusTwitchOptions = ...
  getCommandFunctionOptions610A('Stimulus-Twitch','Stimulator',...
                                 auroraConfigLocal);
  

%%
% Create the trial
%%

flag_printMetaDataToFile = 1;
segmentMetaDataArray=[];

%
% Ramp to startEndLength
%
lengthRampOptions = ...
  getCommandFunctionOptions610A('Ramp','Length Out',...
                                 auroraConfigLocal);

positioningDuration = abs(startEndLength)...
                      /expConfig.positioning.rampSpeedInMMPS;
positioningDuration = max(positioningDuration,...
                          expConfig.positioning.minimumRampTime);

lengthRampOptions(1).value = startEndLength; 
lengthRampOptions(2).value = positioningDuration;

startTime = programMetaData.nextStartTime;
endTime = startTime+lengthRampOptions(2).value;

[programMetaData,fcnMetaData]...
    = writeControlFunction610A_01(...
            fid,...
            0,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfigLocal,...
            programMetaData,...
            flag_printMetaDataToFile);

segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');    

previousLength = startEndLength;
for idxL = 1:1:length(expConfig.ramp.lengths)

  %%
  %Ramp
  %%
  if(idxL > 1)
    previousLength = expConfig.ramp.lengths(idxL-1);
  end

  lengthChange = expConfig.ramp.lengths(idxL)-previousLength;
  rampDuration  = abs(lengthChange) ...
                  /expConfig.positioning.rampSpeedInMMPS;
  rampDuration  =max(rampDuration, expConfig.ramp.duration);

  lengthRampOptions(1).value = expConfig.ramp.lengths(idxL); 
  lengthRampOptions(2).value = rampDuration;

  %Write the ramp
  [programMetaData, fcnMetaData] ...
      = writeControlFunction610A_01(...
              fid,...
              expConfig.ramp.waitTime,...
              'Ramp',...
              lengthRampOptions,...              
              auroraConfigLocal,...
              programMetaData,...
              flag_printMetaDataToFile);



  segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];


  
  %%
  %Twitch/Stimulation
  %%
  if(auroraConfigLocal.isTwitchAvailable==1)

    stimulusTwitchOptions(1).value = expConfig.twitch.initialDelay;
    stimulusTwitchOptions(2).value = expConfig.twitch.pulseWidth;
  
    [programMetaData, fcnMetaData] ...
        = writeControlFunction610A_01(...
                fid,...
                expConfig.positioning.recoveryWaitTime,...
                'Stimulus-Twitch',...
                stimulusTwitchOptions,...              
                auroraConfigLocal,...
                programMetaData,...
                flag_printMetaDataToFile);
  
    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

  else
      stimulusTetanusOptions = getCommandFunctionOptions610A(...
                                'Stimulus-Tetanus','Stimulator',auroraConfig);
      
      stimulusTetanusOptions(1).value=expConfig.tetanus.initialDelay;
      stimulusTetanusOptions(2).value=expConfig.tetanus.pulseFrequency;
      stimulusTetanusOptions(3).value=expConfig.tetanus.pulseWidth;
      stimulusTetanusOptions(4).value=expConfig.tetanus.timeToReachMaxActivation;

      [programMetaData, fcnMetaData] ...
                = writeControlFunction610A_01(...
                          fid,...
                          expConfig.positioning.recoveryWaitTime,...
                          'Stimulus-Tetanus',...
                          stimulusTetanusOptions,...
                          auroraConfigLocal,...                
                          programMetaData,...
                          flag_printMetaDataToFile); 

    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];
  end
end

%%
% Bring the muscle back to its reference length
%%

  lengthChange = expConfig.ramp.lengths(end);
  rampDuration  = abs(lengthChange-startEndLength) ...
                  /expConfig.positioning.rampSpeedInMMPS;
  rampDuration  =max(rampDuration, expConfig.ramp.duration);

lengthRampOptions(1).value = startEndLength; 
lengthRampOptions(2).value = rampDuration;


[programMetaData, fcnMetaData] ...
    = writeControlFunction610A_01(...
            fid,...
            expConfig.ramp.waitTime,...
            'Ramp',...
            lengthRampOptions,...              
            auroraConfigLocal,...
            programMetaData,...
            flag_printMetaDataToFile);


segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

%%
% End the program
%%
disableOptions = getCommandFunctionOptions610A('Stop','',auroraConfigLocal);

stopWaitTime=expConfig.timing.stopWaitTime;
stopWaitTime = max(stopWaitTime,expConfig.positioning.recoveryWaitTime);

[programMetaData, fcnMetaData] ...
    = writeControlFunction610A_01(...
            fid,...
            stopWaitTime,...
            'Stop',...
            disableOptions,...              
            auroraConfigLocal,...
            programMetaData,...
            flag_printMetaDataToFile);

segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

fclose(fid);
fclose(programMetaData.labelFileHandle);

assert(programMetaData.lineCount < auroraConfigLocal.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');

experimentTitle = ...
  sprintf('Plateau Search %1.1f to %1.1f %s',...
          expConfig.ramp.lengths(1), ...
          expConfig.ramp.lengths(end),...
          auroraConfigLocal.defaultLengthUnit);

experimentTags = {'twitch-plateau-search'};

success = writeMetaDataStructure610A(...
                          segmentMetaDataArray,...
                          expConfig,...
                          experimentTitle,...
                          experimentTags,...
                          trialFileNameNoExt,...
                          expFolders,...                          
                          flag_isASequence);



success = writeTimeSeriesDataAndImages610A(...
            programMetaData,...
            auroraConfigLocal,...
            trialFileNameNoExt,...
            expFolders);

trialId = trialId+1;




