function success = createActiveLengthRampImpedanceTrial610A(...
                    lengthRamp,...
                    stochasticWaveSet,...                    
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...
                    perturbationConfig,...
                    auroraConfig)

assert(     size(lengthRamp.normLengths,1)==1 ...
        &&  size(lengthRamp.normLengths,2)==2,...
        "Error: lengthRamp.normLengths should be 1 x 2");


assert(     size(lengthRamp.lengths,1)==1 ...
        &&  size(lengthRamp.lengths,2)==2,...
        "Error: lengthRamp.normLengths should be 1 x 2");



fid = fopen(trialFileFullPath,'w');


programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFullPath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

%%
%Move the specimen from a length of 0 to its starting length
%%

waitTime                    = 0;
flag_printMetaDataToFile    = 1;

lengthChangeOptions = lengthRamp.options;
lengthChangeOptions(1).value = lengthRamp.lengths(1,1);
lengthChangeOptions(2).value = auroraConfig.prePostPositioningDuration;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthChangeOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

%%
%Perturb Passive Muscle
%%

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
end

startTimeBlock              = programMetaData.nextStartTime;
waitTimeForBlock            = auroraConfig.passive.recoveryTime;
flag_printMetaDataToFile    = 1;


for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs(endTimeBlock-startTimeBlock-waitTimeForBlock-waveDurationInS) < 1e-6,...
       'Error: timing meta data is incorrect');



%%
%Activate and measure the impedance at the starting length
%%


stimulationDurationInS = waveDurationInS ...
                        + auroraConfig.timeToReachMaxActivation ...
                        + auroraConfig.activationPaddingTime;

waitTime=0;

programMetaData = ...
    writeStimulusTetanusBlock610A(...
        fid,...
        waitTime, ...
        stimulationDurationInS,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


stimulationEndTime =  programMetaData.controlFunction.endTime;

waitTimeForBlock=auroraConfig.timeToReachMaxActivation;


%%
%Active Perturbation
%%

startTimeBlock = programMetaData.nextStartTime;

for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs((endTimeBlock-startTimeBlock)...
          -(waitTimeForBlock+waveDurationInS)) < 1e-6,...
       'Error: timing meta data is incorrect');

%
% Let the muscle recover
% Then activate, perform the ramp, wait, and measure the impedance
%
assert( (stimulationEndTime-endTimeBlock) > 0,...
        'Error: stimulation ends before perturbation block completes');

waitTime =   (stimulationEndTime-endTimeBlock) ...
           + auroraConfig.restTimeBetweenActivations;


%%
% A short series of small sinusoids to probe the impedance of the
% muscle before the ramp, immediately after the ramp, and then 
% after a break (so that that the end of the probe aligns with the
% maximum allowable activation).
%%

probe(1).wait     = auroraConfig.timeToReachMaxActivation;
probe(1).duration = perturbationConfig.probe.duration;

probe(2).wait     = 0;
probe(2).duration = perturbationConfig.probe.duration;

probe(3).wait     = 1;
probe(3).duration = perturbationConfig.probe.duration;


probe(3).wait     = auroraConfig.stimulation.maxDuration ...
                   -( probe(1).wait + probe(1).duration ...
                    + lengthRamp.wait +  lengthRamp.duration ...
                    + probe(2).wait + probe(2).duration ...
                    + probe(3).duration ...
                    + 2*auroraConfig.activationPaddingTime);

assert(probe(3).wait > 0, ['Error: insufficient time to perform ',...
    'activation-probe-ramp-probe-wait-probe sequence']);


stimulationDurationInS =  ( probe(1).wait   + probe(1).duration ...
                          + lengthRamp.wait + lengthRamp.duration ...
                          + probe(2).wait   + probe(2).duration ...
                          + probe(3).wait   + probe(3).duration ...
                          + auroraConfig.activationPaddingTime);


%%
%Activate
%%

programMetaData = ...
    writeStimulusTetanusBlock610A(...
        fid,...
        waitTime, ...
        stimulationDurationInS,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

stimulationEndTime = programMetaData.controlFunction.endTime;    

%%
% Probe sine wave 1
%%
[sineWaveOptions,isValid,msg]= ...
            getCommandFunctionOptions610A('Sine Wave',...
                                          'Length Out',...
                                          auroraConfig);            
assert(isValid==1,msg);


sineWaveOptions(1).value = perturbationConfig.probe.frequencyHz;
sineWaveOptions(2).value = perturbationConfig.probe.magnitude;
sineWaveOptions(3).value = perturbationConfig.probe.cycles;


waitTime  = probe(1).wait;

programMetaData  = ...
    writeControlFunction610A(   ...
        fid,...
        waitTime,...
        'Sine Wave',...
        sineWaveOptions,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


%%
%Length ramp
%%

waitTimeForBlock = 0;

programMetaData = ...
    writeLengthRampBlock610A(...
        fid, ...
        waitTimeForBlock,...
        lengthRamp.wait,...
        lengthRamp.lengths(1,2),...
        lengthRamp.duration(1,1),...
        lengthRamp.options,...
        auroraConfig,...
        programMetaData,...
        lengthRamp.type,...
        flag_printMetaDataToFile);

%%
% Probe sine wave 2
%%

waitTime  = max(probe(2).wait,programMetaData.smallestNextWaitTime);

programMetaData  = ...
    writeControlFunction610A(   ...
        fid,...
        waitTime,...
        'Sine Wave',...
        sineWaveOptions,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

%%
% Probe sine wave 3
%%
waitTime  = probe(3).wait;

programMetaData  = ...
    writeControlFunction610A(   ...
        fid,...
        waitTime,...
        'Sine Wave',...
        sineWaveOptions,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

probeEndTime = programMetaData.controlFunction.endTime;


assert(abs(probeEndTime+auroraConfig.activationPaddingTime...
           -stimulationEndTime)<(auroraConfig.lengthStepResponseTime*3),...
       ['Error: The activate-probe-ramp-probe-wait-probe sequence',...
        ' did not take the correct amount of time']);


%%
%Activate and measure the impedance at the ending length
%%

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
end

%Let the muscle recover
waitTime  = auroraConfig.restTimeBetweenActivations;

stimulationDurationInS = waveDurationInS ...
                        + auroraConfig.timeToReachMaxActivation ...
                        + auroraConfig.activationPaddingTime;



programMetaData = ...
    writeStimulusTetanusBlock610A(...
        fid,...
        waitTime, ...
        stimulationDurationInS,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


stimulationStartTime = programMetaData.controlFunction.startTime;
stimulationEndTime = programMetaData.controlFunction.endTime;

startTimeBlock      = programMetaData.nextStartTime;
waitTimeForBlock    = auroraConfig.timeToReachMaxActivation;

for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end 

endTimeBlock = programMetaData.controlFunction.endTime;

assert(abs((stimulationEndTime-stimulationStartTime)...
          -(waveDurationInS...
           +auroraConfig.activationPaddingTime ...
           +auroraConfig.timeToReachMaxActivation)) < 1e-3,...
        ['Error: duration of activationTime and the perturbation blocks do ',...
        ' not add up']);

assert(stimulationEndTime-endTimeBlock > 0, ...
       'Error: stimulation has stopped before the perturbations have finished');

waitTime= (stimulationEndTime-endTimeBlock ...
            + auroraConfig.restTimeBetweenActivations);


%%
% Move back to the starting position
%%

waitTime                        = auroraConfig.passive.recoveryTime;
flag_printMetaDataToFile        = 1;

lengthChangeOptions             = lengthRamp.options;
lengthChangeOptions(1).value    = lengthRamp.endLength;
lengthChangeOptions(2).value    = auroraConfig.prePostPositioningDuration;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthChangeOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);



%%
% Closing block
%%

waitTime = auroraConfig.stop.waitTime;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


fclose(fid);
fclose(programMetaData.labelFileHandle);
