function success = createIsometricImpedanceTrial610A(...
                    stochasticWaveSet,...
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...    
                    perturbationConfig,...
                    auroraConfig)



fid = fopen(trialFileFullPath,'w');


programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFullPath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

%%
%Passive Perturbation
%%

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
end


startTimeBlock              = programMetaData.nextStartTime;
waitTimeForBlock            = 0;
flag_printMetaDataToFile    = 1;

for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs(endTimeBlock-startTimeBlock-waveDurationInS) < 1e-6,...
       'Error: timing meta data is incorrect');


%%
%Activate
%%


stimulationDurationInS = waveDurationInS ...
                        + auroraConfig.timeToReachMaxActivation ...
                        + auroraConfig.activationPaddingTime;

waitTime=1;

programMetaData = ...
    writeStimulusTetanusBlock610A(...
        fid,...
        waitTime, ...
        stimulationDurationInS,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


waitTimeForBlock=auroraConfig.timeToReachMaxActivation;

%%
%Active Perturbation
%%

startTimeBlock              = programMetaData.nextStartTime;

for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs((endTimeBlock-startTimeBlock)...
          -(waitTimeForBlock+waveDurationInS)) < 1e-6,...
       'Error: timing meta data is incorrect');


waitTime =   auroraConfig.activationPaddingTime ...
           + auroraConfig.restTimeBetweenActivations ...
           + auroraConfig.stop.waitTime;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


fclose(fid);
fclose(programMetaData.labelFileHandle);
