function success = createActiveLengthRampSeriesTrial610A(...
                        lengthRampSeries,...
                        trialFileFullPath,...
                        trialBlockLabelFullPath,...
                        auroraConfig)


%
% Make the program file
%
fid = fopen(trialFileFullPath,'w');
programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFullPath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);


%
% Stimulate the muscle
%
waitTime = 0;
stretchShorteningDuration = 0;
for i=1:1:length(lengthRampSeries)
    stretchShorteningDuration = ...
        stretchShorteningDuration ...
        + lengthRampSeries(i).duration;
end

stimulationDurationInS = ...
    auroraConfig.timeToReachMaxActivation ...
    + stretchShorteningDuration ...
    + auroraConfig.activationPaddingTime;



flag_printMetaDataToFile = 1;
programMetaData = ...
    writeStimulusTetanusBlock610A(...
        fid,...
        waitTime, ...
        stimulationDurationInS,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

waitTimeForBlock = auroraConfig.timeToReachMaxActivation;

stimulationEndTime = programMetaData.controlFunction.endTime;

%
% Stretch-shorten cycle
%
for i=1:1:length(lengthRampSeries)
    programMetaData = ...
        writeLengthRampBlock610A(...
            fid, ...
            waitTimeForBlock,...
            lengthRampSeries(i).wait,...
            lengthRampSeries(i).lengthChange,...
            lengthRampSeries(i).duration,...
            lengthRampSeries(i).options,...
            auroraConfig,...
            programMetaData,...
            lengthRampSeries(i).type,...
            flag_printMetaDataToFile);   
    waitTimeForBlock=0;
end

endTimeBlock = programMetaData.controlFunction.endTime;

waitTime= max( auroraConfig.stop.waitTime, ...
               ((stimulationEndTime-endTimeBlock) ...
              + auroraConfig.restTimeBetweenActivations) );

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


fclose(fid);
fclose(programMetaData.labelFileHandle);