function success = createIsometricImpedanceTrial610A(...
                    isometric,...
                    stochasticWaveSet,...
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...    
                    perturbationConfig,...
                    auroraConfig)


assert(     size(isometric.normLengths,1)==1,...
        'Error: isometric.normLengths should be 1 x 1');


assert(     size(isometric.lengths,1)==1,...
        'Error: isometric.normLengths should be 1 x 1');

fid = fopen(trialFileFullPath,'w');


programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFullPath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

%%
%Move the specimen from a length of 0 to its starting length
%%

waitTime                    = 0;
flag_printMetaDataToFile    = 1;

lengthChangeOptions             = isometric.options;
lengthChangeOptions(1).value    = isometric.lengths(1,1);
lengthChangeOptions(2).value    = auroraConfig.prePostPositioningDuration;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthChangeOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);


%%
%Passive Perturbation
%%

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
end


startTimeBlock              = programMetaData.nextStartTime;
waitTimeForBlock            = auroraConfig.passive.recoveryTime;
flag_printMetaDataToFile    = 1;

for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs(endTimeBlock-startTimeBlock-waitTimeForBlock-waveDurationInS) < 1e-6,...
       'Error: timing meta data is incorrect');


%%
%Activate
%%


stimulationDurationInS = waveDurationInS ...
                        + auroraConfig.timeToReachMaxActivation ...
                        + auroraConfig.activationPaddingTime;

waitTime=1;

programMetaData = ...
    writeStimulusTetanusBlock610A(...
        fid,...
        waitTime, ...
        stimulationDurationInS,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


waitTimeForBlock=auroraConfig.timeToReachMaxActivation;

%%
%Active Perturbation
%%

startTimeBlock              = programMetaData.nextStartTime;

for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs((endTimeBlock-startTimeBlock)...
          -(waitTimeForBlock+waveDurationInS)) < 1e-6,...
       'Error: timing meta data is incorrect');


%%
%Move the specimen from its ending length to a length of 0
%%

waitTime =   auroraConfig.activationPaddingTime ...
           + auroraConfig.restTimeBetweenActivations;

flag_printMetaDataToFile    = 1;

lengthChangeOptions             = isometric.options;
lengthChangeOptions(1).value    = isometric.endLength;
lengthChangeOptions(2).value    = auroraConfig.prePostPositioningDuration;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthChangeOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);


%%
%Write the ending block.
%%

waitTime =  auroraConfig.stop.waitTime;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


fclose(fid);
fclose(programMetaData.labelFileHandle);
