function success = createIsometricImpedanceTrial610A(...
                    stochasticWaveSet,...
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...                    
                    auroraConfig)



fid = fopen(trialFileFullPath,'w');
fidLabel = fopen(trialBlockLabelFullPath,'w');

lineCount=0;
[startTime,lineCount] = writePreamble610A(fid,lineCount,auroraConfig);

%Perturb
for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthRampBlock610A(fid, startTime,...
                            stochasticWaveSet(i).waitDuration,...
                            stochasticWaveSet(i).optionValues(:,1),...
                            stochasticWaveSet(i).optionValues(:,2),...
                            stochasticWaveSet(i).options,...
                            lineCount,...
                            auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);
            startTime = endTime;

        case 'Sine Wave'
            [endTime,smallestNextWaitTime,lineCount] = ...
                writeLengthSineBlock610A(fid, startTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);            
            startTime = endTime;
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end



%Perturb
stimulationEndTime=nan;
for i=1:1:length(stochasticWaveSet)

    if(i > 1) 
            assert(startTime > stimulationEndTime,...
                ['Error: Attempting to start two',...
                      ' overlapping stimulation signals']); 
    end

    %Activate
    waveDurationInS = ...
        stochasticWaveSet(i).config.points...
        /stochasticWaveSet(i).config.frequencyHz;
    stimulationDurationInS = waveDurationInS + auroraConfig.activationTime + 1;
    [stimulationEndTime, smallestNextWaitTime, lineCount] = ...
        writeStimulationBlock610A(fid, startTime, stimulationDurationInS,...
                                 lineCount, auroraConfig);
   
    fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Activation',startTime,stimulationEndTime);
    
    startTime = startTime ...
                + max(auroraConfig.activationTime, smallestNextWaitTime);
    
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'
            [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthRampBlock610A(fid, startTime,...
                            stochasticWaveSet(i).waitDuration,...
                            stochasticWaveSet(i).optionValues(:,1),...
                            stochasticWaveSet(i).optionValues(:,2),...
                            stochasticWaveSet(i).options,...
                            lineCount,...
                            auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);
            startTime = endTime;

        case 'Sine Wave'
            [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthSineBlock610A(fid, startTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);            
            startTime = endTime;
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end


    startTime = stimulationEndTime+10;
end

startTime=startTime-5;
[endTime, lineCount] = ...
    writeClosingBlock610A(fid, startTime, lineCount, auroraConfig);

success = 1;
assert(lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


fclose(fid);
fclose(fidLabel);
