function success = createSinglePassiveLengthRampImpedanceTrial610A(...                    
                    lengthRamp,...
                    stochasticWaveSet,...
                    trialFileNameNoExt,...
                    folderConfig,...
                    auroraConfig)


fid = fopen(fullfile(folderConfig.rootFolderPath,...
                     folderConfig.protocolFolderName,...
                     [trialFileNameNoExt,'.dpf']),'w');

trialBlockLabelFilePath = fullfile(folderConfig.rootFolderPath,...
                                  folderConfig.blockLabelsFolderName,...
                                  [trialFileNameNoExt,'.csv']);

programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFilePath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

jsonMetaData = struct('data',[],'protocol',[],...
                      'segments',[],'experiment',[]);


jsonMetaData.data.file = {folderConfig.dataFolderName, ...
                          [trialFileNameNoExt,'.ddf']};
jsonMetaData.data.sha256 = "";

jsonMetaData.protocol.file = {folderConfig.protocolFolderName, ...
                          [trialFileNameNoExt,'.dpf']};
jsonMetaData.protocol.sha256 = "";


%%
%Move the specimen from a length of 0 to its starting length
%%


waitTime                    = 1;
flag_printMetaDataToFile    = 1;

numberOfSegments = length(lengthRamp.lengths) ...
                  +length(stochasticWaveSet);

segmentMetaDataArray(numberOfSegments) = ...
    struct('type','','duration',[0,0],'meta_data',[]);


timeFieldName = ['time_',auroraConfig.defaultTimeUnit];
bandwidthFieldName = ['bandwidth_',auroraConfig.defaultFrequencyUnit];
amplitudeFieldName = ['amplitude_',auroraConfig.defaultLengthUnit];        
isActive = 0;

for idxSeg=1:1:length(lengthRamp.lengths)
    segmentMetaDataArray(idxSeg).(timeFieldName) = [0,0];
    segmentMetaDataArray(idxSeg).meta_data.is_active = isActive;
    segmentMetaDataArray(idxSeg).meta_data.channel='';
    segmentMetaDataArray(idxSeg).meta_data.value=[];
    segmentMetaDataArray(idxSeg).meta_data.unit=[];
end

for idxSeg=(length(lengthRamp.lengths)+1):1:numberOfSegments
    segmentMetaDataArray(idxSeg).(timeFieldName) = [0,0];
    segmentMetaDataArray(idxSeg).meta_data.is_active = isActive;
    segmentMetaDataArray(idxSeg).meta_data.(bandwidthFieldName) = [0,0];
    segmentMetaDataArray(idxSeg).meta_data.(amplitudeFieldName) = 0;
    segmentMetaDataArray(idxSeg).meta_data.file ={};
end

idxSeg = 0;
for i=1:1:length(lengthRamp.lengths)

  lengthChangeOptions             = lengthRamp.options;
  lengthChangeOptions(1).value    = lengthRamp.lengths(i);
  lengthChangeOptions(2).value    = auroraConfig.prePostPositioningDuration;

  programMetaData ...
      = writeControlFunction610A(...
              fid,...
              waitTime,...
              'Ramp',...
              lengthChangeOptions,...
              auroraConfig,...
              programMetaData,...
              flag_printMetaDataToFile);

  idxSeg=idxSeg+1;

  lengthFieldName = ['length_','x'];

  segmentMetaDataArray(idxSeg).type = ...
      'Ramp';                
  segmentMetaDataArray(idxSeg).(timeFieldName) = ...
      [programMetaData.controlFunction.startTime,...
       programMetaData.controlFunction.endTime];
  segmentMetaDataArray(idxSeg).meta_data.is_active = isActive;
  segmentMetaDataArray(idxSeg).meta_data.channel = lengthChangeOptions(1).port;
  segmentMetaDataArray(idxSeg).meta_data.value = lengthRamp.lengths(i);
  segmentMetaDataArray(idxSeg).meta_data.unit = lengthChangeOptions(1).unit;
  
end


assert(0,'You are here!');

%%
%Perturb Passive Muscle
%%


startTimeBlock              = programMetaData.nextStartTime;
waitTimeForBlock            = auroraConfig.passive.recoveryTime;
flag_printMetaDataToFile    = 1;

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
    
end



for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Step'

            stepLengths = stochasticWaveSet(i).optionValues(:,1) ...
                         +lengthRamp.lengths(end);

            programMetaData = ...
                writeLengthStepBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stepLengths,...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);      
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs(endTimeBlock-startTimeBlock...
          -(waitTimeForBlock*length(stochasticWaveSet)+waveDurationInS )) < 1e-2,...
       'Error: timing meta data is incorrect');

waitTime            = auroraConfig.passive.recoveryTime;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


fclose(fid);
fclose(programMetaData.labelFileHandle);
