function success = createStretchShortenTrial610A(...
                    nominalLength,...
                    trialFileNameNoExt,...                                     
                    auroraConfig,...
                    expConfig,...
                    expFolders,...
                    flag_isASequence)


%     assert(abs(nominalLength)<1e-6,...
%       ['Error: nominalLength must be 0 to be compatible with the file ',... 
%        'sequencer, as the length will be returned to 0 between trials ',...
%        'automatically.']);
    flag_printMetaDataToFile=1;

    fid = fopen(fullfile(expFolders.rootFolderPath,...
                         expFolders.protocolFolderName,...
                         [trialFileNameNoExt,'.dpf']),'w');
   
    
    trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                      expFolders.blockLabelsFolderName,...
                                      [trialFileNameNoExt,'.csv']);
    
    programMetaData = getEmptyProgramMetaDataStruct610A(trialBlockLabelFilePath);
    programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);
    
    mdfn = getMetaDataFieldNames610A(auroraConfig);

    if(flag_isASequence==0)
      jsonMetaData = struct('data',[],'protocol',[],...
                            'segments',[],'experiment',[]);
        
      jsonMetaData.data.file = {expFolders.dataFolderName, ...
                                [trialFileNameNoExt,'.ddf']};
      jsonMetaData.data.sha256 = "";
      
      jsonMetaData.protocol.file = {expFolders.protocolFolderName, ...
                                [trialFileNameNoExt,'.dpf']};
      jsonMetaData.protocol.sha256 = "";
    else
      jsonMetaData = struct('segments',[],'experiment',[]); 
    end    

    numberOfSegments= expConfig.ramp.isActive+3; 
    
    segmentMetaDataArray(numberOfSegments) = ...
        struct('type','',mdfn.time,[0,0],'meta_data',[]);

    idxSeg=1;  
    %
    % Ramp from 0 to nominalLength
    %
    lengthRampOptions = ...
      getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

    positioningDuration = abs(nominalLength)...
                          /expConfig.positioning.rampSpeedInMMPS;
    positioningDuration = max(positioningDuration,...
                              expConfig.positioning.minimumRampTime);

    lengthRampOptions(1).value = nominalLength; 
    lengthRampOptions(2).value = positioningDuration;
    
    startTime = programMetaData.nextStartTime;
    endTime = startTime+lengthRampOptions(2).value;

    segmentMetaDataArray(idxSeg).type = 'Ramp';
    segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime];
    segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
    segmentMetaDataArray(idxSeg).meta_data.channel=lengthRampOptions(1).port;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.length)=lengthRampOptions(1).value;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.time)=lengthRampOptions(2).value;
    idxSeg=idxSeg+1;

    programMetaData ...
        = writeControlFunction610A(...
                fid,...
                0,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
  
    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data');        

    %
    % Meta data
    %
    waitTime = 1;
    if(abs(nominalLength) > 1e-6)
      waitTime = expConfig.positioning.recoveryWaitTime;
    end
    rampDuration = expConfig.ramp.duration;

    if(expConfig.ramp.isActive==1)

      activeRampTime = rampDuration*2;

      tetanusDuration  = activeRampTime ...
                       +expConfig.tetanus.timeToReachMaxActivation ...
                       +expConfig.tetanus.durationExtension;

      stimulusTetanusOptions = getCommandFunctionOptions610A(...
                                'Stimulus-Tetanus','Stimulator',auroraConfig);
      
      stimulusTetanusOptions(1).value=expConfig.tetanus.initialDelay;
      stimulusTetanusOptions(2).value=expConfig.tetanus.pulseFrequency;
      stimulusTetanusOptions(3).value=expConfig.tetanus.pulseWidth;
      stimulusTetanusOptions(4).value=tetanusDuration;

      startTime = programMetaData.nextStartTime+waitTime;
      endTime   = startTime ...
                  +expConfig.tetanus.initialDelay ...
                  +tetanusDuration;
      

      segmentMetaDataArray(idxSeg).type = 'Stimulus-Tetanus';
      segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime];
      segmentMetaDataArray(idxSeg).meta_data.is_active = 1;
      segmentMetaDataArray(idxSeg).meta_data.channel= ...
        stimulusTetanusOptions(1).port;
      
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.initialDelay)  = ...
        expConfig.tetanus.initialDelay;
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.pulseFrequency)= ...
        expConfig.tetanus.pulseFrequency;  
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.pulseWidth)    = ...
        expConfig.tetanus.pulseWidth;
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.duration)      = ...
        tetanusDuration;

      idxSeg=idxSeg+1;

      %
      % Command
      %
         
      programMetaData = writeControlFunction610A(...
                          fid,...
                          waitTime,...
                          'Stimulus-Tetanus',...
                          stimulusTetanusOptions,...
                          auroraConfig,...                
                          programMetaData,...
                          flag_printMetaDataToFile); 
      
      endTimeError = endTime - programMetaData.controlFunction.endTime;
      assert(abs(endTimeError)<1e-3,...
          'Error: end time differs from the meta data'); 

      waitTime = expConfig.tetanus.timeToReachMaxActivation;
    end


    %
    % Ramp to some length
    %
    lengthRampOptions = ...
      getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

    lengthRampOptions(1).value = expConfig.ramp.length; 
    lengthRampOptions(2).value = expConfig.ramp.duration;
    
    startTime = programMetaData.nextStartTime ...
              + waitTime;
    endTime = startTime+expConfig.ramp.duration;

    segmentMetaDataArray(idxSeg).type = 'Ramp';
    segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime];
    segmentMetaDataArray(idxSeg).meta_data.is_active = expConfig.ramp.isActive;
    segmentMetaDataArray(idxSeg).meta_data.channel=lengthRampOptions(1).port;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.length)=lengthRampOptions(1).value;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.time)=lengthRampOptions(2).value;
    idxSeg=idxSeg+1;

    programMetaData ...
        = writeControlFunction610A(...
                fid,...
                waitTime,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
  
    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data');

    %
    % Ramp to nominalLength
    %
    lengthRampOptions = ...
      getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

    
    lengthRampOptions(1).value = nominalLength; 
    lengthRampOptions(2).value = expConfig.ramp.duration;
    
    startTime = programMetaData.nextStartTime + expConfig.ramp.holdDuration;
    endTime = startTime+lengthRampOptions(2).value;

    segmentMetaDataArray(idxSeg).type = 'Ramp';
    segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime];
    segmentMetaDataArray(idxSeg).meta_data.is_active = expConfig.ramp.isActive;
    segmentMetaDataArray(idxSeg).meta_data.channel=lengthRampOptions(1).port;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.length)=lengthRampOptions(1).value;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.time)=lengthRampOptions(2).value;
    idxSeg=idxSeg+1;

    programMetaData ...
        = writeControlFunction610A(...
                fid,...
                expConfig.ramp.holdDuration,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
  
    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data');        

    %
    % Ramp to 0
    %
    lengthRampOptions = ...
      getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

    positioningDuration = abs(nominalLength)...
                          /expConfig.positioning.rampSpeedInMMPS;
    positioningDuration = max(positioningDuration,...
                              expConfig.positioning.minimumRampTime);
    
    waitTime = max(expConfig.positioning.recoveryWaitTime,...
                   expConfig.ramp.holdDuration);

    lengthRampOptions(1).value = 0; 
    lengthRampOptions(2).value = positioningDuration;
    
    startTime = programMetaData.nextStartTime + waitTime;
    endTime = startTime+lengthRampOptions(2).value;

    segmentMetaDataArray(idxSeg).type = 'Ramp';
    segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime];
    segmentMetaDataArray(idxSeg).meta_data.is_active = expConfig.ramp.isActive;
    segmentMetaDataArray(idxSeg).meta_data.channel=lengthRampOptions(1).port;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.length)=lengthRampOptions(1).value;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.time)=lengthRampOptions(2).value;
    idxSeg=idxSeg+1;

    programMetaData ...
        = writeControlFunction610A(...
                fid,...
                waitTime,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
  
    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data');       
    %
    % Close the trial
    %
    stopWaitTime = expConfig.timing.stopWaitTime;
    if(abs(nominalLength)>1e-6)
      stopWaitTime = max(stopWaitTime,expConfig.positioning.recoveryWaitTime);
    end

    programMetaData = ...
        writeClosingBlock610A(...
            fid,...
            stopWaitTime,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);
    
    success = 1;
    assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
        'Error: maximumNumberOfCommandsExceeded');      

    %
    % Write the json files
    %
    jsonMetaData.segments = segmentMetaDataArray;

    if(expConfig.ramp.isActive==1)
      jsonMetaData.experiment.title = ...
        sprintf('Active Ramp: 0-%1.1f-0%s',...
                expConfig.ramp.length,...
                auroraConfig.defaultLengthUnit);
        jsonMetaData.experiment.tags = {'injury'};
    else
      jsonMetaData.experiment.title = ...
        sprintf('Passive Ramp: 0-%1.1f-0%s',...
                expConfig.ramp.length,...
                auroraConfig.defaultLengthUnit);
        jsonMetaData.experiment.tags = {'injury'};
    end      

    
    jsonMetaDataEncoded = jsonencode(jsonMetaData);
    fidJson = fopen(fullfile(expFolders.rootFolderPath,...
                              expFolders.sequenceMetaData,...
                             [trialFileNameNoExt,'.json']),'w');
    fprintf(fidJson,jsonMetaDataEncoded);
    fclose(fidJson);
    
    fclose(fid);
    fclose(programMetaData.labelFileHandle);