function success = createActiveLengthRampImpedanceTrial610A(...
                    lengthRamp,...
                    stochasticWaveSet,...                    
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...
                    perturbationConfig,...
                    auroraConfig)



fid = fopen(trialFileFullPath,'w');


programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFullPath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

%%
%Perturb Passive Muscle
%%

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
end

startTimeBlock              = programMetaData.nextStartTime;
waitTimeForBlock            = 0;
flag_printMetaDataToFile    = 1;


for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs(endTimeBlock-startTimeBlock-waveDurationInS) < 1e-6,...
       'Error: timing meta data is incorrect');



%%
%Activate and measure the impedance at the starting length
%%


stimulationDurationInS = waveDurationInS ...
                        + auroraConfig.timeToReachMaxActivation ...
                        + auroraConfig.activationPaddingTime;

waitTime=1;

programMetaData = ...
    writeStimulusTetanusBlock610A(...
        fid,...
        waitTime, ...
        stimulationDurationInS,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


waitTimeForBlock=auroraConfig.timeToReachMaxActivation;


%%
%Active Perturbation
%%

startTimeBlock              = programMetaData.nextStartTime;

for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs((endTimeBlock-startTimeBlock)...
          -(waitTimeForBlock+waveDurationInS)) < 1e-6,...
       'Error: timing meta data is incorrect');

%
% Let the muscle recover
% Then activate, perform the ramp, wait, and measure the impedance
%

waitTime =   auroraConfig.activationPaddingTime ...
           + auroraConfig.restTimeBetweenActivations;


%%
% A short series of small sinusoids to probe the impedance of the
% muscle before the ramp, immediately after the ramp, and then 
% after a break (so that that the end of the probe aligns with the
% maximum allowable activation).
%%

probe(1).wait     = auroraConfig.timeToReachMaxActivation;
probe(1).duration = perturbationConfig.probe.duration;

probe(2).wait     = 0;
probe(2).duration = perturbationConfig.probe.duration;

probe(3).wait     = 1;
probe(3).duration = perturbationConfig.probe.duration;


probe(3).wait     = auroraConfig.stimulation.maxDuration ...
                   -( probe(1).wait + probe(1).duration ...
                    + lengthRamp.wait +  lengthRamp.duration ...
                    + probe(2).wait + probe(2).duration ...
                    + probe(3).duration ...
                    + auroraConfig.activationPaddingTime);

assert(probe(3).wait > 0, ['Error: insufficient time to perform ',...
    'activation-probe-ramp-probe-wait-probe sequence']);


stimulationDurationInS =  ( probe(1).wait   + probe(1).duration ...
                          + lengthRamp.wait + lengthRamp.duration ...
                          + probe(2).wait   + probe(2).duration ...
                          + probe(3).wait   + probe(3).duration ...
                          + auroraConfig.activationPaddingTime*2);


%%
%Activate
%%

programMetaData = ...
    writeStimulusTetanusBlock610A(...
        fid,...
        waitTime, ...
        stimulationDurationInS,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

stimulationEndTime = programMetaData.controlFunction.endTime;    

%%
% Probe sine wave 1
%%
[sineWaveOptions,isValid,msg]= ...
            getCommandFunctionOptions610A('Sine Wave',...
                                          'Length Out',...
                                          auroraConfig);            
assert(isValid==1,msg);


sineWaveOptions(1).value = perturbationConfig.probe.frequencyHz;
sineWaveOptions(2).value = perturbationConfig.probe.magnitude;
sineWaveOptions(3).value = perturbationConfig.probe.cycles;


waitTime  = probe(1).wait;

programMetaData  = ...
    writeControlFunction610A(   ...
        fid,...
        waitTime,...
        'Sine Wave',...
        sineWaveOptions,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


%%
%Length ramp
%%

waitTimeForBlock = 0;

programMetaData = ...
    writeLengthRampBlock610A(...
        fid, ...
        waitTimeForBlock,...
        lengthRamp.wait,...
        lengthRamp.lengthChange,...
        lengthRamp.duration,...
        lengthRamp.options,...
        auroraConfig,...
        programMetaData,...
        lengthRamp.type,...
        flag_printMetaDataToFile);

%%
% Probe sine wave 2
%%

waitTime  = probe(2).wait;

programMetaData  = ...
    writeControlFunction610A(   ...
        fid,...
        waitTime,...
        'Sine Wave',...
        sineWaveOptions,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

%%
% Probe sine wave 3
%%
waitTime  = probe(3).wait;

programMetaData  = ...
    writeControlFunction610A(   ...
        fid,...
        waitTime,...
        'Sine Wave',...
        sineWaveOptions,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

probeEndTime = programMetaData.controlFunction.endTime;


assert(abs(probeEndTime+auroraConfig.activationPaddingTime...
           -stimulationEndTime)<1e-3,...
       ['Error: The activate-probe-ramp-probe-wait-probe sequence',...
        ' did not take the correct amount of time']);


%%
%Activate and measure the impedance at the ending length
%%

waveDurationInS = 0;
startTimeBlock = startTime + auroraConfig.restTimeBetweenActivations;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
end

%Let the muscle recover
waitTime  = auroraConfig.restTimeBetweenActivations;

stimulationDurationInS = waveDurationInS ...
                        + auroraConfig.timeToReachMaxActivation ...
                        + auroraConfig.activationPaddingTime;

[stimulationEndTime, smallestNextWaitTime, lineCount] = ...
    writeStimulusTetanusBlock610A(fid, startTime, waitTime, ...
        stimulationDurationInS, lineCount, auroraConfig);

fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Activation',...
            (startTime+waitTime),stimulationEndTime);

waitTime=0;
waitTimeForBlock    = waitTime+auroraConfig.timeToReachMaxActivation;
startTimeBlock      = startTime;

for i=1:1:length(stochasticWaveSet)

    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'
        [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthRampBlock610A(fid, startTime,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,...
                (startTime+waitTimeForBlock),endTime);
            startTime = endTime;

        case 'Sine Wave'
        [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthSineBlock610A(fid, startTime,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,...
                (startTime+waitTimeForBlock),endTime);            
            startTime = endTime;
        otherwise
            assert(0,['Error: Unrecognized controlFunction',...
                     ' in the stochasticWaveSet']);
    end  

end    

assert(abs((startTime-startTimeBlock)...
          -(waveDurationInS...
           +auroraConfig.timeToReachMaxActivation)) < 1e-3,...
        ['Error: duration of activationTime and the perturbation blocks do ',...
        ' not add up']);


waitTime=auroraConfig.stop.waitTime;

if(waitTime < (stimulationEndTime-startTime+auroraConfig.restTimeBetweenActivations))
    waitTime = (  stimulationEndTime-startTime...
                + auroraConfig.restTimeBetweenActivations)...
                + auroraConfig.stop.waitTime;
end


[endTime, lineCount] = ...
    writeClosingBlock610A(fid, startTime, waitTime, lineCount, auroraConfig);

success = 1;
assert(lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');

fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Stop',...
    (startTime+waitTime),endTime);

fclose(fid);
fclose(fidLabel);
