function success = createRampImpedanceTrial610A(...                    
                    trialFileNameNoExt,...
                    stochasticWaveSet,...                                        
                    auroraConfig,...
                    expConfig,...
                    expFolders)



fid = fopen(fullfile(expFolders.rootFolderPath,...
                     expFolders.protocolFolderName,...
                     [trialFileNameNoExt,'.dpf']),'w');

trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                  expFolders.blockLabelsFolderName,...
                                  [trialFileNameNoExt,'.csv']);

programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFilePath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

jsonMetaData = struct('data',[],'protocol',[],...
                      'segments',[],'experiment',[]);


jsonMetaData.data.file = {expFolders.dataFolderName, ...
                          [trialFileNameNoExt,'.ddf']};
jsonMetaData.data.sha256 = "";

jsonMetaData.protocol.file = {expFolders.protocolFolderName, ...
                          [trialFileNameNoExt,'.dpf']};
jsonMetaData.protocol.sha256 = "";


%%
%Create the meta data structure
%%


flag_printMetaDataToFile    = 1;


numberOfSegments = length(expConfig.ramp.length) ...
                  + 1 ...
                  +length(stochasticWaveSet) ...
                  + sum(expConfig.isStochasticWaveActive);


mdfn = getMetaDataFieldNames610A(auroraConfig);

isActive = 0;

segmentMetaDataArray(numberOfSegments) = ...
    struct('type','',mdfn.time,[0,0],'meta_data',[]);

% Ramp
for idxSeg=1:1:length(expConfig.ramp.length)
    segmentMetaDataArray(idxSeg).(mdfn.time) = [0,0];
    segmentMetaDataArray(idxSeg).meta_data.is_active = isActive;
    segmentMetaDataArray(idxSeg).meta_data.channel='';
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.length)=[];
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.time)=[];
end

% Sine wave
idxSeg = length(expConfig.ramp.length)+1;
segmentMetaDataArray(idxSeg).(mdfn.time) = [0,0];
segmentMetaDataArray(idxSeg).meta_data.is_active = isActive;
segmentMetaDataArray(idxSeg).meta_data.channel='';
segmentMetaDataArray(idxSeg).meta_data.(mdfn.frequency)=[];
segmentMetaDataArray(idxSeg).meta_data.(mdfn.amplitude)=[];
segmentMetaDataArray(idxSeg).meta_data.(mdfn.cycles)=[];


for idxWave=1:1:length(stochasticWaveSet)
  %Tetanus
  if(expConfig.isStochasticWaveActive(idxWave))
    idxSeg=idxSeg+1;
    segmentMetaDataArray(idxSeg).(mdfn.time) = [0,0];
    segmentMetaDataArray(idxSeg).meta_data.is_active = ...
      expConfig.isStochasticWaveActive(idxWave);
    segmentMetaDataArray(idxSeg).meta_data.channel= '';
    
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.initialDelay)  = 0;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.pulseFrequency)= 0;  
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.pulseWidth)    = 0;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.duration)      = 0; 
  end
  
  %Stochastic perturbation
  idxSeg=idxSeg+1;
  segmentMetaDataArray(idxSeg).(mdfn.time) = [0,0];
  segmentMetaDataArray(idxSeg).meta_data.is_active = ...
    expConfig.isStochasticWaveActive(idxWave);
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.bandwidth) = [0,0];
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.amplitude) = 0;
end

idxSeg = 0;

lengthRampOptions = ...
  getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

for i=1:1:length(expConfig.ramp.length)

  lengthRampOptions(1).value    = expConfig.ramp.length(i);
  lengthRampOptions(2).value    = expConfig.ramp.duration;

  idxSeg=idxSeg+1;

  startTime = expConfig.ramp.waitTime;
  endTime   = startTime + expConfig.ramp.duration;

  segmentMetaDataArray(idxSeg).type = ...
      'Ramp';                
  segmentMetaDataArray(idxSeg).(mdfn.time)          = [startTime,endTime];  
  segmentMetaDataArray(idxSeg).meta_data.is_active  = 0;
  segmentMetaDataArray(idxSeg).meta_data.channel    ...
    = lengthRampOptions(1).port;
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.length)  ...
    =expConfig.ramp.length(i);
  segmentMetaDataArray(idxSeg).meta_data.(mdfn.time)    ...
    =lengthRampOptions(2).value;

  programMetaData ...
      = writeControlFunction610A(...
              fid,...
              expConfig.ramp.waitTime,...
              'Ramp',...
              lengthRampOptions,...
              auroraConfig,...
              programMetaData,...
              flag_printMetaDataToFile);

  endTimeError = endTime - programMetaData.controlFunction.endTime;
  assert(abs(endTimeError)<1e-3,...
      'Error: end time differs from the meta data');


  
end

%%
% Apply a sine wave to (more quickly) bring the passive forces 
% to equilibrium
%%

lengthSineOptions = getCommandFunctionOptions610A(...
                      'Sine Wave','Length Out',auroraConfig);

lengthSineOptions(1).value = expConfig.sineWave.frequency;
lengthSineOptions(2).value = expConfig.sineWave.amplitude;
lengthSineOptions(3).value = expConfig.sineWave.cycles;

sineCycles = expConfig.sineWave.cycles;
sineTime   = sineCycles/lengthSineOptions(1).value;

sineTimeRounded   = ...
  round(sineTime*auroraConfig.analogToDigitalSampleRateHz)...
  /auroraConfig.analogToDigitalSampleRateHz;

assert(abs(sineTime-sineTimeRounded) < eps*10,...
       ['Error: choose another sine wave frequency or sampling frequency',...
         ' this combination will not yield the correct number of cycles']);

startTime = programMetaData.controlFunction.endTime ...
            + expConfig.sineWave.waitTime;
endTime   = startTime + sineTime;

%
% Write the meta data
%
idxSeg=idxSeg+1;

segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime]; 

segmentMetaDataArray(idxSeg).type = ['Sine Wave'];
segmentMetaDataArray(idxSeg).meta_data.is_active = 0;

segmentMetaDataArray(idxSeg).meta_data.channel            ...
    = lengthSineOptions(1).port;
segmentMetaDataArray(idxSeg).meta_data.(mdfn.frequency) = ...
  lengthSineOptions(1).value;
segmentMetaDataArray(idxSeg).meta_data.(mdfn.amplitude) = ...
  lengthSineOptions(2).value;    
segmentMetaDataArray(idxSeg).meta_data.(mdfn.cycles) = ...
  lengthSineOptions(3).value;    

programMetaData ...
        = writeControlFunction610A(...
                fid,...
                expConfig.sineWave.waitTime,...
                'Sine Wave',...
                lengthSineOptions,...
                auroraConfig,...                
                programMetaData,...
                flag_printMetaDataToFile);  

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');


%%
% Apply stochastic perturbations
%%

flag_printMetaDataToFile    = 1;

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
    
end



for i=1:1:length(stochasticWaveSet)

    assert(strcmp(stochasticWaveSet(i).config.lengthUnits,...
                  auroraConfig.defaultLengthUnit),...
           ['Error: the default length units and the',...
            ' stochastic wave length units should match']);

    assert(strcmp(stochasticWaveSet(i).config.frequencyUnits,...
                  auroraConfig.defaultFrequencyUnit),...
           ['Error: the default frequency units and the',...
            ' stochastic wave frequency units should match']);

    assert(strcmp(stochasticWaveSet(i).config.timeUnits,...
                  auroraConfig.defaultTimeUnit),...
           ['Error: the default time units and the',...
            ' stochastic wave time units should match']);

    
    isActive = 0;
    waveStartTime = programMetaData.nextStartTime ...
                     +expConfig.stochasticWaves.waitTime;
    waveWaitTime  = expConfig.stochasticWaves.waitTime;

    if(expConfig.isStochasticWaveActive(i)==1)
      
      stimulusTetanusOptions = getCommandFunctionOptions610A(...
                            'Stimulus-Tetanus','Stimulator',auroraConfig);

      
      stimulusTetanusOptions(1).value=expConfig.tetanus.initialDelay;
      stimulusTetanusOptions(2).value=expConfig.tetanus.pulseFrequency;
      stimulusTetanusOptions(3).value=expConfig.tetanus.pulseWidth;
      

      singleWaveDuration = (stochasticWaveSet(i).config.points...
                         /stochasticWaveSet(i).config.frequencyHz);
      
      expConfig.tetanus.duration =  singleWaveDuration ...
        + expConfig.stochasticWaves.timeToReachMaxActivation ...
        + expConfig.tetanus.durationExtension;

      stimulusTetanusOptions(4).value=expConfig.tetanus.duration;

      

      startTime = waveStartTime ...
                 - expConfig.tetanus.initialDelay ...
                 - expConfig.stochasticWaves.timeToReachMaxActivation;

      endTime   = startTime ...
                  +expConfig.tetanus.initialDelay ...
                  +expConfig.tetanus.duration;
      
      waitTime  = expConfig.stochasticWaves.waitTime ...
                 - expConfig.tetanus.initialDelay ...
                 - expConfig.stochasticWaves.timeToReachMaxActivation;

      idxSeg=idxSeg+1;

      segmentMetaDataArray(idxSeg).type = 'Stimulus-Tetanus';
      segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime];
      segmentMetaDataArray(idxSeg).meta_data.is_active = 1;
      segmentMetaDataArray(idxSeg).meta_data.channel= ...
        stimulusTetanusOptions(1).port;
      
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.initialDelay)  = ...
        stimulusTetanusOptions(1).value;
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.pulseFrequency)= ...
        stimulusTetanusOptions(2).value;  
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.pulseWidth)    = ...
        stimulusTetanusOptions(3).value;
      segmentMetaDataArray(idxSeg).meta_data.(mdfn.duration)      = ...
        stimulusTetanusOptions(4).value;
    
      %
      % Command
      %
               
      programMetaData = writeControlFunction610A(...
                          fid,...
                          waitTime,...
                          'Stimulus-Tetanus',...
                          stimulusTetanusOptions,...
                          auroraConfig,...                
                          programMetaData,...
                          flag_printMetaDataToFile); 
      
      endTimeError = endTime - programMetaData.controlFunction.endTime;
      assert(abs(endTimeError)<1e-3,...
          'Error: end time differs from the meta data');  
      
      %
      % Update the variables the stochastic waves depend on
      %
      isActive=1;
    end
    %
    % Write the wave meta data
    %
    idxSeg=idxSeg+1;
    
    singleWaveDuration = (stochasticWaveSet(i).config.points...
                         /stochasticWaveSet(i).config.frequencyHz);

    
    if(isActive)
      waveWaitTime = expConfig.stochasticWaves.timeToReachMaxActivation;      
    else
      waveWaitTime  = expConfig.stochasticWaves.waitTime;      
    end

    startTime = programMetaData.nextStartTime + waveWaitTime;
    endTime   = startTime+singleWaveDuration;

    scaleAmp = 1;
    switch isActive
      case 0
        if(~isempty(expConfig.stochasticWaves.overridePassiveAmplitude))
          scaleAmp =expConfig.stochasticWaves.overridePassiveAmplitude ...
                         /max(stochasticWaveSet(i).config.magnitudeRange);
        else
          scaleAmp = expConfig.stochasticWaves.scalePassiveAmplitude;
        end
      case 1
        if(~isempty(expConfig.stochasticWaves.overrideActiveAmplitude))
          scaleAmp =expConfig.stochasticWaves.overrideActiveAmplitude ...
                         /max(stochasticWaveSet(i).config.magnitudeRange);          
        else
          scaleAmp = expConfig.stochasticWaves.scaleActiveAmplitude;
        end
      otherwise
        assert(0,'Error: isActive should be 0 or 1');
    end

    segmentMetaDataArray(idxSeg).(mdfn.time) = [startTime,endTime]; 

    segmentMetaDataArray(idxSeg).type = ...
        [stochasticWaveSet(i).controlFunction,'-Stochastic'];
    segmentMetaDataArray(idxSeg).meta_data.is_active = isActive;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.bandwidth) = ...
      stochasticWaveSet(i).config.frequencyRange;
    segmentMetaDataArray(idxSeg).meta_data.(mdfn.amplitude) = ...
      max(stochasticWaveSet(i).config.magnitudeRange).*scaleAmp;    

    %
    % Write the wave
    %
    
    switch stochasticWaveSet(i).controlFunction
        case 'Step'

            stepLengths = stochasticWaveSet(i).optionValues(:,1).*scaleAmp ...
                         +expConfig.ramp.length(end);

            programMetaData = ...
                writeLengthStepBlock610A(...
                    fid, ...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stepLengths,...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);      
        case 'Ramp'            

            rampLengths= stochasticWaveSet(i).optionValues(:,1).*scaleAmp ...
                         + expConfig.ramp.length(end);

            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    rampLengths,...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2).*scaleAmp,...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end

    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-2,...
        'Error: end time differs from the meta data');

end

jsonMetaData.segments = segmentMetaDataArray;
jsonMetaData.experiment.title = ...
  sprintf('Ramp Impedance %1.1f %s',...
          expConfig.ramp.length(end), ...
          auroraConfig.defaultLengthUnit);
jsonMetaData.experiment.tags = {'ramp-impedance'};

waitTime            = expConfig.stop.waitTime;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


jsonMetaDataEncoded = jsonencode(jsonMetaData);
fidJson = fopen(fullfile(expFolders.rootFolderPath,...
                         [trialFileNameNoExt,'.json']),'w');
fprintf(fidJson,jsonMetaDataEncoded);
fclose(fidJson);

fclose(fid);
fclose(programMetaData.labelFileHandle);
