function [timeVec,...
          signalVec,...
          controlFunctions,...
          lineCount] =...
          createSineWavePattern610A_V1_FcnWrapper(...
                          arg,...
                          indexArg,...
                          config,...
                          frequencyVector,...
                          amplitudeVector,...
                          waitTimeVector,...
                          functionOption,...
                          auroraConfig,...
                          argScale)

argVec = amplitudeVector;
argVec(indexArg) = arg./argScale;

[timeVec,...
 signalVec,...
 controlFunctions,...
 lineCount] =  createSineWavePattern610A_V1(...
                                config,...
                                frequencyVector,...
                                argVec,...
                                waitTimeVector,...
                                functionOption,...
                                auroraConfig);