function success = createPassiveLengthRampImpedanceTrial610A(...                    
                    lengthRamp,...
                    stochasticWaveSet,...
                    indexProbeWave,...
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...
                    auroraConfig)


assert(     size(lengthRamp.normLengths,1)==1 ...
        &&  size(lengthRamp.normLengths,2)==2,...
        "Error: lengthRamp.normLengths should be 1 x 2");


assert(     size(lengthRamp.lengths,1)==1 ...
        &&  size(lengthRamp.lengths,2)==2,...
        "Error: lengthRamp.normLengths should be 1 x 2");

fid = fopen(trialFileFullPath,'w');

programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFullPath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);


%%
%Move the specimen from a length of 0 to its starting length
%%

waitTime                    = 0;
flag_printMetaDataToFile    = 1;

lengthChangeOptions             = lengthRamp.options;
lengthChangeOptions(1).value    = lengthRamp.lengths(1,1);
lengthChangeOptions(2).value    = auroraConfig.prePostPositioningDuration;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthChangeOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);



%%
%Perturb Passive Muscle
%%

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
end

startTimeBlock              = programMetaData.nextStartTime;
waitTimeForBlock            = auroraConfig.passive.recoveryTime;
flag_printMetaDataToFile    = 1;


for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs(endTimeBlock-startTimeBlock...
          -waitTimeForBlock-waveDurationInS) < 1e-2,...
       'Error: timing meta data is incorrect');


%%
%Length ramp
%%

programMetaData = ...
    writeLengthRampBlock610A(...
        fid, ...
        waitTimeForBlock,...
        lengthRamp.wait,...
        lengthRamp.lengths(1,2),...
        lengthRamp.duration(1,1),...
        lengthRamp.options,...
        auroraConfig,...
        programMetaData,...
        lengthRamp.type,...
        flag_printMetaDataToFile);


%%
% Probe sine wave 1
%%
[sineWaveOptions,isValid,msg]= ...
            getCommandFunctionOptions610A('Sine Wave',...
                                          'Length Out',...
                                          auroraConfig);            
assert(isValid==1,msg);


passiveRecoveryTime = auroraConfig.passive.recoveryTime;

%for i=1:1:length(stochasticWaveSet)

i=indexProbeWave;
cycles = ceil(passiveRecoveryTime ...
              *stochasticWaveSet(i).config.probe.frequencyHz);

sineWaveOptions(1).value = stochasticWaveSet(i).config.probe.frequencyHz;
sineWaveOptions(2).value = stochasticWaveSet(i).config.probe.magnitude;
sineWaveOptions(3).value = cycles;

waitTime  = 0.25;

programMetaData  = ...
    writeControlFunction610A(   ...
        fid,...
        waitTime,...
        'Sine Wave',...
        sineWaveOptions,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);
%end


%%
%Measure the impedance at the ending length
%%
waitTimeForBlock    = 1;

for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end 


%%
%Move the specimen to its starting length of zero
%%

waitTime                    = auroraConfig.passive.recoveryTime;

flag_printMetaDataToFile    = 1;

lengthChangeOptions             = lengthRamp.options;
lengthChangeOptions(1).value    = lengthRamp.endLength;
lengthChangeOptions(2).value    = auroraConfig.prePostPositioningDuration;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthChangeOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

%%
% Closing block
%%


programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


fclose(fid);
fclose(programMetaData.labelFileHandle);
