function success = createActiveLengthRampImpedanceTrial610A(...
                    lengthRamp,...
                    stochasticWaveSet,...                    
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...
                    perturbationConfig,...
                    auroraConfig)



fid = fopen(trialFileFullPath,'w');
fidLabel = fopen(trialBlockLabelFullPath,'w');

lineCount=0;
[startTime,lineCount] = writePreamble610A(fid,lineCount,auroraConfig);

%%
%Perturb Passive Muscle
%%
for i=1:1:length(stochasticWaveSet)
    waitTimeForBlock = 0;
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'
            [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthRampBlock610A(fid, startTime,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,...
                (startTime+waitTimeForBlock),...
                endTime);
            startTime = endTime;

        case 'Sine Wave'
            [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthSineBlock610A(fid, startTime,...
                    waitTimeForBlock,...                    
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,...
                (startTime+waitTimeForBlock),...
                endTime);            
            startTime = endTime;
        otherwise
            assert(0,['Error: Unrecognized controlFunction in the',...
                      ' stochasticWaveSet']);
    end
end




%%
%Activate and measure the impedance at the starting length
%%

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
end


waitTime = 0;

stimulationDurationInS = waveDurationInS ...
                        + auroraConfig.activationTime ...
                        + auroraConfig.activationPaddingTime;

[stimulationEndTime, smallestNextWaitTime, lineCount] = ...
    writeStimulusTetanusBlock610A(fid, startTime, waitTime,...
        stimulationDurationInS,lineCount, auroraConfig);

fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Activation',...
    (startTime+waitTime),stimulationEndTime);

waitTimeForBlock = auroraConfig.activationTime;

startTimeBlock = startTime;
for i=1:1:length(stochasticWaveSet)

    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'
        [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthRampBlock610A(fid, startTime,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,...
                    (startTime+waitTimeForBlock),...
                    endTime);
            startTime = endTime;

        case 'Sine Wave'
        [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthSineBlock610A(fid, startTime,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,...
                    (startTime+waitTimeForBlock),...
                    endTime);            
            startTime = endTime;
        otherwise
            assert(0,['Error: Unrecognized controlFunction in the',...
                      ' stochasticWaveSet']);
    end  

end    
assert(abs((startTime-startTimeBlock)...
          -(waveDurationInS+auroraConfig.activationTime)) < 1e-3,...
        ['Error: duration of activationTime and the perturbation blocks do ',...
        ' not add up']);

assert(stimulationEndTime > startTime,...
       'Error: stimulation shut off before perturbations completed');

%
% Let the muscle recover
% Then activate, perform the ramp, wait, and measure the impedance
%

waitTime = (stimulationEndTime+auroraConfig.restTimeBetweenActivations) ...
           - startTime;




%%
% A short series of small sinusoids to probe the impedance of the
% muscle before the ramp, immediately after the ramp, and then 
% after a break (so that that the end of the probe aligns with the
% maximum allowable activation).
%%

probe(1).wait     = auroraConfig.activationTime;
probe(1).duration = perturbationConfig.probe.duration;

probe(2).wait     = 0;
probe(2).duration = perturbationConfig.probe.duration;

probe(3).wait     = 1;
probe(3).duration = perturbationConfig.probe.duration;


probe(3).wait     = auroraConfig.stimulation.maxDuration ...
                   -( probe(1).wait + probe(1).duration ...
                    + lengthRamp.wait +  lengthRamp.duration ...
                    + probe(2).wait + probe(2).duration ...
                    + probe(3).duration);

assert(probe(3).wait > 0, ['Error: insufficient time to perform ',...
    'activation-probe-ramp-probe-wait-probe sequence']);


stimulationDurationInS =  ( probe(1).wait   + probe(1).duration ...
                          + lengthRamp.wait + lengthRamp.duration ...
                          + probe(2).wait   + probe(2).duration ...
                          + probe(3).wait   + probe(3).duration);


%%
%Activate
%%
[stimulationEndTime, smallestNextWaitTime, lineCount] = ...
    writeStimulusTetanusBlock610A(fid, startTime, waitTime,...
     stimulationDurationInS, lineCount, auroraConfig);

fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
    'Activation',...
    (startTime+waitTime),...
    stimulationEndTime);

%%
% Probe sine wave 1
%%
[sineWaveOptions,isValid,msg]= ...
            getCommandFunctionOptions610A('Sine Wave',...
                                          'Length Out',...
                                          auroraConfig);            
assert(isValid==1,msg);


sineWaveOptions(1).value = perturbationConfig.probe.frequencyHz;
sineWaveOptions(2).value = perturbationConfig.probe.magnitude;
sineWaveOptions(3).value = perturbationConfig.probe.cycles;


waitTime  = waitTime + probe(1).wait;

[smallestNextWaitTime, commandDuration] = ...
     writeControlFunction610A(fid, waitTime, ...
        'Sine Wave',sineWaveOptions,auroraConfig);

fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
    perturbationConfig.probe.type,...
    (startTime+waitTime),...
    (startTime+commandDuration));


%%
%Length ramp
%%

startTime = startTime + commandDuration;
waitTimeForBlock = 0;
[endTime, lineCount] = ...
        writeLengthRampBlock610A(fid, startTime,...
                    waitTimeForBlock,...            
                    lengthRamp.wait,...
                    lengthRamp.lengthChange,...
                    lengthRamp.duration,...
                    lengthRamp.options,...
                    lineCount,...
                    auroraConfig);
fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
    lengthRamp.type,...
    (startTime+waitTimeForBlock),...
    (endTime));
startTime = endTime;
%%
% Probe sine wave 2
%%
waitTime  = probe(2).wait;
[smallestNextWaitTime, commandDuration] = ...
     writeControlFunction610A(fid, waitTime, ...
        'Sine Wave',sineWaveOptions,auroraConfig);

fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
    perturbationConfig.probe.type,...
    (startTime+waitTime),...
    (startTime+commandDuration));

%%
% Probe sine wave 3
%%
startTime = startTime + commandDuration;
waitTime  = probe(3).wait;

[smallestNextWaitTime, commandDuration] = ...
     writeControlFunction610A(fid, waitTime, ...
        'Sine Wave',sineWaveOptions,auroraConfig);

fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
    perturbationConfig.probe.type,...
    (startTime+waitTime),...
    (startTime+commandDuration));

startTime = startTime + commandDuration;


assert(abs(startTime-stimulationEndTime)<1e-3,...
       ['Error: The activate-probe-ramp-probe-wait-probe sequence',...
        ' did not take the correct amount of time']);


%%
%Activate and measure the impedance at the ending length
%%

waveDurationInS = 0;
startTimeBlock = startTime + auroraConfig.restTimeBetweenActivations;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
end

%Let the muscle recover
waitTime  = auroraConfig.restTimeBetweenActivations;

stimulationDurationInS = waveDurationInS ...
                        + auroraConfig.activationTime ...
                        + auroraConfig.activationPaddingTime;

[stimulationEndTime, smallestNextWaitTime, lineCount] = ...
    writeStimulusTetanusBlock610A(fid, startTime, waitTime, ...
        stimulationDurationInS, lineCount, auroraConfig);

fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Activation',...
            (startTime+waitTime),stimulationEndTime);

waitTimeForBlock    = waitTime+auroraConfig.activationTime;
startTimeBlock      = startTime;

for i=1:1:length(stochasticWaveSet)

    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'
        [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthRampBlock610A(fid, startTime,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,...
                (startTime+waitTimeForBlock),endTime);
            startTime = endTime;

        case 'Sine Wave'
        [endTime, smallestNextWaitTime, lineCount] = ...
                writeLengthSineBlock610A(fid, startTime,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,...
                (startTime+waitTimeForBlock),endTime);            
            startTime = endTime;
        otherwise
            assert(0,['Error: Unrecognized controlFunction',...
                     ' in the stochasticWaveSet']);
    end  

end    

assert(abs((startTime-startTimeBlock)...
          -(auroraConfig.restTimeBetweenActivations...
           +waveDurationInS...
           +auroraConfig.activationTime)) < 1e-3,...
        ['Error: duration of activationTime and the perturbation blocks do ',...
        ' not add up']);


waitTime=auroraConfig.stop.waitTime;

if(waitTime < (stimulationEndTime-startTime+auroraConfig.restTimeBetweenActivations))
    waitTime = (  stimulationEndTime-startTime...
                + auroraConfig.restTimeBetweenActivations)...
                + auroraConfig.stop.waitTime;
end


[endTime, lineCount] = ...
    writeClosingBlock610A(fid, startTime, waitTime, lineCount, auroraConfig);

success = 1;
assert(lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');

fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Stop',...
    (startTime+waitTime),endTime);

fclose(fid);
fclose(fidLabel);
