function success = createStretchShortenTrial610A_01(...
                      startEndLength,...
                      trialFileNameNoExt,...                                     
                      auroraConfig,...
                      expConfig,...
                      expFolders,...
                      flag_isASequence)



flag_printMetaDataToFile=1;

fid = fopen(fullfile(expFolders.rootFolderPath,...
                     expFolders.protocolFolderName,...
                     [trialFileNameNoExt,'.dpf']),'w');



trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                  expFolders.blockLabelsFolderName,...
                                  [trialFileNameNoExt,'.csv']);

programMetaData = getEmptyProgramMetaDataStruct610A_01( ...
                    startEndLength,...
                    trialBlockLabelFilePath);

programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

mdfn = getMetaDataFieldNames610A(auroraConfig);

if(flag_isASequence==0)
  jsonMetaData = struct('data',[],'protocol',[],...
                        'segments',[],'experiment',[]);
    
  jsonMetaData.data.file = {expFolders.dataFolderName, ...
                            [trialFileNameNoExt,'.ddf']};
  jsonMetaData.data.sha256 = "";
  
  jsonMetaData.protocol.file = {expFolders.protocolFolderName, ...
                            [trialFileNameNoExt,'.dpf']};
  jsonMetaData.protocol.sha256 = "";
else
  jsonMetaData = struct('segments',[],'experiment',[]); 
end    


segmentMetaDataArray = [];

%
% Ramp from 0 to startEndLength
%
lengthRampOptions = ...
  getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

positioningDuration = abs(startEndLength)...
                      /expConfig.positioning.rampSpeedInMMPS;
positioningDuration = max(positioningDuration,...
                          expConfig.positioning.minimumRampTime);

lengthRampOptions(1).value = startEndLength; 
lengthRampOptions(2).value = positioningDuration;

startTime = programMetaData.nextStartTime;
endTime = startTime+lengthRampOptions(2).value;

[programMetaData,fcnMetaData]...
    = writeControlFunction610A_01(...
            fid,...
            0,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');        

%
% Meta data
%
waitTime = 1;
if(abs(startEndLength) > 1e-6)
  waitTime = expConfig.positioning.recoveryWaitTime;
end
rampDuration = expConfig.ramp.duration;

if(expConfig.ramp.isActive==1)

  activeRampTime = rampDuration*2;

  sampleFrequency = auroraConfig.analogToDigitalSampleRateHz;
  dt = 1/sampleFrequency;

  tetanusDuration  = activeRampTime ...
                   +2*dt ...
                   +expConfig.tetanus.timeToReachMaxActivation...
                   +expConfig.tetanus.durationExtension;

  stimulusTetanusOptions = getCommandFunctionOptions610A(...
                            'Stimulus-Tetanus','Stimulator',auroraConfig);
  
  stimulusTetanusOptions(1).value=expConfig.tetanus.initialDelay;
  stimulusTetanusOptions(2).value=expConfig.tetanus.pulseFrequency;
  stimulusTetanusOptions(3).value=expConfig.tetanus.pulseWidth;
  stimulusTetanusOptions(4).value=tetanusDuration;

  startTime = programMetaData.nextStartTime+waitTime;
  endTime   = startTime ...
              +expConfig.tetanus.initialDelay ...
              +tetanusDuration;
 
  %
  % Command
  %
     
  [programMetaData, fcnMetaData] = ...
    writeControlFunction610A_01(...
                      fid,...
                      waitTime,...
                      'Stimulus-Tetanus',...
                      stimulusTetanusOptions,...
                      auroraConfig,...                
                      programMetaData,...
                      flag_printMetaDataToFile); 
  segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

  waitTime = expConfig.tetanus.timeToReachMaxActivation;

  endTimeError = endTime - programMetaData.controlFunction.endTime;   
  assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');        

end


%
% Ramp to some length
%
lengthRampOptions = ...
  getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

lengthRampOptions(1).value = expConfig.ramp.length; 
lengthRampOptions(2).value = expConfig.ramp.duration;

startTime = programMetaData.nextStartTime ...
          + waitTime;
endTime = startTime+expConfig.ramp.duration;

[programMetaData,fcnMetaData] ...
    = writeControlFunction610A_01(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];    

endTimeError = endTime - programMetaData.controlFunction.endTime;   
assert(abs(endTimeError)<1e-3,...
  'Error: end time differs from the meta data');      
%
% Ramp to startEndLength
%
lengthRampOptions = ...
  getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);


lengthRampOptions(1).value = startEndLength; 
lengthRampOptions(2).value = expConfig.ramp.duration;

startTime = programMetaData.nextStartTime + expConfig.ramp.holdDuration;
endTime = startTime+lengthRampOptions(2).value;

[programMetaData,fcnMetaData] ...
    = writeControlFunction610A_01(...
            fid,...
            expConfig.ramp.holdDuration,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];    

endTimeError = endTime - programMetaData.controlFunction.endTime;   
assert(abs(endTimeError)<1e-3,...
  'Error: end time differs from the meta data');      
  
%
% Close the trial
%
stopWaitTime = expConfig.timing.stopWaitTime;
if(abs(startEndLength)>1e-6)
  stopWaitTime = max(stopWaitTime,expConfig.positioning.recoveryWaitTime);
end

disableOptions = getCommandFunctionOptions610A('Stop','',auroraConfig);

[programMetaData,fcnMetaData]...
     = writeControlFunction610A_01(...
        fid,...
        stopWaitTime,...
        'Stop',...
        disableOptions,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData]; 

fclose(fid);
fclose(programMetaData.labelFileHandle);

assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');      

%
% Write the json files
%

if(expConfig.ramp.isActive==1)
  experimentTitle = ...
    sprintf('Active Ramp: 0-%1.1f-0%s',...
            expConfig.ramp.length,...
            auroraConfig.defaultLengthUnit);
  experimentTags = {'injury'};
else
  experimentTitle = ...
    sprintf('Passive Ramp: 0-%1.1f-0%s',...
            expConfig.ramp.length,...
            auroraConfig.defaultLengthUnit);
  experimentTags = {'injury'};
end      


success = writeMetaDataStructure610A(...
            segmentMetaDataArray,...
            expConfig,...
            experimentTitle,...
            experimentTags,...
            trialFileNameNoExt,...
            expFolders,...                          
            flag_isASequence);

success = writeTimeSeriesDataAndImages610A(...
            programMetaData,...
            auroraConfig,...
            trialFileNameNoExt,...
            expFolders);
    