function success = createPassiveLengthRampImpedanceTrial610A(...
                    lengthRamp,...
                    stochasticWaveSet,...                    
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...
                    perturbationConfig,...
                    auroraConfig)



fid = fopen(trialFileFullPath,'w');


programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFullPath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

%%
%Perturb Passive Muscle
%%

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
end

startTimeBlock              = programMetaData.nextStartTime;
waitTimeForBlock            = 0;
flag_printMetaDataToFile    = 1;


for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

endTimeBlock = programMetaData.controlFunction.endTime;
assert(abs(endTimeBlock-startTimeBlock-waveDurationInS) < 1e-6,...
       'Error: timing meta data is incorrect');


%%
%Length ramp
%%

programMetaData = ...
    writeLengthRampBlock610A(...
        fid, ...
        waitTimeForBlock,...
        lengthRamp.wait,...
        lengthRamp.lengthChange,...
        lengthRamp.duration,...
        lengthRamp.options,...
        auroraConfig,...
        programMetaData,...
        lengthRamp.type,...
        flag_printMetaDataToFile);


%%
% Probe sine wave 1
%%
[sineWaveOptions,isValid,msg]= ...
            getCommandFunctionOptions610A('Sine Wave',...
                                          'Length Out',...
                                          auroraConfig);            
assert(isValid==1,msg);


passiveRecoveryTime = auroraConfig.passive.recoveryTime;

cycles = ceil(passiveRecoveryTime*perturbationConfig.probe.frequencyHz);

sineWaveOptions(1).value = perturbationConfig.probe.frequencyHz;
sineWaveOptions(2).value = perturbationConfig.probe.magnitude;
sineWaveOptions(3).value = cycles;


waitTime  = 0.25;

programMetaData  = ...
    writeControlFunction610A(   ...
        fid,...
        waitTime,...
        'Sine Wave',...
        sineWaveOptions,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);



%%
%Measure the impedance at the ending length
%%
waitTimeForBlock    = 1;

for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Ramp'            
            programMetaData = ...
                writeLengthRampBlock610A(...
                    fid, ...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            programMetaData = ...
                writeLengthSineBlock610A(...
                    fid,...
                    waitTimeForBlock,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end 


programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


fclose(fid);
fclose(programMetaData.labelFileHandle);
