function success = createIsometricImpedanceTrial610A_01(...
                    startEndLength,...
                    nominalLength,...
                    stochasticWaveSet,...
                    trialFileNameNoExt,...                    
                    auroraConfig,...
                    expConfig,...
                    expFolders, ...
                    flag_isASequence)

assert(length(stochasticWaveSet)==1);

flag_printMetaDataToFile=1;

fid = fopen(fullfile(expFolders.rootFolderPath,...
                     expFolders.protocolFolderName,...
                     [trialFileNameNoExt,'.dpf']),'w');


trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                  expFolders.blockLabelsFolderName,...
                                  [trialFileNameNoExt,'.csv']);

programMetaData = getEmptyProgramMetaDataStruct610A_01(...
                      startEndLength,...
                      trialBlockLabelFilePath);

programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

mdfn = getMetaDataFieldNames610A(auroraConfig);


if(flag_isASequence==0)
  jsonMetaData = struct('data',[],'protocol',[],...
                        'segments',[],'experiment',[]);
  
  
  jsonMetaData.data.file = {expFolders.dataFolderName, ...
                            [trialFileNameNoExt,'.ddf']};
  jsonMetaData.data.sha256 = "";
  
  jsonMetaData.protocol.file = {expFolders.protocolFolderName, ...
                            [trialFileNameNoExt,'.dpf']};
  jsonMetaData.protocol.sha256 = "";
else
  jsonMetaData = struct('segments',[],'experiment',[]); 
end

%%
%Create the meta data structure
%%


flag_printMetaDataToFile    = 1;
segmentMetaDataArray = [];


%%
%Move the specimen to its nominal length
%%
lengthRampOptions = ...
  getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

waitTime                    = 1;
flag_printMetaDataToFile    = 1;

positioningDuration = abs(nominalLength)...
                      /expConfig.positioning.rampSpeedInMMPS;
positioningDuration = max(positioningDuration,...
                          expConfig.positioning.minimumRampTime);

lengthRampOptions(1).value = nominalLength; 
lengthRampOptions(2).value = positioningDuration;

startTime = programMetaData.nextStartTime+waitTime;
endTime = startTime+positioningDuration;

[programMetaData,fcnMetaData] ...
    = writeControlFunction610A_01(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');      


%%
%Passive Perturbation
%%

waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
    
end



for i=1:1:length(stochasticWaveSet)

    assert(strcmp(stochasticWaveSet(i).config.lengthUnits,...
                  auroraConfig.defaultLengthUnit),...
           ['Error: the default length units and the',...
            ' stochastic wave length units should match']);

    assert(strcmp(stochasticWaveSet(i).config.frequencyUnits,...
                  auroraConfig.defaultFrequencyUnit),...
           ['Error: the default frequency units and the',...
            ' stochastic wave frequency units should match']);

    assert(strcmp(stochasticWaveSet(i).config.timeUnits,...
                  auroraConfig.defaultTimeUnit),...
           ['Error: the default time units and the',...
            ' stochastic wave time units should match']);

    %
    % Write the wave meta data
    %
    
    singleWaveDuration = (stochasticWaveSet(i).config.points...
                         /stochasticWaveSet(i).config.frequencyHz);

    waveWaitTime  = expConfig.impedance.waitTime;   
    if(i==1)
      waveWaitTime = expConfig.positioning.recoveryWaitTime;
    end


    startTime = programMetaData.nextStartTime + waveWaitTime;
    endTime   = startTime+singleWaveDuration;

    scaleAmp = 1;
    targetAmplitude = expConfig.impedance.amplitude;
    defaultAmplitude = max(stochasticWaveSet(i).config.magnitudeRange);

    scaleAmp = targetAmplitude/defaultAmplitude;

 
    fcnMetaDataBlock.type = ...
        [stochasticWaveSet(i).controlFunction,'-Stochastic'];
    fcnMetaDataBlock.(mdfn.time) = [startTime,endTime];
    fcnMetaDataBlock.meta_data.is_active = 0;
    fcnMetaDataBlock.meta_data.(mdfn.bandwidth) = ...
      stochasticWaveSet(i).config.frequencyRange;
    fcnMetaDataBlock.meta_data.(mdfn.amplitude) = ...
      max(stochasticWaveSet(i).config.magnitudeRange).*scaleAmp;    

    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaDataBlock];

    %
    % Write the wave
    %
    
    switch stochasticWaveSet(i).controlFunction
        case 'Step'

            stepLengths = stochasticWaveSet(i).optionValues(:,1).*scaleAmp ...
                         +nominalLength;

            [programMetaData,fcnMetaDataArray] = ...
                writeLengthStepBlock610A_01(...
                    fid, ...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stepLengths,...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);      
        case 'Ramp'            

            rampLengths= stochasticWaveSet(i).optionValues(:,1).*scaleAmp ...
                         + nominalLength;

            [programMetaData,fcnMetaDataArray] = ...
                writeLengthRampBlock610A_01(...
                    fid, ...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    rampLengths,...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            [programMetaData,fcnMetaDataArray] = ...
                writeLengthSineBlock610A_01(...
                    fid,...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2).*scaleAmp,...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end

    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-2,...
        'Error: end time differs from the meta data');

end



%%
%Activate
%%

waitTime = max(expConfig.positioning.recoveryWaitTime,...
               expConfig.timing.waitTime);

tetanusDuration  =waveDurationInS ...
                 +expConfig.tetanus.timeToReachMaxActivation ...
                 +expConfig.tetanus.durationExtension;

stimulusTetanusOptions = getCommandFunctionOptions610A(...
                          'Stimulus-Tetanus','Stimulator',auroraConfig);

stimulusTetanusOptions(1).value=expConfig.tetanus.initialDelay;
stimulusTetanusOptions(2).value=expConfig.tetanus.pulseFrequency;
stimulusTetanusOptions(3).value=expConfig.tetanus.pulseWidth;
stimulusTetanusOptions(4).value=tetanusDuration;

startTime = programMetaData.nextStartTime+waitTime;
endTime = startTime ...
            +expConfig.tetanus.initialDelay ...
            +tetanusDuration;
   
[programMetaData,fcnMetaData] = ...
  writeControlFunction610A_01(...
        fid,...
        waitTime,...
        'Stimulus-Tetanus',...
        stimulusTetanusOptions,...
        auroraConfig,...                
        programMetaData,...
        flag_printMetaDataToFile); 

segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data'); 

waitTime = expConfig.tetanus.timeToReachMaxActivation;

%%
%Active Perturbation
%%
waveDurationInS = 0;
for i=1:1:length(stochasticWaveSet)
    waveDurationInS = waveDurationInS ...
         + (stochasticWaveSet(i).config.points...
           /stochasticWaveSet(i).config.frequencyHz);
    
end



for i=1:1:length(stochasticWaveSet)

    assert(strcmp(stochasticWaveSet(i).config.lengthUnits,...
                  auroraConfig.defaultLengthUnit),...
           ['Error: the default length units and the',...
            ' stochastic wave length units should match']);

    assert(strcmp(stochasticWaveSet(i).config.frequencyUnits,...
                  auroraConfig.defaultFrequencyUnit),...
           ['Error: the default frequency units and the',...
            ' stochastic wave frequency units should match']);

    assert(strcmp(stochasticWaveSet(i).config.timeUnits,...
                  auroraConfig.defaultTimeUnit),...
           ['Error: the default time units and the',...
            ' stochastic wave time units should match']);

    %
    % Write the wave meta data
    %
    
    singleWaveDuration = (stochasticWaveSet(i).config.points...
                         /stochasticWaveSet(i).config.frequencyHz);

    waveWaitTime  = waitTime;      


    startTime = programMetaData.nextStartTime + waveWaitTime;
    endTime   = startTime+singleWaveDuration;

    scaleAmp = 1;
    targetAmplitude = expConfig.impedance.amplitude;
    defaultAmplitude = max(stochasticWaveSet(i).config.magnitudeRange);

    scaleAmp = targetAmplitude/defaultAmplitude;

    fcnMetaDataBlock.type = ...
        [stochasticWaveSet(i).controlFunction,'-Stochastic'];
    fcnMetaDataBlock.(mdfn.time) = [startTime,endTime];
    fcnMetaDataBlock.meta_data.is_active = 1;
    fcnMetaDataBlock.meta_data.(mdfn.bandwidth) = ...
      stochasticWaveSet(i).config.frequencyRange;
    fcnMetaDataBlock.meta_data.(mdfn.amplitude) = ...
      max(stochasticWaveSet(i).config.magnitudeRange).*scaleAmp;    

    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaDataBlock];

    %
    % Write the wave
    %
    
    switch stochasticWaveSet(i).controlFunction
        case 'Step'

            stepLengths = stochasticWaveSet(i).optionValues(:,1).*scaleAmp ...
                         +nominalLength;

            [programMetaData,fcnMetaDataArray] = ...
                writeLengthStepBlock610A_01(...
                    fid, ...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stepLengths,...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);      
        case 'Ramp'            

            rampLengths= stochasticWaveSet(i).optionValues(:,1).*scaleAmp ...
                         + nominalLength;

            [programMetaData,fcnMetaDataArray] = ...
                writeLengthRampBlock610A_01(...
                    fid, ...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    rampLengths,...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);

        case 'Sine Wave'
            [programMetaData,fcnMetaDataArray] = ...
                writeLengthSineBlock610A_01(...
                    fid,...
                    waveWaitTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2).*scaleAmp,...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    auroraConfig,...
                    programMetaData,...
                    stochasticWaveSet(i).type,...
                    flag_printMetaDataToFile);
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end

    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-2,...
        'Error: end time differs from the meta data');

end

%%
%Move the specimen from its ending length to a length of 0
%%

lengthRampOptions = ...
  getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

waitTime                    = 1;

positioningDuration = abs(nominalLength-startEndLength)...
                      /expConfig.positioning.rampSpeedInMMPS;
positioningDuration = max(positioningDuration,...
                          expConfig.positioning.minimumRampTime);


lengthRampOptions(1).value    = startEndLength;
lengthRampOptions(2).value    = positioningDuration;

startTime = programMetaData.nextStartTime+waitTime;
endTime = startTime+positioningDuration;


[programMetaData,fcnMetaData] ...
    = writeControlFunction610A_01(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);
segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');   


%%
%Write the ending block.
%%
disableOptions = getCommandFunctionOptions610A('Stop','',auroraConfig);

stopWaitTime=expConfig.timing.stopWaitTime;
stopWaitTime = max(stopWaitTime,expConfig.positioning.recoveryWaitTime);

[programMetaData, fcnMetaData] ...
    = writeControlFunction610A_01(...
            fid,...
            stopWaitTime,...
            'Stop',...
            disableOptions,...              
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');

fclose(fid);
fclose(programMetaData.labelFileHandle);

%
% Write the json files
%
jsonMetaData.segments = segmentMetaDataArray;

experimentTitle = ...
  sprintf('Active Isometric Impedance: %1.1f mm',...
          nominalLength);

experimentTags = {'impedance'};

success = writeMetaDataStructure610A(...
            segmentMetaDataArray,...
            expConfig,...
            experimentTitle,...
            experimentTags,...
            trialFileNameNoExt,...
            expFolders,...                          
            flag_isASequence);

success = writeTimeSeriesDataAndImages610A(...
            programMetaData,...
            auroraConfig,...
            trialFileNameNoExt,...
            expFolders);