function [timeVec,...
          signalVec,...
          controlFunctions,...
          lineCount] =...
          createSineWavePattern610A_V2_FcnWrapper(...
                          arg,...
                          indexArg,...
                          config,...
                          frequencyVector,...
                          amplitudeVector,...
                          frequencyVectorMap,...
                          waitTimeVector,...
                          randomNumberGeneratorConfig,...
                          functionOption,...
                          auroraConfig,...
                          argScale,...
                          optVarName)

amplitudeVectorInput = amplitudeVector;
frequencyVectorMapInput = frequencyVectorMap;

switch optVarName
  case 'amplitude'
    argVec = amplitudeVector;
    argVec(indexArg) = arg./argScale;
    amplitudeVectorInput=argVec;
  case 'frequency'
    argVec = frequencyVectorMap;
    argVec(indexArg) = arg./argScale;    
    frequencyVectorMapInput=argVec;
end

[timeVec,...
 signalVec,...
 controlFunctions,...
 lineCount] =  createSineWavePattern610A_V1(...
                                config,...
                                frequencyVector,...
                                amplitudeVectorInput,...
                                frequencyVectorMapInput,...
                                waitTimeVector,...
                                randomNumberGeneratorConfig,...
                                functionOption,...
                                auroraConfig);