function [  preConditioningWave, ...
            stochasticWave, ...
            figPerturbation] = createPerturbationWave610A(...
                                  controlFunctionName,...
                                  functionOptions,...
                                  configVibration,...
                                  auroraConfig,...
                                  figPerturbation,...
                                  perturbationPlotConfig,...
                                  verbose)
%%
% @return stochasticWave
% A pseudo-random stochastic perturbation signal for use
% in system identification as applied to muscle fibers
%
% @return preConditioningWave
% An isometric fiber's force drops immediately once its length is perturbed
% to a lower value. This makes the system time-variant. To make the 
% response more consistent with an LTI system, here we generate a set of 
% vibrations that can be used prior to the stochastic wave in order to 
% pre-condition it so that its mean force does not drop when the 
% stochastic perturbation is applied.
%
% The other option is to perturb in the force domain, which is possible
% with the Aurora machine.
% 
%%
pointsHalf = configVibration.points/2;    

if(verbose==1)
    fprintf('\n\nSystem Identification Perturbation\n');
    fprintf('\t%s\tWaveform\n',controlFunctionName);
    fprintf('\t%1.2e s\tDuration\n',configVibration.duration);
    fprintf('\t%1.2e\ttmin\n',...
        min(configVibration.holdRange));
    fprintf('\t%1.2e\ttmax\n',...
        max(configVibration.holdRange)); 
    if(length(configVibration.holdRange)==2)
      fprintf('\t%1.2e\ttmax/tmin\n',...
          (configVibration.holdRange(1,2)/configVibration.holdRange(1,1)));
    end
end

%%
%  Create the random hold vector vector
%%

signOfFirstChange=1;





switch controlFunctionName
    case 'Step' 
      
      timeStart     = 0;
      timeEnd       = (configVibration.points/configVibration.frequencyHz);
      fcnMeanLength = @(arg)interp1([timeStart,timeEnd]',[0,0],arg);

      [timeVec,...
       signalVec,...
       stochasticFunctions,...
       numberOfStochasticWaveCommands]  = ...
        createStepSineWavePattern610A(...
            fcnMeanLength,...
            configVibration,...
            configVibration.frequencyRange,...
            configVibration.magnitudeRange(1,1),...
            functionOptions,...
            auroraConfig);


     flag_enableFitting=1;
     nCommands = (size(stochasticFunctions.optionValues,1)-2)/2;

     if(configVibration.fitPerturbationPowerSpectrum==1 ...
         && flag_enableFitting == 1)

       indexArg = [1:1:nCommands]';
  
       argScale = 1./configVibration.magnitudeRange(1,2);
  
       magnitudeDefault = ones(nCommands,1).*configVibration.magnitudeRange(1,2);

       x0       = magnitudeDefault.*argScale;
  
       fcnWave = @(arg)createStepWavePattern610A_FcnWrapper(...
                          arg,...
                          indexArg,...
                          fcnMeanLength,...
                          configVibration,...
                          configVibration.frequencyRange,...
                          magnitudeDefault,...
                          functionOptions,...
                          auroraConfig,...
                          argScale);

  
       lb = ones(size(indexArg)).*0.0;    
       ub = ones(size(indexArg)).*(configVibration.magnitudeRange(1,2).*argScale);
  
       lsqOptions = optimoptions('lsqnonlin', ...
                        'Algorithm','levenberg-marquardt',...
                        'MaxFunctionEvaluations', 1000000, ...
                        'FunctionTolerance',1e-6,...
                        'MaxIterations',2000,...
                        'StepTolerance',1e-6,...
                        'OptimalityTolerance',1e-4,...
                        'FiniteDifferenceType','central');         
       lambdaVec = [0];

       idxLoop=1;
       objScale=1;
       spectrumError = calcWavePowerSpectrumError(...
                          x0,fcnWave,...
                          configVibration,...
                          objScale,...
                          lambdaVec(idxLoop));
  
       objScale = sqrt(mean(spectrumError.^2));
  
       fcnWaveError = @(arg)calcWavePowerSpectrumError(...
                            arg,fcnWave,...
                            configVibration,...
                            objScale,...
                            lambdaVec(idxLoop));

       [x1,resnorm,residual,exitflag] = ...
         lsqnonlin(fcnWaveError,x0,lb,ub,lsqOptions);


       x0=x1;
       i0=1;
       i1=max(indexArg);
      
       vibrationMagnitude= x1(i0:i1,1)./argScale(1,1);

       [timeVec,...
       signalVec,...
       stochasticFunctions,...
       numberOfStochasticWaveCommands]  = ...
        createStepSineWavePattern610A(...
            fcnMeanLength,...
            configVibration,...
            configVibration.frequencyRange,...
            vibrationMagnitude,...
            functionOptions,...
            auroraConfig);

     end
    case 'Ramp'    
        rng(1,'twister'); 
        randomVecA = rand(configVibration.points,1);
        
        rng(2,'twister'); 
        randomVecB = rand(configVibration.points,1);      
        
        if(randomVecA(pointsHalf,1)>(0.5*(diff(configVibration.holdRange))))
            signOfFirstChange=-1;
        end        

        if(length(configVibration.holdRange) == 2 ...
                && abs(diff(configVibration.holdRange)) > 0)
            randomSignals.duration = ...
               (1-randomVecA).*(configVibration.holdRange(1,1)) ...
                  +randomVecA.*(configVibration.holdRange(1,2)...
                               -configVibration.holdRange(1,1));
        else
            randomSignals.duration = ones(size(randomVecA)).*configVibration.holdRange(1,1);
        end
        
        if(length(configVibration.normSpeedRange) == 2 ...
                && abs(diff(configVibration.normSpeedRange)) > 0 )
            randomSignals.velocity = ...
                (1-randomVecB).*(configVibration.normSpeedRange(1,1)) ...
                   +randomVecB.*(configVibration.normSpeedRange(1,2)...
                                -configVibration.normSpeedRange(1,1));
            
        else
            randomSignals.velocity = ...
                ones(size(randomVecA)).*configVibration.normSpeedRange(1,1);
        end

        [timeVec,...
        signalVec,...
        stochasticFunctions,...
        numberOfStochasticWaveCommands] =...
        createSquareWavePattern610A(...
                         configVibration,...
                         randomSignals.duration,...
                         randomSignals.velocity,...
                         signOfFirstChange,...
                         functionOptions,...
                         auroraConfig);

    case 'Sine Wave'

      randomNumberGeneratorConfig.type='twister';
      randomNumberGeneratorConfig.seed=3;

      [timeVec,...
      signalVec,...
      stochasticFunctions,...
      numberOfStochasticWaveCommands] = ...
        createSineWavePattern610A_V1(...
                  configVibration,...
                  configVibration.frequencyRange,...
                  configVibration.magnitudeRange(1,1),...
                  configVibration.waitTimeRange(1,1),...
                  randomNumberGeneratorConfig,...
                  functionOptions,...
                  auroraConfig);

      flag_enableFitting=1;
      nCommands = size(stochasticFunctions.optionValues,1)-2;

      if(configVibration.fitPerturbationPowerSpectrum==1 && flag_enableFitting == 1)

         indexArg = [1:1:nCommands]';
    
         argScale = 1./configVibration.magnitudeRange(1,2);
    
         magnitudeDefault = ones(nCommands,1).*configVibration.magnitudeRange(1,2);

         x0       = magnitudeDefault.*argScale;
    
         fcnWave = @(arg)createSineWavePattern610A_V1_FcnWrapper(...
                            arg,...
                            indexArg,...
                            configVibration,...
                            configVibration.frequencyRange,...
                            magnitudeDefault,...
                            configVibration.waitTimeRange(1,1),...
                            randomNumberGeneratorConfig,...
                            functionOptions,...
                            auroraConfig,...
                            argScale);

    
         lb = ones(size(indexArg)).*0.0;    
         ub = ones(size(indexArg)).*(configVibration.magnitudeRange(1,2).*argScale);
    
         lsqOptions = optimoptions('lsqnonlin', ...
                          'Algorithm','levenberg-marquardt',...
                          'MaxFunctionEvaluations', 10000, ...
                          'FunctionTolerance',1e-8,...
                          'MaxIterations',2000,...
                          'StepTolerance',1e-8,...
                          'OptimalityTolerance',1e-6,...
                          'FiniteDifferenceType','central');         
         lambdaVec = [0];

         for idxLoop=1:1:length(lambdaVec)
           objScale=1;
           spectrumError = calcWavePowerSpectrumError(...
                              x0,fcnWave,...
                              configVibration,...
                              objScale,...
                              lambdaVec(idxLoop));
      
           objScale = sqrt(mean(spectrumError.^2));
      
           fcnWaveError = @(arg)calcWavePowerSpectrumError(...
                                arg,fcnWave,...
                                configVibration,...
                                objScale,...
                                lambdaVec(idxLoop));

           [x1,resnorm,residual,exitflag] = ...
             lsqnonlin(fcnWaveError,x0,lb,ub,lsqOptions);
  
  
           x0=x1;

         end

          i0=1;
          i1=max(indexArg);
          
          vibrationMagnitude= x1(i0:i1,1)./argScale(1,1);
   
          [timeVec,...
          signalVec,...
          stochasticFunctions,...
          numberOfStochasticWaveCommands] = ...
            createSineWavePattern610A_V1(...
                      configVibration,...
                      configVibration.frequencyRange,...
                      vibrationMagnitude,...
                      configVibration.waitTimeRange(1,1),...
                      randomNumberGeneratorConfig,...
                      functionOptions,...
                      auroraConfig);          
      end

    otherwise
        assert(0,['Error: no signal generator has been written for ',...
                    controlFunctionName]);
end

stochasticWave.signal = ...
    analyzeSignalSpectrum(timeVec, signalVec,configVibration);

% The wave requires half the number of commands as time 
% entries because the 0-hold length changes are not written to file

fprintf('\t%i\tNumber of perturbation commands\n',...
        numberOfStochasticWaveCommands);

stochasticWave.config = configVibration;
stochasticWave.controlFunctions = stochasticFunctions;


%%
% Get the conditioning vibration vector
%
% During pilot experiments we noticed that the output force of the
% fiber would drop as soon as any vibration was introduced. This
% lead to a non-stationary change in force. Here we apply a constant
% square wave signal to the fiber so that its force drops. Then after
% a quiesent period we apply the perturbation. 
%%





configConstant=configVibration;
configConstant.points = round(configVibration.points/4);
configConstant.duration = ...
  (configConstant.points/auroraConfig.analogToDigitalSampleRateHz) ...
  -2*configConstant.paddingDuration;

configConstant.holdRange = [1,1].*mean(configVibration.holdRange);

constantHoldVector = ones(configConstant.points,1)...
                   .*mean(configVibration.holdRange);

constantFrequencyVector = ones(configConstant.points,1)...
                   .*configVibration.probe.frequencyHz;
constantFrequencyVector = round(constantFrequencyVector);


constantVelocityVector = ones(configConstant.points,1)...
                   .*mean(configVibration.normSpeedRange);

constantMagnitudeVector = ones(configConstant.points,1)...
                   .*configVibration.probe.magnitude;

constantWaitVector = ones(configConstant.points,1)...
                   .*mean(configVibration.waitTimeRange);


switch controlFunctionName
    case 'Step'
      timeStart     = 0;
      timeEnd       = (configVibration.points/configVibration.frequencyHz);
      fcnMeanLength = @(arg)interp1([timeStart,timeEnd]',[0,0],arg);

      [timeVec,...
       signalVec,...
       preconditionFunctions,...
       numberOfPreconditioningWaveCommands]  = ...
        createStepSineWavePattern610A(...
            fcnMeanLength,...
            configVibration,...
            constantFrequencyVector(1,1),...
            constantMagnitudeVector(1,1),...
            functionOptions,...
            auroraConfig);
    case 'Ramp'
    
        if(randomVecA(configConstant.points,1)>(0.5*(diff(configVibration.holdRange))))
            signOfFirstChange=-1;
        end        
    
                
        [timeVec, ...
        signalVec, ...
        preconditionFunctions,...
        numberOfPreconditioningWaveCommands] = ...
        createSquareWavePattern610A(configConstant,...
                                   constantHoldVector,...
                                   constantVelocityVector,...
                                   1,...
                                   functionOptions,...
                                   auroraConfig);
    case 'Sine Wave'
      randomNumberGeneratorConfig.type='twister';
      randomNumberGeneratorConfig.seed=3;

      [timeVec,...
        signalVec,...
        preconditionFunctions,...
        numberOfPreconditioningWaveCommands] = ...
        createSineWavePattern610A_V1(configConstant,...
                                constantFrequencyVector(1,1),...
                                constantMagnitudeVector(1,1),...
                                constantWaitVector(1,1),...
                                randomNumberGeneratorConfig,...
                                functionOptions,...
                                auroraConfig);        
       here=1;
    otherwise
        assert(0,['Error: no signal generator has been written for ',...
                    controlFunctionName]);
end

preConditioningWave.signal = ...
    analyzeSignalSpectrum( timeVec, signalVec,configConstant);

preConditioningWave.controlFunctions = preconditionFunctions;
preConditioningWave.config = configConstant;

if(verbose==1)
    fprintf('\t%i\tNumber of pre-conditioning commands\n',...
            numberOfPreconditioningWaveCommands);
end


totalNumberOfSystemIdCommands = ...
    numberOfStochasticWaveCommands ...
   +numberOfPreconditioningWaveCommands;

assert(totalNumberOfSystemIdCommands < auroraConfig.maximumNumberOfCommands,...
    'Error: System id exceeded the maximum number of commands');

if(verbose==1)
    fprintf('\t%i\tNumber of commands remaining\n',...
         (auroraConfig.maximumNumberOfCommands...
         -totalNumberOfSystemIdCommands));
end
%%
%
%%
if(isempty(figPerturbation)==0)
        
    subplotPanel = perturbationPlotConfig.subplot;
    plotConfig   = perturbationPlotConfig.config;

    figure(figPerturbation);
    subplot('Position',reshape(subplotPanel(1,1,:),1,4));
        plot((preConditioningWave.signal.t-max(preConditioningWave.signal.t)),...
             preConditioningWave.signal.x,'-','Color',[1,1,1].*0.75,...
             'LineWidth',0.25,'DisplayName','Pre-conditioning');
        hold on;
        plot(stochasticWave.signal.t,...
             stochasticWave.signal.x,'-k',...
             'LineWidth',0.25,'DisplayName','x(t)');
        axis tight;
        xlabel('Time (s)');
        ylabel(['Length (', auroraConfig.defaultLengthUnit,')']);
        title('Conditioning and perturbation waveform');
        legend('Location','NorthWest');
        %legend boxoff;
        box off;
        hold on;

    figure(figPerturbation);
    subplot('Position',reshape(subplotPanel(2,1,:),1,4));

    plot((preConditioningWave.signal.t-max(preConditioningWave.signal.t)),...
         preConditioningWave.signal.xdot,'-','Color',[1,1,1].*0.75,...
         'LineWidth',0.25,'DisplayName','Pre-conditioning');
    hold on;
    plot(stochasticWave.signal.t,...
         stochasticWave.signal.xdot,'-k',...
         'LineWidth',0.25,'DisplayName','xdot(t)');
    axis tight;
    xlabel('Time (s)');
    ylabel(['Velocity (', auroraConfig.defaultLengthUnit,'/s)']);
    title('Conditioning and perturbation waveform');
    legend('Location','NorthWest');
    %legend boxoff;
    box off;
    hold on;    
    
    
    figure(figPerturbation);
    subplot('Position',reshape(subplotPanel(3,1,:),1,4));
        normPower=stochasticWave.signal.p(1:pointsHalf,1)...
               ./max(stochasticWave.signal.p(1:pointsHalf,1));
        plot(stochasticWave.signal.freqHz(1:pointsHalf,1),...
             normPower,'-','Color',[1,1,1].*0.75,...
             'LineWidth',0.25,'DisplayName','pxx(x(t))');
        hold on;
    
        meanFreq = sum(stochasticWave.signal.fwHz.*stochasticWave.signal.pw) ...
                  ./sum(stochasticWave.signal.pw);
        [valPeak,idxPeak] = max(stochasticWave.signal.pw);
        
        pwN = stochasticWave.signal.pw./max(stochasticWave.signal.pw);
    
        plot(stochasticWave.signal.fwHz,...
             pwN,'-k',...
             'LineWidth',0.25,'DisplayName','pwelch(x(t))');
        hold on;
        plot(stochasticWave.signal.fwHz(idxPeak),pwN(idxPeak),'o',...
            'MarkerFaceColor',[0,0,0],...
            'HandleVisibility','off');        
        hold on;
        text(stochasticWave.signal.fwHz(idxPeak)*1.05,pwN(idxPeak),...
             sprintf('Peak: %1.2f Hz',stochasticWave.signal.fwHz(idxPeak)),...
             'HorizontalAlignment','left',...
             'VerticalAlignment','top');
        hold on;
        plot([1;1].*meanFreq,[0;0.5],'-','Color',[1,1,1],...
             'LineWidth',2,...
             'HandleVisibility','off');
        hold on;
        plot([1;1].*meanFreq,[0;0.5],'-','Color',[0,0,1],...
             'HandleVisibility','off');
        hold on;
        text(meanFreq*1.05,0.5,...
             sprintf('Mean: %1.2f Hz',meanFreq),...
             'HorizontalAlignment','left',...
             'VerticalAlignment','middle');
        hold on;
    
        legend('Location','NorthEast');
        %legend boxoff;
        axis tight;
        xlim([0, configVibration.frequencyRange(1,2)*1.5]);
        box off;
        xlabel('Frequency (Hz)');
        ylabel('Norm. Power');
        title('Peturbation power spectrum');  
       


    configPlotExporter(figPerturbation,plotConfig);
end

