function success = createActiveLengthRampSeriesTrial610A(...
                        lengthRampSeries,...
                        trialFileFullPath,...
                        trialBlockLabelFullPath,...
                        auroraConfig)


assert(     size(lengthRampSeries.normLengths,1)==1 ...
        &&  size(lengthRampSeries.normLengths,2)==3,...
        "Error: lengthRampSeries.normLengths should be 1 x 3");


assert(     size(lengthRampSeries.lengths,1)==1 ...
        &&  size(lengthRampSeries.lengths,2)==3,...
        "Error: lengthRampSeries.normLengths should be 1 x 3");


%
% Make the program file
%
fid = fopen(trialFileFullPath,'w');
programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFullPath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);


%%
%Move the specimen from a length of 0 to its starting length
%%

waitTime                    = 0;
flag_printMetaDataToFile    = 1;

lengthChangeOptions             = lengthRampSeries.options;
lengthChangeOptions(1).value    = lengthRampSeries.lengths(1,1);
lengthChangeOptions(2).value    = auroraConfig.prePostPositioningDuration;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthChangeOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

%
% Stimulate the muscle
%
waitTime = 0;
stretchShorteningDuration = 0;
for i=1:1:length(lengthRampSeries)
    stretchShorteningDuration = ...
        stretchShorteningDuration ...
        + sum(lengthRampSeries(i).duration);
end

stimulationDurationInS = ...
    auroraConfig.timeToReachMaxActivation ...
    + stretchShorteningDuration ...
    + auroraConfig.activationPaddingTime;


flag_printMetaDataToFile = 1;
programMetaData = ...
    writeStimulusTetanusBlock610A(...
        fid,...
        waitTime, ...
        stimulationDurationInS,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

waitTimeForBlock = auroraConfig.timeToReachMaxActivation;

stimulationEndTime = programMetaData.controlFunction.endTime;

%
% Stretch-shorten cycle
%
programMetaData = ...
    writeLengthRampBlock610A(...
        fid, ...
        waitTimeForBlock,...
        lengthRampSeries.wait(1,2:end)',...
        lengthRampSeries.lengths(1,2:end)',...
        lengthRampSeries.duration(1,:)',...
        lengthRampSeries.options,...
        auroraConfig,...
        programMetaData,...
        lengthRampSeries.type,...
        flag_printMetaDataToFile);   
waitTimeForBlock=0;

endTimeBlock = programMetaData.controlFunction.endTime;

waitTime= ((stimulationEndTime-endTimeBlock) ...
           + auroraConfig.restTimeBetweenActivations);

%%
%Move the specimen to its starting length of zero
%%

waitTime                    = auroraConfig.passive.recoveryTime;

flag_printMetaDataToFile    = 1;

lengthChangeOptions             = lengthRampSeries.options;
lengthChangeOptions(1).value    = lengthRampSeries.endLength;
lengthChangeOptions(2).value    = auroraConfig.prePostPositioningDuration;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Ramp',...
            lengthChangeOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

%%
% Write the closing block
%%

waitTime = auroraConfig.stop.waitTime;

programMetaData = ...
    writeClosingBlock610A(...
        fid,...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');

fclose(fid);
fclose(programMetaData.labelFileHandle);