function success = createActivePassiveProbeTrial610A_01(...
                          startEndLength,...
                          trialFileNameNoExt,...                                     
                          auroraConfig,...
                          expConfig,...
                          expFolders,...
                          flag_isASequence)


    fid = fopen(fullfile(expFolders.rootFolderPath,...
                         expFolders.protocolFolderName,...
                         [trialFileNameNoExt,'.dpf']),'w');
   
    
    trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                      expFolders.blockLabelsFolderName,...
                                      [trialFileNameNoExt,'.csv']);
    
    programMetaData = getEmptyProgramMetaDataStruct610A_01(...
                          startEndLength,...
                          trialBlockLabelFilePath);

    programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);
    

    if(flag_isASequence==0)
      jsonMetaData = struct('data',[],'protocol',[],...
                            'segments',[],'experiment',[]);
        
      jsonMetaData.data.file = {expFolders.dataFolderName, ...
                                [trialFileNameNoExt,'.ddf']};
      jsonMetaData.data.sha256 = "";
      
      jsonMetaData.protocol.file = {expFolders.protocolFolderName, ...
                                [trialFileNameNoExt,'.dpf']};
      jsonMetaData.protocol.sha256 = "";
    else
      jsonMetaData = struct('segments',[],'experiment',[]); 
    end    

    flag_printMetaDataToFile=1;

    segmentMetaDataArray=[];

    %
    % Ramp to startEndLength
    %
    lengthRampOptions = ...
      getCommandFunctionOptions610A('Ramp','Length Out',...
                                     auroraConfig);
    
    positioningDuration = abs(startEndLength)...
                          /expConfig.positioning.rampSpeedInMMPS;
    positioningDuration = max(positioningDuration,...
                              expConfig.positioning.minimumRampTime);
    
    lengthRampOptions(1).value = startEndLength; 
    lengthRampOptions(2).value = positioningDuration;
    
    startTime = programMetaData.nextStartTime;
    endTime = startTime+lengthRampOptions(2).value;
    
    [programMetaData,fcnMetaData]...
        = writeControlFunction610A_01(...
                fid,...
                0,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
    
    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];
    
    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data');  

    %
    % Passive ramp probe
    %
    lengthRampOptions = ...
      getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

    waitTime = 1;
    passiveRampDuration = ...
          abs(expConfig.probe.passiveLength-startEndLength)...
          /expConfig.probe.velocity;


    lengthRampOptions(1).value = expConfig.probe.passiveLength; 
    lengthRampOptions(2).value = passiveRampDuration;
    
    startTime = programMetaData.nextStartTime ...
              + waitTime;
    endTime = startTime+passiveRampDuration;

    [programMetaData,fcnMetaData] ...
        = writeControlFunction610A_01(...
                fid,...
                waitTime,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
  
    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];
    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data');

    %
    % Ramp to 0
    %
    lengthRampOptions = ...
      getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

    lengthRampOptions(1).value = startEndLength; 
    lengthRampOptions(2).value = passiveRampDuration;
    
    startTime = programMetaData.nextStartTime+waitTime;
    endTime = startTime+passiveRampDuration;

    [programMetaData,fcnMetaData] ...
        = writeControlFunction610A_01(...
                fid,...
                waitTime,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
  
    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data');   


    %
    % Isometric contraction
    %
    tetanusDuration  =expConfig.tetanus.timeToReachMaxActivation ...
                     +expConfig.tetanus.durationExtension;

    stimulusTetanusOptions = getCommandFunctionOptions610A(...
                              'Stimulus-Tetanus','Stimulator',auroraConfig);
    
    stimulusTetanusOptions(1).value=expConfig.tetanus.initialDelay;
    stimulusTetanusOptions(2).value=expConfig.tetanus.pulseFrequency;
    stimulusTetanusOptions(3).value=expConfig.tetanus.pulseWidth;
    stimulusTetanusOptions(4).value=tetanusDuration;

    startTime = programMetaData.nextStartTime+expConfig.timing.waitTime;
    endTime   = startTime ...
                +expConfig.tetanus.initialDelay ...
                +tetanusDuration;
    
       
    flag_printMetaDataToFile=1;
    [programMetaData,fcnMetaData] = ...
      writeControlFunction610A_01(...
              fid,...
              expConfig.timing.waitTime,...
              'Stimulus-Tetanus',...
              stimulusTetanusOptions,...
              auroraConfig,...                
              programMetaData,...
              flag_printMetaDataToFile); 

    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];
    
    endTimeError = endTime - programMetaData.controlFunction.endTime;
    assert(abs(endTimeError)<1e-3,...
        'Error: end time differs from the meta data'); 

    tetanusCommandTime = ...
      programMetaData.controlFunction.endTime ...
      -programMetaData.controlFunction.startTime;
  
    %
    % Close the trial
    %
    disableOptions = getCommandFunctionOptions610A('Stop','',auroraConfig);
    
    stopWaitTime = expConfig.timing.stopWaitTime;
    
    [programMetaData, fcnMetaData] ...
        = writeControlFunction610A_01(...
                fid,...
                stopWaitTime,...
                'Stop',...
                disableOptions,...              
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile);
    
    segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];
    
    fclose(fid);
    fclose(programMetaData.labelFileHandle);
    
    assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
        'Error: maximumNumberOfCommandsExceeded');  

    %
    % Write the json files
    %

    experimentTitle = ...
      sprintf('Active-Passive Probe (0mm-%1.1f-0mm)',...
              expConfig.probe.passiveLength);
    experimentTags = {'probe'};
   
    success = writeMetaDataStructure610A(...
                              segmentMetaDataArray,...
                              expConfig,...
                              experimentTitle,...
                              experimentTags,...
                              trialFileNameNoExt,...
                              expFolders,...                          
                              flag_isASequence);
    
    
    
    success = writeTimeSeriesDataAndImages610A(...
                programMetaData,...
                auroraConfig,...
                trialFileNameNoExt,...
                expFolders);