function success = createRampRecoveryTrial610A(...
                    lengthRampOptions,...  
                    trialFileNameNoExt,...                            
                    auroraConfig,...
                    expConfig,...
                    expFolders,...
                    flag_isASequence)

flag_printMetaDataToFile=1;

fid = fopen(fullfile(expFolders.rootFolderPath,...
                     expFolders.protocolFolderName,...
                     [trialFileNameNoExt,'.dpf']),'w');

trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                  expFolders.blockLabelsFolderName,...
                                  [trialFileNameNoExt,'.csv']);

programMetaData = getEmptyProgramMetaDataStruct(trialBlockLabelFilePath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

if(flag_isASequence==0)
  jsonMetaData = struct('data',[],'protocol',[],...
                        'segments',[],'experiment',[]);
    
  jsonMetaData.data.file = {expFolders.dataFolderName, ...
                            [trialFileNameNoExt,'.ddf']};
  jsonMetaData.data.sha256 = "";
  
  jsonMetaData.protocol.file = {expFolders.protocolFolderName, ...
                            [trialFileNameNoExt,'.dpf']};
  jsonMetaData.protocol.sha256 = "";
else
  jsonMetaData = struct('segments',[],'experiment',[]); 
end



mdFieldNames = getMetaDataFieldNames610A(auroraConfig);
timeFieldName = mdFieldNames.time;
cyclesFieldName =mdFieldNames.cycles;
frequencyFieldName = mdFieldNames.frequency;
amplitudeFieldName = mdFieldNames.amplitude; 
lengthFieldName = mdFieldNames.length;

% Sine wave
segmentMetaDataArray(2) = ...
    struct('type','',timeFieldName,[0,0],'meta_data',[]);

%
% Ramp
%

idxSeg=1;

startTime = programMetaData.nextStartTime+expConfig.ramp.waitTime;
endTime   = startTime + lengthRampOptions(2).value;

segmentMetaDataArray(idxSeg).type = 'Ramp';
segmentMetaDataArray(idxSeg).(timeFieldName) = [startTime,endTime];
segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
segmentMetaDataArray(idxSeg).meta_data.channel=lengthRampOptions(1).port;
segmentMetaDataArray(idxSeg).meta_data.(lengthFieldName)=lengthRampOptions(1).value;
segmentMetaDataArray(idxSeg).meta_data.(timeFieldName)=lengthRampOptions(2).value;

programMetaData ...
    = writeControlFunction610A(...
            fid,...
            expConfig.ramp.waitTime,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');

%
% Sine wave
%
idxSeg=idxSeg+1;

lengthSineOptions = getCommandFunctionOptions610A(...
                      'Sine Wave','Length Out',auroraConfig);
lengthSineOptions(1).value = expConfig.sineWave.frequency;
lengthSineOptions(2).value = expConfig.sineWave.amplitude;
lengthSineOptions(3).value = expConfig.sineWave.cycles;


sineTime = (expConfig.sineWave.cycles ...
           /expConfig.sineWave.frequency);

startTime = programMetaData.nextStartTime ...
           +expConfig.sineWave.waitTime;

endTime = startTime + sineTime;

segmentMetaDataArray(idxSeg).type = 'Sine Wave';
segmentMetaDataArray(idxSeg).(timeFieldName) = [startTime,endTime];
segmentMetaDataArray(idxSeg).meta_data.is_active = 0;
  segmentMetaDataArray(idxSeg).meta_data.channel=lengthSineOptions(1).port;
segmentMetaDataArray(idxSeg).meta_data.(frequencyFieldName)= ...
  lengthSineOptions(1).value;    
segmentMetaDataArray(idxSeg).meta_data.(amplitudeFieldName)= ...
  lengthSineOptions(2).value;
segmentMetaDataArray(idxSeg).meta_data.(cyclesFieldName)= ...
  lengthSineOptions(3).value;    

%Write the wave
programMetaData = writeControlFunction610A(...
                    fid,...
                    expConfig.sineWave.waitTime,...
                    'Sine Wave',...
                    lengthSineOptions,...
                    auroraConfig,...                
                    programMetaData,...
                    flag_printMetaDataToFile); 

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');

programMetaData = ...
  writeClosingBlock610A(...
      fid,...
      expConfig.stopWaitTime,...
      auroraConfig,...
      programMetaData,...
      flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');

trialTitleStr = ...
  sprintf("Passive Ramp (%1.1fmm) Sine Wave (%1.1fHz %1.1fmm %1.1f cycles)",...
                   lengthRampOptions(1).value,...
                   expConfig.sineWave.frequency,...
                   expConfig.sineWave.amplitude,...
                   expConfig.sineWave.cycles);
tags = {'ramp-recovery'};  

jsonMetaData.segments = segmentMetaDataArray;
jsonMetaData.experiment.title = trialTitleStr;
jsonMetaData.experiment.tags = tags;

jsonMetaDataEncoded = jsonencode(jsonMetaData);

if(flag_isASequence==1)
  fidJson = fopen(fullfile(expFolders.rootFolderPath,...
                           expFolders.sequenceMetaData,...
                           [trialFileNameNoExt,'.json']),'w');
else
  fidJson = fopen(fullfile(expFolders.rootFolderPath,...
                             [trialFileNameNoExt,'.json']),'w');
end

fprintf(fidJson,jsonMetaDataEncoded);
fclose(fidJson);

fclose(fid);
fclose(programMetaData.labelFileHandle);

