function success = createRampRecoveryTrial610A_01(...
                    nominalLength,...
                    trialFileNameNoExt,...                            
                    auroraConfig,...
                    expConfig,...
                    expFolders,...
                    flag_isASequence)

flag_printMetaDataToFile=1;




%assert(abs(lengthRampOptions(1).value)<1e-6,...
%       'Error: the ramp recovery trial must begin and end at 0');

fid = fopen(fullfile(expFolders.rootFolderPath,...
                     expFolders.protocolFolderName,...
                     [trialFileNameNoExt,'.dpf']),'w');

trialBlockLabelFilePath = fullfile(expFolders.rootFolderPath,...
                                  expFolders.blockLabelsFolderName,...
                                  [trialFileNameNoExt,'.csv']);

programMetaData = getEmptyProgramMetaDataStruct610A_01(...
                      nominalLength,...
                      trialBlockLabelFilePath);
programMetaData = writePreamble610A(fid,auroraConfig,programMetaData);

if(flag_isASequence==0)
  jsonMetaData = struct('data',[],'protocol',[],...
                        'segments',[],'experiment',[]);
    
  jsonMetaData.data.file = {expFolders.dataFolderName, ...
                            [trialFileNameNoExt,'.ddf']};
  jsonMetaData.data.sha256 = "";
  
  jsonMetaData.protocol.file = {expFolders.protocolFolderName, ...
                            [trialFileNameNoExt,'.dpf']};
  jsonMetaData.protocol.sha256 = "";
else
  jsonMetaData = struct('segments',[],'experiment',[]); 
end




segmentMetaDataArray=[];

%
% Ramp to nominalLength
%
lengthRampOptions = ...
  getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

lengthRampOptions(1).value = nominalLength; 
lengthRampOptions(2).value = 1;

startTime = programMetaData.nextStartTime;
endTime = startTime+lengthRampOptions(2).value;

[programMetaData,fcnMetaData]...
    = writeControlFunction610A_01(...
            fid,...
            0,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');       

%
% Sine wave
%

lengthSineOptions = getCommandFunctionOptions610A(...
                      'Sine Wave','Length Out',auroraConfig);
lengthSineOptions(1).value = expConfig.sineWave.frequency;
lengthSineOptions(2).value = expConfig.sineWave.amplitude;
lengthSineOptions(3).value = expConfig.sineWave.cycles;


sineTime = (expConfig.sineWave.cycles ...
           /expConfig.sineWave.frequency);

startTime = programMetaData.nextStartTime ...
           +expConfig.sineWave.waitTime;

endTime = startTime + sineTime;

%Write the wave
[programMetaData, fcnMetaData] ...
  = writeControlFunction610A_01(...
                    fid,...
                    expConfig.sineWave.waitTime,...
                    'Sine Wave',...
                    lengthSineOptions,...
                    auroraConfig,...                
                    programMetaData,...
                    flag_printMetaDataToFile); 

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');
segmentMetaDataArray = [segmentMetaDataArray,fcnMetaData];

%
% Ramp to nominalLength
%
lengthRampOptions = ...
  getCommandFunctionOptions610A('Ramp','Length Out',auroraConfig);

lengthRampOptions(1).value = nominalLength; 
lengthRampOptions(2).value = 1;

startTime = programMetaData.nextStartTime;
endTime = startTime+lengthRampOptions(2).value;

[programMetaData,fcnMetaData]...
    = writeControlFunction610A_01(...
            fid,...
            0,...
            'Ramp',...
            lengthRampOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

segmentMetaDataArray=[segmentMetaDataArray,fcnMetaData];

endTimeError = endTime - programMetaData.controlFunction.endTime;
assert(abs(endTimeError)<1e-3,...
    'Error: end time differs from the meta data');    

%
% Close the trial 
%


programMetaData = ...
  writeClosingBlock610A(...
      fid,...
      expConfig.stopWaitTime,...
      auroraConfig,...
      programMetaData,...
      flag_printMetaDataToFile);

success = 1;
assert(programMetaData.lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');
fclose(fid);
fclose(programMetaData.labelFileHandle);


experimentTitle = ...
  sprintf("Passive Ramp (%1.1fmm) Sine Wave (%1.1fHz %1.1fmm %1.1f cycles)",...
                   lengthRampOptions(1).value,...
                   expConfig.sineWave.frequency,...
                   expConfig.sineWave.amplitude,...
                   expConfig.sineWave.cycles);
experimentTags = {'ramp-recovery'};  

success = writeMetaDataStructure610A(...
            segmentMetaDataArray,...
            expConfig,...
            experimentTitle,...
            experimentTags,...
            trialFileNameNoExt,...
            expFolders,...                          
            flag_isASequence);

success = writeTimeSeriesDataAndImages610A(...
            programMetaData,...
            auroraConfig,...
            trialFileNameNoExt,...
            expFolders);


