function [timeVec,...
          signalVec,...
          controlFunctions,...
          lineCount] =...
          createStepWavePattern610A_FcnWrapper(...
                          arg,...
                          indexArg,...
                          fcnMeanLength,...
                          config,...                          
                          frequencyVector,...
                          amplitudeVector,...
                          functionOption,...
                          auroraConfig,...
                          argScale)

argVec = amplitudeVector;
argVec(indexArg) = arg./argScale;

[timeVec,...
 signalVec,...
 controlFunctions,...
 lineCount] =  createStepSineWavePattern610A(...
                                fcnMeanLength,...
                                config,...
                                frequencyVector,...
                                argVec,...
                                functionOption,...
                                auroraConfig);