function programMetaData = ...
            writeStimulusTetanusBlock610A(...
                fid, ...
                waitTime,...
                durationInS, ...
                auroraConfig,...
                programMetaData,...
                flag_printMetaDataToFile)

assert(strcmp(auroraConfig.defaultTimeUnit,'s'),...
    'Error: auroraConfig.defaultTimeUnit must be s');

assert(durationInS <= auroraConfig.stimulation.maxDuration,...
       sprintf(['Error: requested a stimulation (%1.2f) duration ',...
        'greater than auroraConfig.stimulation.maxDuration (%1.2f)'],...
        durationInS,auroraConfig.stimulation.maxDuration));

stimOptions = getCommandFunctionOptions610A(...
                'Stimulus-Tetanus','Stimulator',auroraConfig);

stimOptions(1).value = 0;
stimOptions(2).value = auroraConfig.stimulation.frequencyHz;
stimOptions(3).value = auroraConfig.stimulation.pulseWidthMs;
stimOptions(4).value = durationInS;


programMetaData ...
    = writeControlFunction610A(...
            fid,...
            waitTime,...
            'Stimulus-Tetanus',...
            stimOptions,...
            auroraConfig,...
            programMetaData,...
            flag_printMetaDataToFile);

