function [programMetaData,fcnMetaData] = ...
    writeClosingBlock610A_01(...
        fid, ...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile)

disableOptions = getCommandFunctionOptions610A('Stop','',auroraConfig);

[programMetaData,fcnMetaData]...
     = writeControlFunction610A_01(...
        fid,...
        waitTime,...
        'Stop',...
        disableOptions,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


