function [programMetaData,fcnMetaDataArray] ...
            = writeLengthRampBlock610A_01( ...
                fid,...
                waitTimeForBlock,...
                waitTimeVector,...
                lengthVector,...
                durationVector,...
                lengthRampOptions, ...
                auroraConfig,...
                programMetaData,...
                blockLabelName,...
                flag_printMetaDataToFile)

assert(length(waitTimeVector)==length(lengthVector) ...
    && length(waitTimeVector)==length(durationVector),...
    ['Error: waitTimeVector, lengthVector, and',...
     ' durationVector have different sizes']);

flag_addControlFunctionMetaData = 0;

blockStartTime      = programMetaData.nextStartTime ...
                     + waitTimeForBlock;
                    
blockLineCountStart = programMetaData.lineCount;

fcnMetaDataArray=[];

sampleFrequencyHz = auroraConfig.analogToDigitalSampleRateHz;
dt = 1/sampleFrequencyHz;

for i=1:1:length(waitTimeVector)

    lengthRampOptions(1).value = lengthVector(i,1);
    lengthRampOptions(2).value = durationVector(i,1);
    waitTime = waitTimeVector(i,1);

    if(i==1)
      waitTime=waitTime+waitTimeForBlock;
    end
    if(~(waitTime >= programMetaData.smallestNextWaitTime))
      here=1;
    end    

    if(waitTime>dt)
      waitTime=waitTime-dt;
    end

    [programMetaData,fcnMetaData]...
        = writeControlFunction610A_01(...
                fid,...
                waitTime,...
                'Ramp',...
                lengthRampOptions,...
                auroraConfig,...
                programMetaData,...
                flag_addControlFunctionMetaData);
    fcnMetaDataArray=[fcnMetaDataArray,fcnMetaData];

end

blockLineCountEnd = programMetaData.lineCount;
blockEndTime      = programMetaData.controlFunction.endTime;
nextStartTime     = programMetaData.nextStartTime;


assert(abs(blockLineCountEnd-blockLineCountStart)...
        == length(lengthVector),...
       'Error: line count mis-match');


if(flag_printMetaDataToFile==1)


    fprintf(programMetaData.labelFileHandle,'%s,%1.6f,%1.6f\n',...
        blockLabelName,...
        (blockStartTime),...
        (blockEndTime));
end


