function programMetaData = ...
    writeClosingBlock610A(...
        fid, ...
        waitTime,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile)

disableOptions = getCommandFunctionOptions610A('Stop','',auroraConfig);

programMetaData...
     = writeControlFunction610A(...
        fid,...
        waitTime,...
        'Stop',...
        disableOptions,...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);


