function success = writeMetaDataStructure610A(...
                          segmentMetaDataArray,...
                          expConfig,...
                          experimentTitle,...
                          experimentTags,...
                          trialFileNameNoExt,...
                          expFolders,...
                          flag_isASequence)

jsonMetaData = getTrialMetaDataStruct610A(...
    trialFileNameNoExt, expFolders, flag_isASequence);

jsonMetaData.segments = segmentMetaDataArray;
jsonMetaData.experiment.title = experimentTitle;
jsonMetaData.experiment.manually_measured_temperature_C ...
  = expConfig.muscle.temperatureC;
jsonMetaData.experiment.tags = experimentTags;

jsonMetaDataEncoded = jsonencode(jsonMetaData);

if(flag_isASequence==0)
  fidJson = fopen(fullfile(expFolders.rootFolderPath,...
                           [trialFileNameNoExt,'.json']),'w');
else                     
  fidJson = fopen(fullfile(expFolders.rootFolderPath,...
                           expFolders.sequenceMetaData,...
                           [trialFileNameNoExt,'.json']),'w');

end
fprintf(fidJson,jsonMetaDataEncoded);
fclose(fidJson);

success=1;