function [programMetaData] ...
            = writeLengthStepBlock610A( ...
                fid,...
                waitTimeForBlock,...
                waitTimeVector,...
                lengthVector,...
                lengthStepOptions, ...
                auroraConfig,...
                programMetaData,...
                blockLabelName,...
                flag_printMetaDataToFile)

assert(length(waitTimeVector)==length(lengthVector),...
    ['Error: waitTimeVector and lengthVector',...
     ' have different sizes']);

flag_addControlFunctionMetaData = 0;

blockStartTime      = programMetaData.nextStartTime ...
                     + waitTimeForBlock;
                    
blockLineCountStart = programMetaData.lineCount;



for i=1:1:length(waitTimeVector)

    lengthStepOptions(1).value  = lengthVector(i,1);
    waitTime                    = waitTimeVector(i,1);

    if(i==1)
      waitTime=waitTime+waitTimeForBlock;
    end
    if(~(waitTime >= programMetaData.smallestNextWaitTime))
      here=1;
    end    

    programMetaData ...
        = writeControlFunction610A(...
                fid,...
                waitTime,...
                'Step',...
                lengthStepOptions,...
                auroraConfig,...
                programMetaData,...
                flag_addControlFunctionMetaData);

end

blockLineCountEnd = programMetaData.lineCount;
blockEndTime      = programMetaData.controlFunction.endTime;
nextStartTime     = programMetaData.nextStartTime;


assert(abs(blockLineCountEnd-blockLineCountStart)...
        == length(lengthVector),...
       'Error: line count mis-match');


if(flag_printMetaDataToFile==1)


    fprintf(programMetaData.labelFileHandle,'%s,%1.6f,%1.6f\n',...
        blockLabelName,...
        (blockStartTime),...
        (blockEndTime));
end


