function [programMetaData] ...
            = writeLengthSineBlock610A( ...
                fid,...
                waitTimeForBlock,...
                waitTimeVector,...
                frequencyVector,...
                lengthVector,...
                durationVector,...
                lengthSineOptions,...
                auroraConfig,...
                programMetaData,...                
                blockLabelName,...
                flag_printMetaDataToFile)



flag_addControlFunctionMetaData = 0;

blockStartTime      = programMetaData.nextStartTime ...
                    + waitTimeForBlock;
blockLineCountStart = programMetaData.lineCount;


for i=1:1:length(waitTimeVector)


    lengthSineOptions(1).value = frequencyVector(i,1);
    lengthSineOptions(2).value = lengthVector(i,1);
    lengthSineOptions(3).value = durationVector(i,1);
    waitTime = waitTimeVector(i,1);

    if(i == 1 ) 
        waitTime = waitTime + waitTimeForBlock;
    end

    
    programMetaData...
        = writeControlFunction610A(...
                fid,...
                waitTime,...
                'Sine Wave',...
                lengthSineOptions,...
                auroraConfig,...                
                programMetaData,...
                flag_addControlFunctionMetaData);

    
end

blockLineCountEnd = programMetaData.lineCount;
blockEndTime      = programMetaData.controlFunction.endTime;
nextStartTime     = programMetaData.nextStartTime;

assert(abs(blockLineCountEnd-blockLineCountStart)...
        == length(lengthVector),...
       'Error: line count mis-match');

if(flag_printMetaDataToFile==1)

    fprintf(programMetaData.labelFileHandle,'%s,%1.6f,%1.6f\n',...
        blockLabelName,...
        (blockStartTime),...
        (blockEndTime));

end
