function [] = createLengthRampImpedanceTrial(...
                    isActive,...                    
                    startingLength,...
                    endingLength,...
                    startingPerturbation,...
                    endingPerturbation,...
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...
                    auroraConfig)

