function [  stochasticWave, ...
            preConditioningWave, ...
            figPerturbation] = createPerturbationWave600A(...
                                  controlFunctionName,...
                                  functionOptions,...
                                  configVibration,...
                                  auroraConfig,...
                                  figPerturbation,...
                                  perturbationPlotConfig,...
                                  verbose)
%%
% @return stochasticWave
% A pseudo-random stochastic perturbation signal for use
% in system identification as applied to muscle fibers
%
% @return preConditioningWave
% An isometric fiber's force drops immediately once its length is perturbed
% to a lower value. This makes the system time-variant. To make the 
% response more consistent with an LTI system, here we generate a set of 
% vibrations that can be used prior to the stochastic wave in order to 
% pre-condition it so that its mean force does not drop when the 
% stochastic perturbation is applied.
%
% The other option is to perturb in the force domain, which is possible
% with the Aurora machine.
% 
%%

scaleTime=1;
switch auroraConfig.defaultTimeUnit
    case 's'
        scaleTime=1;
    case 'ms'
        scaleTime=1000;
    otherwise
        assert(0,'Error: Unrecognized time unit');
end

pointsHalf = configVibration.points/2;    

if(verbose==1)
    fprintf('\n\nSystem Identification Perturbation\n');
    fprintf('\t%s\tWaveform\n',controlFunctionName);
end

flag_makePreconditioningWave = 0;

switch controlFunctionName
    case 'Length-Ramp'    
          
        [timeVec,...
            signalVec,...
            stochasticFunctions,...
            numberOfStochasticWaveCommands] =...
            createSquareWavePattern600A(...
                             configVibration,...
                             functionOptions,...
                             auroraConfig,...
                             flag_makePreconditioningWave);
        here=1;
    case 'Length-Sine'

        [timeVec,...
        signalVec,...
        stochasticFunctions,...
        numberOfStochasticWaveCommands] = ...
        createSineWavePattern600A(...
                        configVibration,...
                        functionOptions,...                            
                        auroraConfig,...
                        flag_makePreconditioningWave);
    case 'Length-Arb'

        [timeVec,...
        signalVec,...
        stochasticFunctions,...
        numberOfStochasticWaveCommands] = ...
            createArbitraryWavePattern600A(...
                                'random',...
                                configVibration,...
                                functionOptions,...
                                auroraConfig);        

    otherwise
        assert(0,['Error: no signal generator has been written for ',...
                    controlFunctionName]);
end

stochasticWave.signal = ...
    analyzeSignalSpectrum(timeVec, signalVec,configVibration);

% The wave requires half the number of commands as time 
% entries because the 0-hold length changes are not written to file

fprintf('\t%i\tNumber of perturbation commands\n',...
        numberOfStochasticWaveCommands);

stochasticWave.config           = configVibration;
stochasticWave.controlFunctions = stochasticFunctions;



%%
% Get the conditioning vibration vector
%
% During pilot experiments we noticed that the output force of the
% fiber would drop as soon as any vibration was introduced. This
% lead to a non-stationary change in force. Here we apply a constant
% square wave signal to the fiber so that its force drops. Then after
% a quiesent period we apply the perturbation. 
%%

configConstant=configVibration;
configConstant.points       = round(configVibration.points/4);


flag_makePreconditioningWave = 1;

switch controlFunctionName
    case 'Length-Ramp'  

        configConstant.duration     = ...
            configVibration.duration/4;

        configConstant.lengthRamp.holdRange    = ...
            [1,1].*mean(configVibration.lengthRamp.holdRange);


        [timeVec, ...
         signalVec, ...
         preconditionFunctions,...
         numberOfPreconditioningWaveCommands] = ...
            createSquareWavePattern600A(configConstant,...
                                       functionOptions,...
                                       auroraConfig,...
                                       flag_makePreconditioningWave);
    case 'Length-Sine'
        [timeVec,...
         signalVec,...
         preconditionFunctions,...
         numberOfPreconditioningWaveCommands] = ...
            createSineWavePattern600A(  configConstant,...
                                        functionOptions,...
                                        auroraConfig,...
                                        flag_makePreconditioningWave);        

    case 'Length-Arb'
        %
        % Use the sine wave command to pre-condition the fiber
        %
        timeVec                 = [];
        signalVec               = [];
        preconditionFunctions   = [];
        numberOfPreconditioningWaveCommands = 0;

        disp('Note: There is no preconditioning wave for a Larb wave');
%         [timeVec,...
%          signalVec,...
%          preconditionFunctions,...
%          numberOfPreconditioningWaveCommands] = ...
%             createArbitraryWavePattern600A(...
%                                 'preconditioning',...
%                                 configVibration,...
%                                 functionOptions,...
%                                 auroraConfig);         
    otherwise
        assert(0,['Error: no signal generator has been written for ',...
                    controlFunctionName]);
end

preConditioningWave = [];

if(isempty(timeVec)==0 && isempty(signalVec) == 0)
    preConditioningWave.signal = ...
        analyzeSignalSpectrum( timeVec, signalVec,configConstant);
    
    preConditioningWave.controlFunctions = preconditionFunctions;

   
end

if(verbose==1)
    fprintf('\t%i\tNumber of pre-conditioning commands\n',...
            numberOfPreconditioningWaveCommands);
end 


totalNumberOfSystemIdCommands = ...
    numberOfStochasticWaveCommands ...
   +numberOfPreconditioningWaveCommands;

assert(totalNumberOfSystemIdCommands < auroraConfig.maximumNumberOfCommands,...
    'Error: System id exceeded the maximum number of commands');

if(verbose==1)
    fprintf('\t%i\tNumber of commands remaining\n',...
         (auroraConfig.maximumNumberOfCommands...
         -totalNumberOfSystemIdCommands));
end
%%
%
%%
if(isempty(figPerturbation)==0)
        
    subplotPanel = perturbationPlotConfig.subplot;
    plotConfig   = perturbationPlotConfig.config;

    figure(figPerturbation);
    col = perturbationPlotConfig.column;
    subplot('Position',reshape(subplotPanel(1,col,:),1,4));
%         plot((preConditioningWave.signal.t-max(preConditioningWave.signal.t)),...
%              preConditioningWave.signal.x,'-','Color',[1,1,1].*0.75,...
%              'LineWidth',0.25,'DisplayName','Pre-conditioning');
%         hold on;
        plot(stochasticWave.signal.t,...
             stochasticWave.signal.x,'-k',...
             'LineWidth',0.25,'DisplayName','x(t)');
        yticks([-max(configVibration.magnitude),0,max(configVibration.magnitude)]);
        xlim([min(stochasticWave.signal.t),max(stochasticWave.signal.t)]);
        ylim([-max(configVibration.magnitude).*1.01,...
               max(configVibration.magnitude).*1.01]);

        xlabel('Time (s)');
        ylabel(['Length (', auroraConfig.defaultLengthUnit,')']);
        title('Perturbation waveform');
        legend('Location','NorthWest');
        %legend boxoff;
        box off;
        hold on;

    figure(figPerturbation);
    subplot('Position',reshape(subplotPanel(2,col,:),1,4));

%     plot((preConditioningWave.signal.t-max(preConditioningWave.signal.t)),...
%          preConditioningWave.signal.xdot,'-','Color',[1,1,1].*0.75,...
%          'LineWidth',0.25,'DisplayName','Pre-conditioning');
%     hold on;
    plot(stochasticWave.signal.t,...
         stochasticWave.signal.xdot,'-k',...
         'LineWidth',0.25,'DisplayName','xdot(t)');
    axis tight;
    xlabel('Time (s)');
    ylabel(['Velocity (', auroraConfig.defaultLengthUnit,'/s)']);
    title('Perturbation waveform');
    legend('Location','NorthWest');
    %legend boxoff;
    box off;
    hold on;    
    
    
    figure(figPerturbation);
    subplot('Position',reshape(subplotPanel(3,col,:),1,4));

    idxFreq = find(stochasticWave.signal.freqHz ...
              < (configVibration.frequencyHz*0.5) );


    normPower=stochasticWave.signal.p(1:pointsHalf,1)...
           ./max(stochasticWave.signal.p(1:pointsHalf,1));
    plot(stochasticWave.signal.freqHz(idxFreq,1),...
         normPower(idxFreq,1),'-','Color',[1,1,1].*0.75,...
         'LineWidth',0.25,'DisplayName','pxx(x(t))');
    hold on;

    meanFreq = sum(stochasticWave.signal.fwHz.*stochasticWave.signal.pw) ...
              ./sum(stochasticWave.signal.pw);
    [valPeak,idxPeak] = max(stochasticWave.signal.pw);
    
    pwN = stochasticWave.signal.pw./max(stochasticWave.signal.pw);

    idxFreqW = find(stochasticWave.signal.fwHz...
                    <(configVibration.frequencyHz*0.5));
    plot(stochasticWave.signal.fwHz(idxFreqW,1),...
         pwN(idxFreqW,1),'-k',...
         'LineWidth',0.25,'DisplayName','pwelch(x(t))');
    hold on;
    plot(stochasticWave.signal.fwHz(idxPeak),pwN(idxPeak),'o',...
        'MarkerFaceColor',[0,0,0],...
        'HandleVisibility','off');        
    hold on;
    text(stochasticWave.signal.fwHz(idxPeak)*1.05,pwN(idxPeak),...
         sprintf('Peak: %1.2f Hz',stochasticWave.signal.fwHz(idxPeak)),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','top');
    hold on;
    plot([1;1].*meanFreq,[0;0.5],'-','Color',[1,1,1],...
         'LineWidth',2,...
         'HandleVisibility','off');
    hold on;
    plot([1;1].*meanFreq,[0;0.5],'-','Color',[0,0,1],...
         'HandleVisibility','off');
    hold on;
    text(meanFreq*1.05,0.5,...
         sprintf('Mean: %1.2f Hz',meanFreq),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','middle');
    hold on;

    legend('Location','NorthEast');
    %legend boxoff;
    axis tight;
    box off;
    xlabel('Frequency (Hz)');
    ylabel('Norm. Power');
    title('Peturbation power spectrum');  
       


    configPlotExporter(figPerturbation,plotConfig);
end

