function success = createIsometricImpedanceTrial600A(...
                    stochasticWaveSet,...
                    trialFileFullPath,...
                    trialBlockLabelFullPath,...
                    auroraConfig)



fid = fopen(trialFileFullPath,'w');
fidLabel = fopen(trialBlockLabelFullPath,'w');

lineCount=0;
[startTime,lineCount] = writePreamble600A(fid,lineCount,auroraConfig);

%Perturb
for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Length-Ramp'
            [endTime, lineCount] = ...
                writeLengthRampBlock600A(fid, startTime,...
                            stochasticWaveSet(i).waitDuration,...
                            stochasticWaveSet(i).optionValues(:,1),...
                            stochasticWaveSet(i).optionValues(:,2),...
                            stochasticWaveSet(i).options,...
                            lineCount,...
                            auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);
            startTime = endTime + auroraConfig.postCommandPauseTime;

        case 'Length-Sine'
            [endTime,lineCount] = ...
                writeLengthSineBlock600A(fid, startTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);            
            startTime = endTime + auroraConfig.postCommandPauseTime;
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end


%Activate
[endTime, lineCount] = ...
    writeActivationBlock600A(fid, startTime, 'ms', lineCount, auroraConfig);

endActivation = endTime + auroraConfig.bath.activationDuration;

fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Pre-Activation',startTime,endTime);
fprintf(fidLabel,'%s,%1.6f,%1.6f\n','Activation',endTime,endActivation);

startTime = endActivation;

%Perturb
for i=1:1:length(stochasticWaveSet)
    switch stochasticWaveSet(i).controlFunction
        case 'Length-Ramp'
            [endTime, lineCount] = ...
                writeLengthRampBlock600A(fid, startTime,...
                            stochasticWaveSet(i).waitDuration,...
                            stochasticWaveSet(i).optionValues(:,1),...
                            stochasticWaveSet(i).optionValues(:,2),...
                            stochasticWaveSet(i).options,...
                            lineCount,...
                            auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);
            startTime = endTime + auroraConfig.postCommandPauseTime;

        case 'Length-Sine'
            [endTime,lineCount] = ...
                writeLengthSineBlock600A(fid, startTime,...
                    stochasticWaveSet(i).waitDuration,...
                    stochasticWaveSet(i).optionValues(:,1),...
                    stochasticWaveSet(i).optionValues(:,2),...
                    stochasticWaveSet(i).optionValues(:,3),...
                    stochasticWaveSet(i).options,...
                    lineCount,...
                    auroraConfig);
            fprintf(fidLabel,'%s,%1.6f,%1.6f\n',...
                stochasticWaveSet(i).type,startTime,endTime);            
            startTime = endTime + auroraConfig.postCommandPauseTime;
        otherwise
            assert(0,'Error: Unrecognized controlFunction in the stochasticWaveSet');
    end
end

[endTime, lineCount] = ...
    writeDeactivationBlock600A(fid, startTime, lineCount, auroraConfig);

startTime=endTime+auroraConfig.postCommandPauseTime;

[endTime, lineCount] = ...
    writeClosingBlock600A(fid, startTime, lineCount, auroraConfig);

success = 1;
assert(lineCount < auroraConfig.maximumNumberOfCommands,...
    'Error: maximumNumberOfCommandsExceeded');


fclose(fid);
fclose(fidLabel);
