function [programMetaData,fcnMetaData] = ...
    dataDisable600A(fid,startTime,auroraConfig,programMetaData)

dataDisableOptions = getCommandFunctionOptions600AUpd(...
                        'Data-Disable',auroraConfig,[]);

flag_printMetaDataToCsv   = 1;

[programMetaData,fcnMetaData] = ...
    writeControlFunction600AUpd(...
        fid,startTime,'Data-Disable',dataDisableOptions,{},...
        [],auroraConfig,programMetaData,flag_printMetaDataToCsv);
