function [programMetaData,fcnMetaData] = ...
    dataEnableData600A(fid,startTime,auroraConfig,programMetaData)

dataEnableOptions = getCommandFunctionOptions600AUpd(...
                        'Data-Enable',auroraConfig,[]);

flag_printMetaDataToCsv   = 1;

[programMetaData,fcnMetaData] = ...
    writeControlFunction600AUpd(...
        fid,startTime,'Data-Enable',dataEnableOptions,{},...
        [],auroraConfig,programMetaData,flag_printMetaDataToCsv);
