function fcnMetaData=getEmptySegmentMetaDataStruct600A(...
              controlFunctionName,auroraConfig)

fcnMetaData=struct('type',controlFunctionName, ...
           auroraConfig.labels.time, [nan,nan],...
           'is_recorded',nan,...
           'meta_data',[]);
