function mergedStochasticWave = ...
    mergeArbitraryWaveSegments( stochasticWaves,...
                                mergedArbitraryWaveformSettings)

mergedStochasticWave = [];

for i=1:1:length(stochasticWaves)
    if(stochasticWaves(i).waveConfig.canBeMerged==1)
        if(isempty(mergedStochasticWave)==1)

            mergedStochasticWave = stochasticWaves(i);

            %Update the file names
            mergedStochasticWave.waveConfig.arbitraryWaveform.fileName = ...
                ['merged_',stochasticWaves(i).waveConfig.arbitraryWaveform.fileName];
            mergedStochasticWave.optionValues(1,1) = ...
                {['merged_',stochasticWaves(i).optionValues{1}]};
            mergedStochasticWave.fileName = ...
                ['merged_',stochasticWaves(i).fileName];
        else
            
            if(mergedStochasticWave.waveConfig.frequencyHz ...
                    == stochasticWaves(i).waveConfig.frequencyHz)

                %Update the data
                nPaddingPoints = ...
                    round(mergedArbitraryWaveformSettings.paddingTime ...
                         *mergedStochasticWave.waveConfig.frequencyHz);
                paddingPoints = zeros(nPaddingPoints,1);
                mergedStochasticWave.fileData = ...
                    [mergedStochasticWave.fileData;...
                    paddingPoints;...
                    stochasticWaves(i).fileData];

                %Update the meta data
                metaFields =...
                    {'bandwidth','amplitude','points','frequencyHz'};
                paddingData=...
                    [0,0,nPaddingPoints,...
                    mergedStochasticWave.waveConfig.frequencyHz];

                for j=1:1:length(metaFields)

                    mergedStochasticWave.metadata.(metaFields{j}) = ...
                    [mergedStochasticWave.metadata.(metaFields{j}),...
                    paddingData(1,j)];

                    mergedStochasticWave.metadata.(metaFields{j}) = ...
                    [mergedStochasticWave.metadata.(metaFields{j}),...
                    stochasticWaves(i).metadata.(metaFields{j})];                        

                end
               
            end
        end
    end
end
