function simulatedSignals = resizeSimulatedCommandFunctionStruct(simulatedSignals)

    simulatedSignals.time = [simulatedSignals.time; ...
                             zeros(size(simulatedSignals.time))];
    simulatedSignals.lengthAbs = [simulatedSignals.lengthAbs; ...
                             zeros(size(simulatedSignals.lengthAbs))];
    simulatedSignals.forceAbs = [simulatedSignals.forceAbs; ...
                             zeros(size(simulatedSignals.forceAbs))];
    simulatedSignals.commandId = [simulatedSignals.commandId; ...
                             zeros(size(simulatedSignals.commandId))];    

