function [programMetaData, segmentMetaDataArray] = ...
    writeActivationBlock600AUpd(fid, auroraConfig, programMetaData,...
                                useMinimalDataRecording)

segmentMetaDataArray(2) = ...
    struct('type','',timeFieldName,[0,0],'meta_data',[]);
idxS=1;

if(useMinimalDataRecording==1)
  assert(programMetaData.dataEnable==0,...
         ['Error: Data-Enable has been called previously.',...
          ' When using minimal data recording mode, Data-Disable',...
          ' should be called prior to calling this function']);
end

%%
%Start recording
%%
if(useMinimalDataRecording==1)
  dataEnableOptions = ...
      getCommandFunctionOptions600A('Data-Enable',auroraConfig);

  isActive=0;
  startTime=programMetaData.nextStartTime;
  [programMetaData,fcnMetaData] =  ...
      writeControlFunction600AUpd(...
          fid,...
          isActive,...
          startTime,...
          auroraConfig.defaultTimeUnit,...
          'Data-Enable',...
          dataEnableOptions,...
          [],...
          auroraConfig,...
          programMetaData,...
          0);
  timeDataDisable = programMetaData.nextStartTime ...
                    +auroraConfig.bath.sampleTime;
end

%%
% Execute the bath change
%%
bathOptions = getCommandFunctionOptions600A('Bath',auroraConfig);

bathOptions(1).value = auroraConfig.bath.preActivation;
bathOptions(2).value = 0;

isActive  = 0;
startTime = programMetaData.nextStartTime;
flag_printMetaDataToFile=1;

[programMetaData,fcnMetaData] =  ...
    writeControlFunction600AUpd(...
        fid,...
        isActive,...
        startTime,...
        auroraConfig.defaultTimeUnit,...
        'Bath',...
        bathOptions,...
        [],...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

segmentMetaDataArray(idxS)=fcnMetaData;
idxS=idxS+1;

%%
% Disable recording
%%
if(useMinimalDataRecording==1)
  dataDisableOptions = ...
      getCommandFunctionOptions600A('Data-Disable',auroraConfig);

  isActive=0;
  dt = max(0,timeDataDisable-programMetaData.nextStartTime);
  startTime=programMetaData.nextStartTime+dt;
  [programMetaData,fcnMetaData] =  ...
      writeControlFunction600AUpd(...
          fid,...
          isActive,...
          startTime,...
          auroraConfig.defaultTimeUnit,...
          'Data-Disable',...
          dataDisableOptions,...
          [],...
          auroraConfig,...
          programMetaData,...
          0);  

end

%%
% Start recording
%%
activationBathStartTime = programMetaData.nextStartTime ...
                        + auroraConfig.bath.preActivationDuration;

%Start recording
if(useMinimalDataRecording==1)
  dataEnableOptions = ...
      getCommandFunctionOptions600A('Data-Enable',auroraConfig);

  isActive=1;
  startTime=activationBathStartTime;
  [programMetaData,fcnMetaData] =  ...
      writeControlFunction600AUpd(...
          fid,...
          isActive,...
          startTime,...
          auroraConfig.defaultTimeUnit,...
          'Data-Enable',...
          dataEnableOptions,...
          [],...
          auroraConfig,...
          programMetaData,...
          0);
  timeDataDisable = programMetaData.nextStartTime ...
                    +auroraConfig.bath.sampleTime;
  assert(programMetaData.nextStartTime >= activationBathStartTime,...
         ['Error: the nextStartTime should be after the pre-calculated',...
          ' activationBathStartTime']);
  activationBathStartTime = programMetaData.nextStartTime;
end

%%
% Move to the activation bath
%%
bathOptions(1).value = auroraConfig.bath.active;
bathOptions(2).value = 0;

flag_printMetaDataToFile=1;

isActive=1;
startTime=activationBathStartTime;

[programMetaData,fcnMetaData] =  ...
    writeControlFunction600AUpd(...
        fid,...
        isActive,...
        startTime,...
        auroraConfig.defaultTimeUnit,...
        'Bath',...
        bathOptions,...
        [],...
        auroraConfig,...
        programMetaData,...
        flag_printMetaDataToFile);

segmentMetaDataArray(idxS)=fcnMetaData;
idxS=idxS+1;

%%
% Disable data recording
%%
if(useMinimalDataRecording==1)
  dataDisableOptions = ...
      getCommandFunctionOptions600A('Data-Disable',auroraConfig);

  isActive=1;
  dt = max(0,timeDataDisable-programMetaData.nextStartTime);
  startTime=programMetaData.nextStartTime+dt;
  
  [programMetaData,fcnMetaData] =  ...
      writeControlFunction600AUpd(...
          fid,...
          isActive,...
          startTime,...
          auroraConfig.defaultTimeUnit,...
          'Data-Disable',...
          dataDisableOptions,...
          [],...
          auroraConfig,...
          programMetaData,...
          0);  

end
